package com.podhod.app;
import android.app.*;import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import org.json.*;
public class LanguageSmoke extends Instrumentation {
 volatile MainActivity latest;
 public void onCreate(Bundle b){super.onCreate(b);start();}
 void check(boolean v,String m){if(!v)throw new AssertionError(m);}
 void main(Runnable r){final Throwable[] e={null};runOnMainSync(()->{try{r.run();}catch(Throwable t){e[0]=t;}});if(e[0]!=null)throw new AssertionError(e[0]);}
 TextView find(View v,String text){if(v instanceof TextView&&((TextView)v).getText().toString().equals(text))return (TextView)v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){TextView t=find(((ViewGroup)v).getChildAt(i),text);if(t!=null)return t;}return null;}
 void english(View v){if(v instanceof TextView&&!(v instanceof EditText)){String s=((TextView)v).getText().toString();if(!s.equals("Русский")&&!s.equals("✓  Русский"))check(!s.matches("(?s).*[А-Яа-яЁё].*"),"Untranslated UI: "+s);}if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++)english(((ViewGroup)v).getChildAt(i));}
 void capture(MainActivity a,String page,String filename){main(()->{try{a.page=page;a.render();english(a.root);View v=a.root;int w=a.getResources().getDisplayMetrics().widthPixels,h=a.getResources().getDisplayMetrics().heightPixels;v.measure(View.MeasureSpec.makeMeasureSpec(w,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(h,View.MeasureSpec.EXACTLY));v.layout(0,0,w,h);Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);v.draw(new Canvas(b));try(FileOutputStream out=getTargetContext().openFileOutput(filename,0)){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();}catch(Exception e){throw new RuntimeException(e);}});}
 public void onStart(){String originalLanguage=Lang.english()?"en":"ru";String original=Store.get(getTargetContext()).data.toString();Bundle report=new Bundle();int code=Activity.RESULT_CANCELED;
 Application app=(Application)getTargetContext().getApplicationContext();Application.ActivityLifecycleCallbacks callbacks=new Application.ActivityLifecycleCallbacks(){public void onActivityResumed(Activity a){if(a instanceof MainActivity)latest=(MainActivity)a;}public void onActivityCreated(Activity a,Bundle b){}public void onActivityStarted(Activity a){}public void onActivityPaused(Activity a){}public void onActivityStopped(Activity a){}public void onActivitySaveInstanceState(Activity a,Bundle b){}public void onActivityDestroyed(Activity a){}};app.registerActivityLifecycleCallbacks(callbacks);
 try{
 main(()->Lang.set(getTargetContext(),"ru"));latest=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));MainActivity before=latest;
 main(()->{before.page="settings";before.render();TextView choice=find(before.root,"English");check(choice!=null,"English selector missing");choice.performClick();});
 for(int i=0;i<30&&latest==before;i++)Thread.sleep(100);waitForIdleSync();check(latest!=before,"Language change did not recreate activity");check(latest.page.equals("settings"),"Language change left settings");check(Lang.english(),"English not selected");check(getTargetContext().getSharedPreferences("trace-settings",0).getString("language","").equals("en"),"Language not persisted");main(()->Lang.init(getTargetContext()));check(Lang.english(),"Language lost on initialization");
 for(String page:new String[]{"settings","mine","library","workout","progress","history","steps"})capture(latest,page,"en-"+page+".png");
 main(()->{latest.page="progress";latest.render();WalkingProgress walking=latest.walkingProgress;check(walking!=null,"Walking card missing");walking.chart.getChildAt(0).performClick();check(walking.selected.equals(java.time.LocalDate.now().minusDays(6)),"Chart selection failed");check(!walking.detail.getText().toString().isEmpty(),"Selected day details missing");walking.chart.getChildAt(6).performClick();check(walking.selected.equals(java.time.LocalDate.now()),"Today selection failed");check(walking.steps.getText().toString().equals(StepsPage.format(Steps.today(latest))),"Walking total mismatch");});
 main(()->latest.selected="builtin-sheiko-12-week");capture(latest,"program","en-sheiko-cycle.png");
 main(()->Lang.set(getTargetContext(),"ru"));
 main(()->{latest.page="program";latest.render();View v=latest.root;int w=latest.getResources().getDisplayMetrics().widthPixels,h=latest.getResources().getDisplayMetrics().heightPixels;v.measure(View.MeasureSpec.makeMeasureSpec(w,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(h,View.MeasureSpec.EXACTLY));v.layout(0,0,w,h);Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);v.draw(new Canvas(b));try(FileOutputStream out=getTargetContext().openFileOutput("ru-sheiko-cycle.png",0)){b.compress(Bitmap.CompressFormat.PNG,100,out);}catch(Exception e){throw new RuntimeException(e);}b.recycle();Lang.set(getTargetContext(),"en");});
 main(()->{latest.error(new IllegalArgumentException(Lang.t("Некорректный вес")));});
 check(Lang.content("Неделя 2 · День 3").equals("Week 2 · Day 3"),"Built-in day not translated");check(Lang.content("Мой личный план 42").equals("Мой личный план 42"),"Custom name changed");
 for(var n:getTargetContext().getSystemService(NotificationManager.class).getActiveNotifications())if(n.getId()==7){String title=n.getNotification().extras.getCharSequence(Notification.EXTRA_TITLE,"").toString();check(!title.matches(".*[А-Яа-я].*"),"Notification not translated");}
 main(()->{Lang.set(getTargetContext(),"ru");latest.page="settings";latest.render();check(find(latest.root,"Настройки")!=null,"Russian switch back failed");});
 check(original.equals(Store.get(getTargetContext()).data.toString()),"Language changed workout data");report.putString("stream","PASS: language picker, recreation, persistence, six English screens, built-in names, notification, Russian return, unchanged workout data.\n");code=Activity.RESULT_OK;
 }catch(Throwable e){report.putString("stream","FAIL: "+e+"\n");}finally{main(()->{Lang.set(getTargetContext(),originalLanguage);Notices.update(getTargetContext());if(latest!=null){latest.page="settings";latest.render();}});app.unregisterActivityLifecycleCallbacks(callbacks);}finish(code,report);}
}
