package com.podhod.app;
import android.app.*;
import android.content.Intent;
import android.graphics.*;
import android.os.Bundle;
import android.view.View;
import java.io.FileOutputStream;

/** Visual preview only; does not reset onboarding or change the signed-in account. */
public class WelcomeSmoke extends Instrumentation {
 boolean settings,friends,liveFriends,privacyEyes,friendPage,ownProfile,chatPreview,avatarStartup,gmailPreview,scrollPreview;
 public void onCreate(Bundle b){super.onCreate(b);scrollPreview="scroll".equals(b.getString("preview"));gmailPreview="gmail".equals(b.getString("preview"));avatarStartup="avatar-startup".equals(b.getString("preview"));chatPreview="chat".equals(b.getString("preview"));ownProfile="own-profile".equals(b.getString("preview"));friendPage="friend-page".equals(b.getString("preview"));settings="settings".equals(b.getString("preview"));friends="friends".equals(b.getString("preview"));liveFriends=ownProfile||"friends-live".equals(b.getString("preview"));privacyEyes="privacy-eyes".equals(b.getString("preview"));start();}
 public void onStart(){Bundle result=new Bundle();final Throwable[] failure={null};
  MainActivity a=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));
  if(scrollPreview){ScrollSmoke.verify(this,a);return;}
  if(gmailPreview){try{new FriendsStore().gmailVisible();}catch(Exception e){failure[0]=e;}final AlertDialog[] dialog={null};runOnMainSync(()->{try{if(failure[0]!=null)throw new IllegalStateException(failure[0]);dialog[0]=GmailFriends.add(a);}catch(Throwable e){failure[0]=e;}});android.os.SystemClock.sleep(800);runOnMainSync(()->{try{if(failure[0]!=null)return;View v=dialog[0].getWindow().getDecorView();Bitmap b=Bitmap.createBitmap(v.getWidth(),v.getHeight(),Bitmap.Config.ARGB_8888);v.draw(new Canvas(b));try(FileOutputStream out=a.openFileOutput("gmail-friends.png",0)){b.compress(Bitmap.CompressFormat.PNG,100,out);}b.recycle();}catch(Throwable e){failure[0]=e;}});result.putString("stream",failure[0]==null?"PASS: own Gmail discovery setting read and add-friend form rendered. No lookup enabled and no friend request sent.\n":"FAIL: "+failure[0]);finish(failure[0]==null?Activity.RESULT_OK:Activity.RESULT_CANCELED,result);return;}
  if(avatarStartup){android.os.SystemClock.sleep(5000);runOnMainSync(()->{try{if(a.friendsState!=null)throw new AssertionError("Profile page should not be loaded");View current=a.profileButton.getChildAt(0);if(!(current instanceof FriendsProfile.Portrait)||((FriendsProfile.Portrait)current).image==null)throw new AssertionError("Startup did not load avatar");a.headerProfile=null;a.render();View cached=a.profileButton.getChildAt(0);if(!(cached instanceof FriendsProfile.Portrait)||((FriendsProfile.Portrait)cached).image==null)throw new AssertionError("Cached avatar missing from first frame");FriendsProfile.Header isolated=new FriendsProfile.Header(a,"different-test-account");if(!isolated.portrait.isEmpty())throw new AssertionError("Avatar leaked between accounts");FriendsProfile.remember(a,a.headerProfile.portrait.isEmpty()?new java.util.HashMap<>():new java.util.HashMap<>(a.headerProfile.portrait));}catch(Throwable e){failure[0]=e;}});result.putString("stream",failure[0]==null?"PASS: startup avatar, immediate cached frame and account isolation.\n":"FAIL: "+failure[0]);finish(failure[0]==null?Activity.RESULT_OK:Activity.RESULT_CANCELED,result);return;}
  FriendsPanel.State social=new FriendsPanel.State();
  if(liveFriends||privacyEyes||friendPage||chatPreview)try{FriendsStore backend=new FriendsStore();social.profile=backend.profileData();social.privacy=backend.privacyData();social.connections=backend.connections();social.items=backend.ownItems();social.portrait=backend.portrait(backend.uid);for(var c:social.connections)if("accepted".equals(c.getString("status")))social.portraits.put(backend.peer(c),backend.portrait(backend.peer(c)));}catch(Exception e){failure[0]=e;}
  if(chatPreview){final FriendChat[] chat={null};runOnMainSync(()->{try{if(failure[0]!=null)throw new IllegalStateException(failure[0]);var c=social.connections.stream().filter(v->"accepted".equals(v.getString("status"))).findFirst().orElseThrow();FriendsStore b=new FriendsStore();chat[0]=FriendChat.open(a,c.getId(),FriendsProfile.name(social.portraits.get(b.peer(c)),b.peerName(c)));}catch(Throwable e){failure[0]=e;}});android.os.SystemClock.sleep(5000);runOnMainSync(()->{try{if(failure[0]!=null)throw new IllegalStateException(failure[0]);if(chat[0].first)throw new AssertionError("No server-authorized chat snapshot");View v=chat[0].root;Bitmap bitmap=Bitmap.createBitmap(v.getWidth(),v.getHeight(),Bitmap.Config.ARGB_8888);v.draw(new Canvas(bitmap));try(FileOutputStream out=a.openFileOutput("friend-chat.png",0)){bitmap.compress(Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();chat[0].input.requestFocus();((android.view.inputmethod.InputMethodManager)a.getSystemService(android.content.Context.INPUT_METHOD_SERVICE)).showSoftInput(chat[0].input,0);}catch(Throwable e){failure[0]=e;}});android.os.SystemClock.sleep(1000);runOnMainSync(()->{try{if(failure[0]!=null)return;View v=chat[0].root;if(android.os.Build.VERSION.SDK_INT>=30){var insets=v.getRootWindowInsets();int bottom=insets.getInsets(android.view.WindowInsets.Type.ime()).bottom;if(v.getPaddingBottom()<bottom)throw new AssertionError("Keyboard overlaps composer");}}catch(Throwable e){failure[0]=e;}});result.putString("stream",failure[0]==null?"PASS: chat server read and keyboard insets. No messages sent.\n":"FAIL: "+failure[0]);finish(failure[0]==null?Activity.RESULT_OK:Activity.RESULT_CANCELED,result);return;}
  if(friendPage){
   final FriendPage[] page={null};
   runOnMainSync(()->{try{if(failure[0]!=null)throw new IllegalStateException(failure[0]);var c=social.connections.stream().filter(v->"accepted".equals(v.getString("status"))).findFirst().orElseThrow();String peer=new FriendsStore().peer(c);var details=social.portraits.get(peer);page[0]=FriendPage.open(a,peer,FriendsProfile.name(details,FriendsPanel.uid(a).equals(c.getString("from"))?c.getString("toName"):c.getString("fromName")),details,c.getId());}catch(Throwable e){failure[0]=e;}});
   android.os.SystemClock.sleep(5000);
   runOnMainSync(()->{try{if(failure[0]!=null)throw new IllegalStateException(failure[0]);if(page[0].busy)throw new AssertionError("Profile did not finish loading");page[0].tabs.getChildAt(2).performClick();if(!"walk".equals(page[0].filter))throw new AssertionError("Walk tab failed");page[0].tabs.getChildAt(1).performClick();if(!"plan".equals(page[0].filter))throw new AssertionError("Plan tab failed");page[0].tabs.getChildAt(0).performClick();View view=page[0].root;android.view.WindowInsets insets=view.getRootWindowInsets();if(insets==null)throw new AssertionError("Missing window insets");int safeTop=android.os.Build.VERSION.SDK_INT>=30?insets.getInsets(android.view.WindowInsets.Type.systemBars()|android.view.WindowInsets.Type.displayCutout()).top:insets.getSystemWindowInsetTop();if(view.getPaddingTop()<safeTop)throw new AssertionError("Profile overlaps status bar");int safeBottom=android.os.Build.VERSION.SDK_INT>=30?insets.getInsets(android.view.WindowInsets.Type.systemBars()).bottom:insets.getSystemWindowInsetBottom();if(view.getPaddingBottom()<safeBottom)throw new AssertionError("Profile overlaps navigation bar");Bitmap bitmap=Bitmap.createBitmap(view.getWidth(),view.getHeight(),Bitmap.Config.ARGB_8888);view.draw(new Canvas(bitmap));try(FileOutputStream out=a.openFileOutput("friend-page.png",0)){bitmap.compress(Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();}catch(Throwable e){failure[0]=e;}});
   result.putString("stream",failure[0]==null?"PASS: friend profile loaded and rendered without publishing data.\n":"FAIL: "+failure[0]);finish(failure[0]==null?Activity.RESULT_OK:Activity.RESULT_CANCELED,result);return;
  }
  runOnMainSync(()->{try{
   if(failure[0]!=null)throw new IllegalStateException(failure[0]);
   if(privacyEyes){a.page="mine";a.render();a.body.removeAllViews();a.heading("Privacy","Choose what friends can see");PrivacyEye.Controller controller=new PrivacyEye.Controller(a,FriendsPanel.uid(a));a.privacyEyes=controller;controller.loaded=true;controller.categories=social.privacy;for(var item:social.items)controller.items.put(item.getId(),item.getData());org.json.JSONObject plan=a.store.data.optJSONArray("programs").optJSONObject(0);if(plan!=null){android.widget.LinearLayout card=a.card(a.body);card.addView(a.title(Lang.content(plan.optString("name")),22));PrivacyEye.add(a,card,"plan",plan);}org.json.JSONArray walks=Walks.data(a).optJSONArray("history");if(walks.length()>0){org.json.JSONObject walk=walks.optJSONObject(walks.length()-1);android.widget.LinearLayout card=a.card(a.body);card.addView(a.title("Walk · "+FriendsPanel.walkName(walk),20));PrivacyEye.add(a,card,"walk",walk);}}else if(liveFriends){a.page=ownProfile?"profile":"friends";a.render();a.body.removeAllViews();a.heading(ownProfile?"My profile":"Friends",ownProfile?"Your photo, your name, your training.":"Your circle. Your choice of what to share.");if(social.profile==null)throw new AssertionError("Expected created profile");if(ownProfile){a.friendsState=social;FriendsPanel.own(a,a.body,social);FriendsProfile.headerImage(a);a.profileButton.performClick();if(!"profile".equals(a.page))throw new AssertionError("Profile navigation failed");}else FriendsPanel.draw(a,a.body,social);View unchanged=a.root;for(int i=0;i<20;i++)a.changed.onReceive(a,new Intent("com.podhod.app.CHANGED"));if(a.root!=unchanged)throw new AssertionError("Sync broadcasts rebuilt Friends");Bitmap fixture=Bitmap.createBitmap(640,320,Bitmap.Config.ARGB_8888);fixture.eraseColor(Color.BLUE);FriendsProfile.Portrait crop=new FriendsProfile.Portrait(a,fixture,"A",true);crop.frame.zoom=2;Bitmap decoded=PlanImages.decode(crop.encode());if(decoded==null||decoded.getWidth()!=256||decoded.getHeight()!=256)throw new AssertionError("Avatar crop encoding failed");fixture.recycle();}else if(friends){a.page="friends";a.render();a.body.removeAllViews();a.heading("Friends","Your circle. Your choice of what to share.");FriendsPanel.create(a,a.body);}else if(settings){a.page="settings";a.render();}else WelcomeScreen.show(a);View root=a.root;
   root.measure(View.MeasureSpec.makeMeasureSpec(1080,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(2200,View.MeasureSpec.EXACTLY));root.layout(0,0,1080,2200);
   Bitmap bitmap=Bitmap.createBitmap(1080,2200,Bitmap.Config.ARGB_8888);root.draw(new Canvas(bitmap));
   try(FileOutputStream out=a.openFileOutput(ownProfile?"own-profile.png":privacyEyes?"privacy-eyes.png":liveFriends?"friends-live.png":friends?"friends-preview.png":settings?"settings-preview.png":"welcome-preview.png",0)){bitmap.compress(Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();
  }catch(Throwable e){failure[0]=e;}finally{a.render();}});
  result.putString("stream",failure[0]==null?"PASS: preview rendered; live Friends verifies 20 broadcasts preserve the root and avatar crop encoding. Account and onboarding unchanged.\n":"FAIL: "+failure[0]);finish(failure[0]==null?Activity.RESULT_OK:Activity.RESULT_CANCELED,result);
 }
}
