package com.podhod.app;
import android.widget.*;
import org.json.*;
import java.util.*;
final class AdvancedUi {
 static void panel(MainActivity a,LinearLayout parent,JSONObject p,boolean inline){LinearLayout c=inline?parent:a.card(parent);c.addView(a.title(EnglishPlanText.text("Злат · Продвинутый"),22));c.addView(a.text(EnglishPlanText.text("3 недели · 9 занятий · нагрузка по результату"),14,a.MUTED));JSONObject ws=p.optJSONObject("advancedWeights");if(ws!=null)for(String lift:new String[]{"dip","pullup"})c.addView(a.text(Lang.t(lift.equals("dip")?"Брусья":"Турник")+" · "+Engine.number(ws.optJSONObject(lift).optDouble("heavy"))+Lang.t(" кг"),18,a.GREEN));a.button(c,Lang.t("Настроить начальные веса"),false,()->setup(a,p,()->{}));a.hint(c,Lang.t("Правила и источник"),EnglishPlanText.text("Проценты учитывают половину массы тела: (1ПМ + масса / 2) × процент − масса / 2. Округление вниз до 1,25 кг. После тяжёлого и технического блоков оцени все подходы: с запасом — +2,5 кг; уверенно — +1,25 кг; на пределе — удержать. При недоборе повторов тяжёлый или технический блок снижается на 5%. Объём: минимум 6 повторов — +2,5 кг; 5 — +1,25 кг; иначе удержать. Это адаптация Trace: без 0,5 кг, максимум выбирается вручную, подготовительные веса меняются вместе с тяжёлым блоком. В цикле сохраняй указанные дни отдыха."));a.link(c,Lang.t("Источник программы"),()->a.startActivity(new android.content.Intent(android.content.Intent.ACTION_VIEW,android.net.Uri.parse(ZlatAdvanced.SOURCE))));}
 static void setup(MainActivity a,JSONObject p,Runnable after){LinearLayout box=a.form();box.addView(a.text(Lang.t("Укажи известные максимумы дополнительного веса и массу тела. Будущие занятия пересчитаются; текущие подходы сохранятся."),14,a.MUTED));EditText pull=a.input(box,Lang.t("Турник · 1ПМ, кг"),"",true),dip=a.input(box,Lang.t("Брусья · 1ПМ, кг"),"",true),body=a.input(box,Lang.t("Масса тела, кг"),p.has("bodyWeight")?Engine.number(p.optDouble("bodyWeight")):"",true);a.formDialog(Lang.t("Начальные веса"),box,Lang.t("Сохранить"),()->{ZlatAdvanced.configure(p,a.positive(pull,false),a.positive(dip,false),a.positive(body,false));a.store.save();a.render();after.run();});}
 static void finish(MainActivity a,JSONObject s){if(Engine.doneCount(s)!=s.optJSONArray("sets").length())return;LinearLayout box=a.form();box.addView(a.text(Lang.t("Проверь реальные повторы и оцени весь блок. Если хотя бы один подход был на пределе, оставь вес."),14,a.MUTED));ArrayList<JSONObject> targets=new ArrayList<>();ArrayList<EditText> fields=new ArrayList<>();LinkedHashMap<String,Spinner> ratings=new LinkedHashMap<>();JSONArray sets=s.optJSONArray("sets");for(int i=0;i<sets.length();i++){JSONObject set=sets.optJSONObject(i);String block=set.optString("advancedBlock"),lift=set.optString("advancedLift");if(!block.equals("heavy")&&!block.equals("volume")&&!block.equals("technique"))continue;String key=lift+"_"+block;String label=Lang.t(lift.equals("dip")?"Брусья":"Турник")+" · "+Lang.t(block.equals("heavy")?"Сила":block.equals("volume")?"Объём":"Техника");if(!block.equals("volume")&&!ratings.containsKey(key)){box.addView(a.text(label,17,a.GREEN));Spinner rating=new Spinner(a);ArrayAdapter<String> adapter=new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{Lang.t("На пределе · оставить вес"),Lang.t("Уверенно · +1,25 кг"),Lang.t("С запасом · +2,5 кг")});rating.setAdapter(adapter);box.addView(rating);ratings.put(key,rating);}targets.add(set);fields.add(a.input(box,label+" · "+Lang.t("Подход ")+set.optInt("ordinal"),String.valueOf(set.optInt("reps")),true));}int revision=s.optInt("revision");a.formDialog(Lang.t("Результат занятия"),box,Lang.t("Сохранить и рассчитать веса"),()->{if(a.store.active()!=s||s.optInt("revision")!=revision)throw new IllegalArgumentException(Lang.t("Подходы изменились. Открой сохранение заново."));int[] reps=new int[fields.size()];for(int i=0;i<reps.length;i++)reps[i]=a.integer(fields.get(i),1000);JSONObject effort=new JSONObject();for(Map.Entry<String,Spinner> e:ratings.entrySet())Engine.put(effort,e.getKey(),e.getValue().getSelectedItemPosition());for(int i=0;i<reps.length;i++)Engine.put(targets.get(i),"reps",reps[i]);Engine.put(s,"advancedEffort",effort);Engine.put(s,"confirmedRevision",revision);a.act("finish");});}
}
