package com.podhod.app;
import java.util.*;
/** Canonical built-in content. Independent of the selected interface language. */
final class EnglishPlanText {
 private static final Map<String,String> TEXT=new LinkedHashMap<>();
 static {
  TEXT.put(" · День "," · Day ");
  TEXT.put(" кг"," kg");
  TEXT.put(" подхода"," sets");
  TEXT.put("12 НЕДЕЛЬ · К СОРЕВНОВАНИЯМ","12 WEEKS · COMPETITION PREP");
  TEXT.put("Dead bug — каждая сторона","Dead bug — each side");
  TEXT.put("Nerd Fitness · начальный комплекс. Одна гантель и устойчивая опора. Разминка перед занятием; 2 круга, занятия в несмежные дни. Тяга — 10 на каждую руку, шаги — 10 на сторону. Планка: одна отметка означает удержание 15–30 секунд. Вес гантели выбери в редакторе. 12 занятий — организация дневника Trace, не авторский срок программы.","Nerd Fitness beginner workout. One dumbbell and a stable support. Warm up first; complete 2 circuits on non-consecutive days. Rows: 10 per arm; walking jacks: 10 per side. One plank entry means a 15–30 second hold. Set your dumbbell weight in the editor. The 12 sessions organize the Trace log; they are not an original program duration.");
  TEXT.put("sheyko.xlsx · План тренировок разрядников из книги Б. И. Шейко «Пауэрлифтинг»","sheyko.xlsx · Training plan for ranked lifters from B. I. Sheiko’s Powerlifting");
  TEXT.put("Адаптация Recommended Routine. Турник, оборудование для горизонтальных подтягиваний и брусьев, резинка для жима Палофа и устойчивая опора для обратной гиперэкстензии. 3 занятия в неделю через день. Разминка 5–10 минут. Первые 6 упражнений выполняются парами, по 3 круга; затем 3 круга на корпус. Отдых между подходами пары около 90 секунд, в блоке корпуса — 60 секунд. Выбери подходящий вариант каждого упражнения: начни с 3×5, дойди до 3×8 и усложни вариант. Корпус: 3×8–12. Прогрессию меняй вручную в редакторе. Односторонние упражнения — на каждую сторону. Здесь выбраны стартовые варианты ног и корпуса, их можно заменить по источнику. 12 занятий — четыре недели дневника.","Recommended Routine adaptation. Pull-up bar, equipment for rows and dips, a band for Pallof presses, and a stable support for reverse hyperextensions. Train 3 times per week on non-consecutive days. Warm up for 5–10 minutes. Alternate each of the first three exercise pairs for 3 rounds, then do 3 core rounds. Rest about 90 seconds between paired sets and 60 seconds in the core block. Select appropriate variations: begin at 3×5, reach 3×8, then choose a harder variation. Core: 3×8–12. Update progression manually in the editor. Unilateral reps are per side. Starting leg and core variations are selected here; alternatives are in the source. Twelve sessions organize four weeks of logging.");
  TEXT.put("Базовая схема 2018 года: 3 занятия в неделю, 3–4 подхода по 5–8 повторений. Здесь 12 занятий для удобства дневника, а не авторский срок цикла. Между занятиями — день отдыха. После цикла можно создать копию.","Base routine from 2018: 3 workouts per week, 3–4 sets of 5–8 reps. The 12 workouts are a journal layout, not a prescribed cycle length. Take a rest day between workouts. Copy the plan for a new cycle.");
  TEXT.put("Брусья","Dips");
  TEXT.put("Брусья с весом","Weighted dips");
  TEXT.put("Брусья — свой уровень","Dips — your progression");
  TEXT.put("Брусья: ","Dips: ");
  TEXT.put("В ","In ");
  TEXT.put("Вс","Sun");
  TEXT.put("Вт","Tue");
  TEXT.put("Выбери вес попытки вручную. Запиши успешный результат; не отмечай неудачную попытку выполненной.","Choose your attempt weight manually. Record a successful result; do not mark a failed attempt as completed.");
  TEXT.put("Гиперэкстензии","Back extension");
  TEXT.put("Горизонтальные подтягивания","Inverted rows");
  TEXT.put("День ","Day ");
  TEXT.put("Домашняя","Home training");
  TEXT.put("Жим Палофа с резинкой — каждая сторона","Band Pallof press — each side");
  TEXT.put("Жим из-за головы","Behind-the-neck press");
  TEXT.put("Жим лёжа","Bench press");
  TEXT.put("Жим ногами","Leg press");
  TEXT.put("Жим сидя под углом","Incline seated press");
  TEXT.put("Злат · intermediate","Zlat · Intermediate");
  TEXT.put("Злат · Начальный","Zlat · Beginner");
  TEXT.put("Злат · Продвинутый","Zlat · Advanced");
  TEXT.put("Злат · Средний","Zlat · Intermediate");
  TEXT.put("КМС / МС · ПОДГОТОВКА","CMS / MS · PREPARATION");
  TEXT.put("Контрольная техника, без отказа. На брусьях — пауза внизу; на турнике — полный вис перед подъёмом.","Controlled form, no failure. Pause at the bottom on dips; start pull-ups from a dead hang.");
  TEXT.put("Контрольный день","Top-set day");
  TEXT.put("Контрольный подход · 4–6 повторений. Результат задаёт вес следующей недели.","Top set · 4–6 reps. Your result sets next week’s heavy weight.");
  TEXT.put("Лёгкая техника","Light technique");
  TEXT.put("Матвей Злат · турник и брусья","Zlat · Beginner");
  TEXT.put("НАЧАЛЬНЫЙ · 3 ДНЯ В НЕДЕЛЮ","BEGINNER · 3 DAYS A WEEK");
  TEXT.put("Наклон со штангой сидя","Seated good morning");
  TEXT.put("Наклонный жим","Incline bench press");
  TEXT.put("Наклоны good morning без веса","Bodyweight good mornings");
  TEXT.put("Наклоны на одной ноге без веса","Single-leg bodyweight deadlifts");
  TEXT.put("Наклоны сидя","Seated good mornings");
  TEXT.put("Наклоны со штангой стоя","Standing good morning");
  TEXT.put("Наклоны стоя","Good mornings");
  TEXT.put("Неделя ","Week ");
  TEXT.put("Неделя 1 · Вс · Двойные паузы","Week 1 · Sun · Double pauses");
  TEXT.put("Неделя 1 · Вт · Двойные паузы","Week 1 · Tue · Double pauses");
  TEXT.put("Неделя 1 · Пн · Сила и объём","Week 1 · Mon · Strength and volume");
  TEXT.put("Неделя 1 · Пт · Сила и объём","Week 1 · Fri · Strength and volume");
  TEXT.put("Неделя 1 · Чт · Восстановление","Week 1 · Thu · Recovery");
  TEXT.put("Неделя 12 · Соревнования №36. В таблице нет весов и попыток для этого дня.","Week 12 · Competition #36. The spreadsheet does not specify weights or attempts for this day.");
  TEXT.put("Неделя 2 · Сб · Подготовка","Week 2 · Sat · Preparation");
  TEXT.put("Неделя 2 · Ср · Разгрузка","Week 2 · Wed · Deload");
  TEXT.put("Неделя 3 · Вт · Проверка максимума","Week 3 · Tue · Max test");
  TEXT.put("Неделя 3 · Пт · Следующий цикл","Week 3 · Fri · Next cycle");
  TEXT.put("Обратная гиперэкстензия","Reverse hyperextensions");
  TEXT.put("Объём","Volume");
  TEXT.put("Объёмный блок · 4–6 повторений. Прогрессия по худшему подходу.","Volume block · 4–6 reps. Progression uses the lowest rep count.");
  TEXT.put("Отжимания от возвышения или с колен","Incline or knee push-ups");
  TEXT.put("Отжимания от пола (руки на ширине плеч)","Shoulder-width push-ups");
  TEXT.put("Отжимания от пола (руки шире плеч)","Wide-grip push-ups");
  TEXT.put("Отжимания — свой уровень","Push-ups — your progression");
  TEXT.put("ПРОДВИНУТЫЙ · ЦИКЛ 3 НЕДЕЛИ","ADVANCED · 3-WEEK CYCLE");
  TEXT.put("Пауза","Paused");
  TEXT.put("Пауза в полном висе, затем быстрый подъём. Без раскачки.","Pause in a full dead hang, then pull up explosively. No swinging.");
  TEXT.put("Пауза на 3 счёта в верхней и нижней точках каждого повторения.","Pause for 3 counts at the top and bottom of each rep.");
  TEXT.put("Пауза на 3 счёта внизу каждого повторения.","Pause for 3 counts at the bottom of each rep.");
  TEXT.put("План 1 подготовительный","Preparation · Block 1");
  TEXT.put("План 2 подготовительный","Preparation · Block 2");
  TEXT.put("План 3 соревновательный","Competition · Block 3");
  TEXT.put("Планка с колен · 15–30 секунд","Knee plank · 15–30 seconds");
  TEXT.put("Пн","Mon");
  TEXT.put("Подготовительный цикл · 4 недели · Б. И. Шейко","Preparatory cycle · 4 weeks · B. I. Sheiko");
  TEXT.put("Подтягивания с весом","Weighted pull-ups");
  TEXT.put("Подтягивания — свой уровень","Pull-ups — your progression");
  TEXT.put("Подтягивания: ","Pull-ups: ");
  TEXT.put("Подъем штанги на трицепсы","Barbell triceps extension");
  TEXT.put("Попеременный жим гантелей сидя","Seated alternating dumbbell press");
  TEXT.put("Пресс","Abs");
  TEXT.put("Присед","Squat");
  TEXT.put("Присед со штангой на груди","Front squat");
  TEXT.put("Приседания в глубину","Deep squat");
  TEXT.put("Приседания с поддержкой","Assisted squats");
  TEXT.put("Приседания со штангой в \"ножницах\"","Barbell split squat");
  TEXT.put("Приседания — свой уровень","Squats — your progression");
  TEXT.put("Проверь максимумы и массу тела","Check your maxes and body weight");
  TEXT.put("Прогресс","Progress");
  TEXT.put("Проходка: в исходном плане есть подходы до 105% от заданных максимумов.","Max test: the source plan includes sets up to 105% of the entered maxes.");
  TEXT.put("Пт","Fri");
  TEXT.put("Разведение рук с гантелями лежа","Dumbbell fly");
  TEXT.put("Разводка","Dumbbell fly");
  TEXT.put("Разгибание бедра в тренажере","Machine hip extension");
  TEXT.put("Разгибания рук","Triceps extensions");
  TEXT.put("СРЕДНИЙ · 3 ДНЯ В НЕДЕЛЮ","INTERMEDIATE · 3 DAYS A WEEK");
  TEXT.put("Сб","Sat");
  TEXT.put("Сила","Strength");
  TEXT.put("Ср","Wed");
  TEXT.put("Становая тяга","Deadlift");
  TEXT.put("Три разных дня: объём, лёгкая техника, контрольный подход. Адаптация Trace: без прибавок 0,5 кг и без автоматических тестов 1ПМ. 12 занятий — четыре обычные недели.","Three distinct days: volume, light technique and a top set. Trace adaptation: no 0.5 kg increases or automatic 1RM tests. 12 sessions cover four regular weeks.");
  TEXT.put("Трёхнедельный цикл: объём, восстановление, реализация. 9 занятий. Адаптация Trace без микроблинов; оценка тяжести перед сохранением. Максимальные попытки выбираются вручную.","A three-week cycle: volume, recovery, realization. 9 sessions. Trace adaptation without microplates; rate difficulty before saving. Choose max attempts manually.");
  TEXT.put("Тяга гантели — каждая рука","Dumbbell row — each arm");
  TEXT.put("Тяга до колен","Deadlift to knees");
  TEXT.put("Тяга из ямы","Deficit deadlift");
  TEXT.put("Тяга на подставке","Deficit deadlift");
  TEXT.put("Тяга с плинтов","Block pull");
  TEXT.put("Тяжёлый блок · 3 подхода по 3 повторения.","Heavy block · 3 sets of 3 reps.");
  TEXT.put("Удерживай 15–30 секунд. 1 повтор в журнале = одно удержание.","Hold for 15–30 seconds. 1 logged rep = one hold.");
  TEXT.put("Укажи дополнительный вес от 0 до 1995 кг и 3 или 4 подхода","Enter additional weight from 0 to 1995 kg and 3 or 4 sets");
  TEXT.put("Укажи максимумы от 1,25 до 1900 кг","Enter maximum added weights from 1.25 to 1900 kg");
  TEXT.put("Цикл для разрядников из файла sheyko.xlsx: недели 1–8 — подготовка, 9–12 — соревновательный этап. 35 тренировок; затем соревнования №36 без заданных попыток. Веса — проценты от твоих максимумов, округление 0,5 кг. Подсобные веса выбираются вручную. В расхождениях между краткой записью и ячейками использованы подробные ячейки подходов.","A graded-lifter cycle from sheyko.xlsx: weeks 1–8 build up, weeks 9–12 prepare for competition. 35 workouts, then competition #36 with no prescribed attempts. Weights follow your maxes, rounded to 0.5 kg. Choose accessory weights manually. Where the summary and detailed cells differ, the detailed set cells are used.");
  TEXT.put("Чт","Thu");
  TEXT.put("Шаги jumping jack — каждая сторона","Walking jacks — each side");
  TEXT.put("Шейко · 12 недель к соревнованиям","Sheiko · Competition");
  TEXT.put("Шейко · КМС / МС","Sheiko · Preparation");
  TEXT.put("Шейко · Подготовка","Sheiko · Preparation");
  TEXT.put("Шейко · Соревнования","Sheiko · Competition");
  TEXT.put("Широчайшие мышцы","Lat exercise");
  TEXT.put("Широчайшие на блоке","Lat pulldown");
  TEXT.put("кг","kg");
  TEXT.put("наклоны стоя","Good mornings");
  TEXT.put("от 0","from 0");
  TEXT.put("раз","reps");
  TEXT.put("Открытая схема Злата 2018 года, по русскому переводу ролика.\n\nПоследний подход: 8 и более повторений → +5 кг; 7 → +2,5 кг; 6 → +1,25 кг; 5 и меньше → без прибавки. Адаптация Trace под блины от 1,25 кг: прибавка 0,5 кг отключена. Расчёт отдельно для каждого упражнения, от веса последнего подхода по порядку в плане.\n\nНачинай с веса, с которым можешь выполнить 10–12 чистых повторений, работая в диапазоне 5–8. Разминочные подходы выполняй отдельно.\n\n12 занятий — организация дневника, не авторское ограничение длительности. В конце можно создать копию цикла. Исторические результаты не пересчитываются.","Zlat's public 2018 routine, based on the Russian translation of his video.\n\nFinal set: 8+ reps → +5 kg; 7 → +2.5 kg; 6 → +1.25 kg; 5 or fewer → no increase. Trace adaptation for plates starting at 1.25 kg: the 0.5 kg increase is disabled. Each exercise is calculated separately, using the weight of its final planned set.\n\nStart with a weight you can lift for 10–12 clean reps and train in the 5–8 range. Do warm-up sets separately.\n\nThe 12 workouts are a journal layout, not an author-imposed cycle length. Copy the cycle when you finish. Past results are not recalculated.");
  TEXT.put("Объём → техника → контроль. Прибавки 1,25 или 2,5 кг, только после подтверждения результата.","Volume → technique → top set. Increases of 1.25 or 2.5 kg follow confirmed results.");
  TEXT.put("Старт: тяжёлый вес — 80% от 1ПМ, объёмный — 65%, лёгкий — 70% тяжёлого. Округление вниз до 1,25 кг. Далее тяжёлый и лёгкий веса растут на одну прибавку по контрольному дню; объёмный блок — отдельно по минимуму повторов. 6+ повторов: +2,5 кг; 5: +1,25 кг; 4 и меньше: вес остаётся. Облегчённые подходы контрольного дня: −15 кг на турнике, −20 кг на брусьях, минимум 0 кг. Это адаптация без микроблинов и ежемесячного теста 1ПМ.","Initial loads: heavy 80% of 1RM, volume 65%, light 70% of heavy. Round down to 1.25 kg. Heavy and light loads then change by the same amount after the top-set day; volume progresses independently using the lowest reps. 6+ reps: +2.5 kg; 5: +1.25 kg; 4 or fewer: hold. Top-day backoffs: −15 kg for pull-ups, −20 kg for dips, floored at 0 kg. This adaptation omits microplates and monthly 1RM tests.");
  TEXT.put("3 недели · 9 занятий · нагрузка по результату","3 weeks · 9 sessions · performance-based loads");
  TEXT.put("Проценты учитывают половину массы тела: (1ПМ + масса / 2) × процент − масса / 2. Округление вниз до 1,25 кг. После тяжёлого и технического блоков оцени все подходы: с запасом — +2,5 кг; уверенно — +1,25 кг; на пределе — удержать. При недоборе повторов тяжёлый или технический блок снижается на 5%. Объём: минимум 6 повторов — +2,5 кг; 5 — +1,25 кг; иначе удержать. Это адаптация Trace: без 0,5 кг, максимум выбирается вручную, подготовительные веса меняются вместе с тяжёлым блоком. В цикле сохраняй указанные дни отдыха.","Percentages include half your body weight: (1RM + body weight / 2) × percentage − body weight / 2. Round down to 1.25 kg. Rate the whole heavy or technique block: reps in reserve +2.5 kg; solid +1.25 kg; at your limit hold. Missing the minimum reps reduces heavy or technique loads by 5%. Volume: at least 6 reps in every set +2.5 kg; 5 +1.25 kg; otherwise hold. Trace adaptation: no 0.5 kg increments, max attempts are manual, preparatory loads follow heavy-load changes. Keep the scheduled rest days.");
 }
 static String text(String source){
  String exact=TEXT.get(source);if(exact!=null)return exact;
  if(source.matches("Неделя \\d+ · День \\d+"))return source.replace("Неделя ","Week ").replace("День ","Day ");
  if(source.matches("День \\d+"))return source.replace("День ","Day ");
  if(source.matches("Неделя \\d+ · (Объём|Лёгкая техника|Контрольный день)")){String[] parts=source.split(" · ",2);return parts[0].replace("Неделя ","Week ")+" · "+text(parts[1]);}
  return source;
 }
 // Existing exercise classifiers keep the same meaning after a label changes.
 static String original(String label){for(Map.Entry<String,String> e:TEXT.entrySet())if(e.getValue().equals(label))return e.getKey();return label;}
}
