package com.podhod.app;

import android.app.*;
import android.view.*;
import android.widget.*;
import android.text.InputFilter;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.*;
import java.util.*;

/** Private, server-authorized text conversation scoped to an accepted connection. */
final class FriendChat {
 final MainActivity a;final String uid;final Dialog dialog;final LinearLayout root,messages;final ScrollView scroll;final EditText input;final TextView status,send,older;final CollectionReference collection;
 ListenerRegistration listener;FirebaseAuth.AuthStateListener auth;final Map<String,DocumentSnapshot> loaded=new HashMap<>();DocumentSnapshot oldest;boolean more,sending,first=true,loadingOlder,prepending;
 static String s(String en,String ru){return FriendsPanel.s(en,ru);}
 static FriendChat open(MainActivity a,String connection,String name){return new FriendChat(a,connection,name);}
 FriendChat(MainActivity a,String connection,String name){
  this.a=a;uid=FriendsPanel.uid(a);collection=FirebaseFirestore.getInstance().collection("connections/"+connection+"/messages");dialog=new Dialog(a,android.R.style.Theme_Material_NoActionBar);root=a.column();root.setBackgroundColor(a.BG);dialog.setContentView(root);
  LinearLayout bar=new LinearLayout(a);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(a.dp(12),0,a.dp(20),0);root.addView(bar,new LinearLayout.LayoutParams(-1,a.dp(64)));ImageView back=new ImageView(a);back.setImageDrawable(new LineIcon("back",a.TEXT));back.setPadding(a.dp(13),a.dp(13),a.dp(13),a.dp(13));back.setContentDescription(s("Back","Назад"));bar.addView(back,new LinearLayout.LayoutParams(a.dp(48),a.dp(48)));a.clickable(back,dialog::dismiss);LinearLayout heading=a.column();heading.setPadding(a.dp(8),0,0,0);bar.addView(heading,new LinearLayout.LayoutParams(0,-2,1));TextView title=a.title(name,20);title.setSingleLine(true);title.setEllipsize(android.text.TextUtils.TruncateAt.END);heading.addView(title);status=a.text(s("Connecting…","Подключаемся…"),12,a.MUTED);heading.addView(status);
  scroll=new ScrollView(a);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout history=a.column();history.setPadding(a.dp(16),0,a.dp(16),a.dp(12));scroll.addView(history);older=a.button(history,s("Earlier messages","Предыдущие сообщения"),false,this::loadOlder);older.setVisibility(View.GONE);messages=a.column();history.addView(messages);
  LinearLayout composer=new LinearLayout(a);composer.setGravity(Gravity.BOTTOM);composer.setPadding(a.dp(16),a.dp(8),a.dp(16),a.dp(12));root.addView(composer);input=new EditText(a);input.setTextColor(a.TEXT);input.setHintTextColor(a.MUTED);input.setHint(s("Message…","Сообщение…"));input.setTextSize(16);input.setBackground(a.shape(a.CARD,20));input.setPadding(a.dp(16),a.dp(12),a.dp(16),a.dp(12));input.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);input.setMaxLines(4);input.setFilters(new InputFilter[]{new InputFilter.LengthFilter(2000)});composer.addView(input,new LinearLayout.LayoutParams(0,-2,1));send=a.button(composer,"↑",true,this::send);send.setContentDescription(s("Send message","Отправить сообщение"));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(a.dp(48),a.dp(48));sp.setMargins(a.dp(8),0,0,0);send.setLayoutParams(sp);
  Window w=dialog.getWindow();w.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);if(android.os.Build.VERSION.SDK_INT>=30)w.setDecorFitsSystemWindows(false);else w.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION);
  root.setOnApplyWindowInsetsListener((v,i)->{if(android.os.Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=i.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout()|WindowInsets.Type.ime());v.setPadding(bars.left,bars.top,bars.right,bars.bottom);}else v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});
  auth=f->{if(!uid.equals(FriendsPanel.uid(a)))dialog.dismiss();};dialog.setOnDismissListener(d->{if(listener!=null)listener.remove();FirebaseAuth.getInstance().removeAuthStateListener(auth);});dialog.show();w.setLayout(-1,-1);root.requestApplyInsets();FirebaseAuth.getInstance().addAuthStateListener(auth);listen();
 }
 boolean active(){return dialog.isShowing()&&!a.isDestroyed()&&uid.equals(FriendsPanel.uid(a));}
 void listen(){if(listener!=null)listener.remove();listener=collection.orderBy("sentAt",Query.Direction.DESCENDING).limit(40).addSnapshotListener(MetadataChanges.INCLUDE,(snapshot,error)->{if(!active())return;if(error!=null){loaded.clear();messages.removeAllViews();status.setText(s("Chat unavailable · reopen to retry","Чат недоступен · открой снова"));send.setEnabled(false);return;}if(snapshot==null||snapshot.getMetadata().isFromCache())return;send.setEnabled(!sending);status.setText(s("Private conversation","Личная переписка"));for(DocumentChange change:snapshot.getDocumentChanges())if(change.getType()==DocumentChange.Type.REMOVED){DocumentSnapshot prior=loaded.get(change.getDocument().getId());if(prior!=null&&prior.getMetadata().hasPendingWrites())loaded.remove(prior.getId());}accept(snapshot);});}
 void accept(QuerySnapshot snapshot){for(DocumentSnapshot doc:snapshot.getDocuments())loaded.put(doc.getId(),doc);if(oldest==null){more=snapshot.size()==40;if(!snapshot.isEmpty())oldest=snapshot.getDocuments().get(snapshot.size()-1);}draw();}
 void loadOlder(){if(oldest==null||loadingOlder)return;loadingOlder=true;older.setEnabled(false);collection.orderBy("sentAt",Query.Direction.DESCENDING).startAfter(oldest).limit(40).get(Source.SERVER).addOnCompleteListener(task->{if(!active())return;loadingOlder=false;if(task.isSuccessful()){QuerySnapshot page=task.getResult();more=page.size()==40;if(!page.isEmpty())oldest=page.getDocuments().get(page.size()-1);prepending=true;accept(page);prepending=false;}else{older.setEnabled(true);status.setText(s("Could not load earlier messages · retry","Не удалось загрузить историю · повтори"));}});}
 void draw(){boolean prepend=prepending;boolean bottom=!prepend&&(first||!scroll.canScrollVertically(1));int scrollY=scroll.getScrollY(),height=messages.getHeight();messages.removeAllViews();List<DocumentSnapshot> docs=new ArrayList<>(loaded.values());docs.sort((x,y)->{Date dx=x.getDate("sentAt"),dy=y.getDate("sentAt");int c=Long.compare(dx==null?Long.MAX_VALUE:dx.getTime(),dy==null?Long.MAX_VALUE:dy.getTime());return c!=0?c:x.getId().compareTo(y.getId());});for(DocumentSnapshot d:docs){boolean mine=uid.equals(d.getString("sender"));LinearLayout line=new LinearLayout(a);line.setGravity(mine?Gravity.RIGHT:Gravity.LEFT);LinearLayout bubble=a.column();bubble.setPadding(a.dp(14),a.dp(10),a.dp(14),a.dp(8));bubble.setBackground(a.shape(mine?0xFF21483F:a.CARD,18));TextView text=a.text(d.getString("text"),16,a.TEXT);text.setMaxWidth(a.dp(260));text.setTextIsSelectable(true);bubble.addView(text);Date date=d.getDate("sentAt");TextView time=a.text(date==null?s("Sending…","Отправляем…"):new java.text.SimpleDateFormat("d MMM · HH:mm",Lang.locale()).format(date),11,a.MUTED);bubble.addView(time);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-2,-2);bp.setMargins(0,a.dp(4),0,a.dp(4));line.addView(bubble,bp);messages.addView(line);}if(docs.isEmpty())messages.addView(a.text(s("Start a conversation with your friend.","Начни разговор с другом."),15,a.MUTED));older.setVisibility(more?View.VISIBLE:View.GONE);older.setEnabled(!loadingOlder);first=false;scroll.post(()->{if(bottom)scroll.fullScroll(View.FOCUS_DOWN);else scroll.scrollTo(0,scrollY+(prepend?Math.max(0,messages.getHeight()-height):0));});}
 void send(){String text=input.getText().toString().trim();if(text.isEmpty()||sending||!active())return;sending=true;send.setEnabled(false);input.setEnabled(false);status.setText(s("Sending…","Отправляем…"));Map<String,Object> data=new HashMap<>();data.put("sender",uid);data.put("text",text);data.put("sentAt",FieldValue.serverTimestamp());collection.document().set(data).addOnCompleteListener(task->{if(!active())return;sending=false;input.setEnabled(true);send.setEnabled(true);if(task.isSuccessful()){input.setText("");status.setText(s("Sent","Отправлено"));scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));}else{status.setText(s("Not sent · try again","Не отправлено · повтори"));a.error(new IllegalStateException(FriendsPanel.errorMessage(task.getException())));}});}
}
