package com.podhod.app;
import android.app.*;
import android.widget.*;
import android.text.InputType;

final class GmailFriends {
 static String s(String en,String ru){return FriendsPanel.s(en,ru);}
 static AlertDialog add(MainActivity a){LinearLayout box=a.form();LinearLayout tabs=new LinearLayout(a);box.addView(tabs);EditText input=a.input(box,s("Gmail or friend code","Gmail или код друга"),"",false);TextView hint=a.text("",14,a.MUTED);box.addView(hint);boolean[] gmail={true};TextView[] buttons=new TextView[2];Runnable select=()->{input.setText("");input.setHint(gmail[0]?"name@gmail.com":"ABCD-EFGH-IJKL");input.setInputType(gmail[0]?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS:InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_CHARACTERS);hint.setText(gmail[0]?s("Your friend must enable Find me by Gmail in My profile. The request arrives in Trace, not by email.","Друг должен включить поиск по Gmail в своём профиле. Запрос придёт в Trace, а не письмом."):s("Ask your friend for their code in My profile.","Код друга можно найти в его профиле."));for(int i=0;i<2;i++){boolean selected=(i==0)==gmail[0];buttons[i].setBackground(a.shape(selected?a.GREEN:a.LINE,14));buttons[i].setTextColor(selected?a.BG:a.TEXT);}};
  buttons[0]=FriendsButton(a,tabs,"Gmail",()->{gmail[0]=true;select.run();});buttons[1]=FriendsButton(a,tabs,s("Friend code","Код друга"),()->{gmail[0]=false;select.run();});select.run();
  AlertDialog dialog=a.panel(s("Add friend","Добавить друга"),box,Lang.t("Закрыть"),()->{},false);TextView[] send={null};send[0]=a.button(box,s("Send request","Отправить запрос"),true,()->{String value=input.getText().toString().trim();if(gmail[0]){try{GmailAddress.normalize(value);}catch(IllegalArgumentException e){input.setError(s("Enter a valid Gmail address","Введи корректный адрес Gmail"));return;}}else if(!SocialPayload.code(value).matches("[A-F0-9]{12}")){input.setError(s("Enter a 12-character friend code","Введи код друга из 12 символов"));return;}boolean byGmail=gmail[0];send[0].setEnabled(false);send[0].setText(s("Sending…","Отправляем…"));FriendsPanel.run(a,b->{if(byGmail)b.requestGmail(value);else b.request(value);return true;},ok->{dialog.dismiss();Toast.makeText(a,s("Friend request sent in Trace","Запрос в друзья отправлен в Trace"),Toast.LENGTH_LONG).show();FriendsPanel.refresh(a);},()->{send[0].setEnabled(true);send[0].setText(s("Send request","Отправить запрос"));});});return dialog;
 }
 static TextView FriendsButton(MainActivity a,LinearLayout row,String label,Runnable action){FriendsPanel.compact(a,row,label,false,action);return (TextView)row.getChildAt(row.getChildCount()-1);}
 static void settings(MainActivity a,LinearLayout host){LinearLayout card=a.card(host);card.addView(a.title(s("Find me by Gmail","Находить меня по Gmail"),19));a.space(card,8);card.addView(a.text(s("People who know your exact sign-in Gmail can send a friend request. Off by default. Your Gmail is not shown on your profile.","Зная точный Gmail твоего аккаунта, можно отправить тебе запрос. По умолчанию выключено. Адрес не отображается в профиле."),14,a.MUTED));Switch toggle=new Switch(a);toggle.setTextColor(a.TEXT);toggle.setText(s("Checking…","Проверяем…"));toggle.setMinHeight(a.dp(48));toggle.setEnabled(false);card.addView(toggle);String account=FriendsPanel.uid(a);
  try{new FriendsStore().gmail();}catch(Exception e){toggle.setText(s("Available for verified Gmail accounts","Доступно для подтверждённого Gmail"));return;}
  FriendsPanel.run(a,FriendsStore::gmailVisible,enabled->{if(!card.isAttachedToWindow()||!account.equals(FriendsPanel.uid(a)))return;toggle.setChecked(enabled);toggle.setEnabled(true);toggle.setText(s("Allow Gmail lookup","Разрешить поиск по Gmail"));toggle.setOnCheckedChangeListener((button,checked)->{if(!button.isEnabled())return;toggle.setEnabled(false);FriendsPanel.run(a,b->{b.gmailVisible(checked);return true;},ok->{if(card.isAttachedToWindow())toggle.setEnabled(true);},()->{toggle.setChecked(!checked);toggle.setEnabled(true);});});},()->toggle.setText(s("Unavailable · reopen profile to retry","Недоступно · открой профиль снова")));
 }
}
