package com.podhod.app;
import android.content.*;
import android.content.res.Configuration;
import java.util.*;
/** Display-only localization. Stored workout names and identifiers never change. */
public final class Lang {
    private static Context localized;
    private static String language="ru";
    private static final Map<String,Integer> ids=new HashMap<>();
    static {
        ids.put("Спереди",R.string.muscle_front);
        ids.put("Сзади",R.string.muscle_back);
        ids.put("Грудь",R.string.walk_muscle_0);
        ids.put("Спина",R.string.walk_muscle_1);
        ids.put("Плечи",R.string.walk_muscle_2);
        ids.put("Бицепс",R.string.walk_muscle_3);
        ids.put("Трицепс",R.string.walk_muscle_4);
        ids.put("Пресс",R.string.walk_muscle_5);
        ids.put("Ягодицы",R.string.walk_muscle_6);
        ids.put("Передняя поверхность бедра",R.string.walk_muscle_7);
        ids.put("Задняя поверхность бедра",R.string.walk_muscle_8);
        ids.put("Икры",R.string.walk_muscle_9);
        ids.put("Поясница",R.string.walk_muscle_10);
        ids.put("Предплечья",R.string.walk_muscle_11);
        ids.put("Мышцы упражнения",R.string.walk_muscle_12);
        ids.put("Какие мышцы работают?",R.string.walk_muscle_13);
        ids.put("Определять автоматически",R.string.walk_muscle_14);
        ids.put("КАРТА МЫШЦ",R.string.walk_muscle_15);
        ids.put("Отмечай подходы — задействованные мышцы подсветятся.",R.string.walk_muscle_16);
        ids.put("Подходы с участием мышцы, включая вспомогательную работу. Это оценка по упражнениям, а не измерение усталости.",R.string.walk_muscle_17);
        ids.put("Есть нераспознанные упражнения. Укажи мышцы в редакторе плана.",R.string.walk_muscle_18);
        ids.put("Мышцы спереди и сзади. Подробности перечислены ниже.",R.string.walk_muscle_19);
        ids.put("В этой тренировке",R.string.walk_muscle_20);
        ids.put("За последние 7 дней",R.string.walk_muscle_21);
        ids.put("НА СВЕЖЕМ ВОЗДУХЕ",R.string.walk_muscle_22);
        ids.put("Твой маршрут",R.string.walk_muscle_23);
        ids.put("КИЛОМЕТРЫ",R.string.walk_muscle_24);
        ids.put("ВРЕМЯ",R.string.walk_muscle_25);
        ids.put("МИН / КМ",R.string.walk_muscle_26);
        ids.put("Средний темп рассчитан по полному времени, включая остановки. GPS записывается только во время прогулки. Карта OpenStreetMap требует интернет; маршруты сохраняются на телефоне. Без сети запись продолжается, но фон карты может быть недоступен. Лимит — 24 часа.",R.string.walk_muscle_27);
        ids.put(" прогулок · ",R.string.walk_muscle_28);
        ids.put(" мин/км",R.string.walk_muscle_29);
        ids.put("Открыть маршрут",R.string.walk_muscle_30);
        ids.put("Миниатюра маршрута",R.string.walk_muscle_31);

        ids.put("Пояс с блинами · дополнительный вес",R.string.belt_0);
        ids.put("БЛИНЫ НА ПОЯС",R.string.belt_1);
        ids.put("Только собственный вес",R.string.belt_2);
        ids.put("Дополнительный вес: +",R.string.belt_3);

        ids.put("Упражнение со штангой · гриф 20 кг",R.string.barbell_0);
        ids.put("Без блинов",R.string.barbell_1);
        ids.put("КАК СОБРАТЬ ШТАНГУ",R.string.barbell_2);
        ids.put("Гриф весит 20 кг. Укажи общий вес не меньше 20 кг.",R.string.barbell_3);
        ids.put("С каждой стороны: ",R.string.barbell_4);
        ids.put("Гриф 20 кг · всего ",R.string.barbell_5);
        ids.put("Этот вес нельзя собрать точно. На рисунке ",R.string.barbell_6);
        ids.put(" кг. Вес подхода не изменён.",R.string.barbell_7);

        ids.put("Не найден браузер для скачивания",R.string.updates_0);
        ids.put("ОБНОВЛЕНИЯ TRACE",R.string.updates_1);
        ids.put("Установлена версия ",R.string.updates_2);
        ids.put("Доступна версия ",R.string.updates_3);
        ids.put("У тебя актуальная версия",R.string.updates_4);
        ids.put("Проверено: ",R.string.updates_5);
        ids.put("Что нового",R.string.updates_6);
        ids.put("Скачать APK",R.string.updates_7);
        ids.put("Скачивание откроется в браузере. Открой APK из загрузок и подтверди обновление Android. Данные сохранятся.",R.string.updates_8);
        ids.put("Проверь, появилась ли новая версия на GitHub.",R.string.updates_9);
        ids.put("Не удалось проверить обновление. Проверь интернет и попробуй ещё раз.",R.string.updates_10);
        ids.put("Проверяем обновления…",R.string.updates_11);
        ids.put("Проверить обновления",R.string.updates_12);
        ids.put("Все версии на GitHub",R.string.updates_13);

        ids.put("Домашняя",R.string.category_home_training);
        ids.put("Все",R.string.catalog_filter_0);
        ids.put("В этой категории пока нет планов",R.string.catalog_filter_1);
        ids.put("Создай или импортируй план и выбери для него эту категорию.",R.string.catalog_filter_2);

        ids.put("Злат · Начальный",R.string.catalog_0);
        ids.put("Злат · Средний",R.string.catalog_1);
        ids.put("Злат · Продвинутый",R.string.catalog_2);
        ids.put("Шейко · Подготовка",R.string.catalog_3);
        ids.put("Шейко · Соревнования",R.string.catalog_4);
        ids.put("НАЧАЛЬНЫЙ · 3 ДНЯ В НЕДЕЛЮ",R.string.catalog_5);
        ids.put("СРЕДНИЙ · 3 ДНЯ В НЕДЕЛЮ",R.string.catalog_6);
        ids.put("ПРОДВИНУТЫЙ · ЦИКЛ 3 НЕДЕЛИ",R.string.catalog_7);
        ids.put("КМС / МС · ПОДГОТОВКА",R.string.catalog_8);
        ids.put("12 НЕДЕЛЬ · К СОРЕВНОВАНИЯМ",R.string.catalog_9);
        ids.put("Трёхнедельный цикл: объём, восстановление, реализация. 9 занятий. Адаптация Trace без микроблинов; оценка тяжести перед сохранением. Максимальные попытки выбираются вручную.",R.string.catalog_10);
        ids.put("Проверь максимумы и массу тела",R.string.catalog_11);
        ids.put("Пауза на 3 счёта в верхней и нижней точках каждого повторения.",R.string.catalog_12);
        ids.put("Выбери вес попытки вручную. Запиши успешный результат; не отмечай неудачную попытку выполненной.",R.string.catalog_13);
        ids.put("Контрольная техника, без отказа. На брусьях — пауза внизу; на турнике — полный вис перед подъёмом.",R.string.catalog_14);
        ids.put("3 недели · 9 занятий · нагрузка по результату",R.string.catalog_15);
        ids.put("Проценты учитывают половину массы тела: (1ПМ + масса / 2) × процент − масса / 2. Округление вниз до 1,25 кг. После тяжёлого и технического блоков оцени все подходы: с запасом — +2,5 кг; уверенно — +1,25 кг; на пределе — удержать. При недоборе повторов тяжёлый или технический блок снижается на 5%. Объём: минимум 6 повторов — +2,5 кг; 5 — +1,25 кг; иначе удержать. Это адаптация Trace: без 0,5 кг, максимум выбирается вручную, подготовительные веса меняются вместе с тяжёлым блоком. В цикле сохраняй указанные дни отдыха.",R.string.catalog_16);
        ids.put("Укажи известные максимумы дополнительного веса и массу тела. Будущие занятия пересчитаются; текущие подходы сохранятся.",R.string.catalog_17);
        ids.put("Масса тела, кг",R.string.catalog_18);
        ids.put("Проверь реальные повторы и оцени весь блок. Если хотя бы один подход был на пределе, оставь вес.",R.string.catalog_19);
        ids.put("Сила",R.string.catalog_20);
        ids.put("Техника",R.string.catalog_21);
        ids.put("На пределе · оставить вес",R.string.catalog_22);
        ids.put("Уверенно · +1,25 кг",R.string.catalog_23);
        ids.put("С запасом · +2,5 кг",R.string.catalog_24);
        ids.put("Неделя 1 · Пн · Сила и объём",R.string.catalog_25);
        ids.put("Неделя 1 · Вт · Двойные паузы",R.string.catalog_26);
        ids.put("Неделя 1 · Чт · Восстановление",R.string.catalog_27);
        ids.put("Неделя 1 · Пт · Сила и объём",R.string.catalog_28);
        ids.put("Неделя 1 · Вс · Двойные паузы",R.string.catalog_29);
        ids.put("Неделя 2 · Ср · Разгрузка",R.string.catalog_30);
        ids.put("Неделя 2 · Сб · Подготовка",R.string.catalog_31);
        ids.put("Неделя 3 · Вт · Проверка максимума",R.string.catalog_32);
        ids.put("Неделя 3 · Пт · Следующий цикл",R.string.catalog_33);

        ids.put("6+ повторов: +2,5 кг · 5: +1,25 кг · 4 и меньше: без прибавки",R.string.intermediate_finish);
        ids.put("Три разных дня: объём, лёгкая техника, контрольный подход. Адаптация Trace: без прибавок 0,5 кг и без автоматических тестов 1ПМ. 12 занятий — четыре обычные недели.",R.string.intermediate_0);
        ids.put("Злат · intermediate",R.string.intermediate_1);
        ids.put("Объём",R.string.intermediate_2);
        ids.put("Лёгкая техника",R.string.intermediate_3);
        ids.put("Контрольный день",R.string.intermediate_4);
        ids.put("Укажи максимумы от 1,25 до 1900 кг",R.string.intermediate_5);
        ids.put("Пауза в полном висе, затем быстрый подъём. Без раскачки.",R.string.intermediate_6);
        ids.put("Пауза на 3 счёта внизу каждого повторения.",R.string.intermediate_7);
        ids.put("Объёмный блок · 4–6 повторений. Прогрессия по худшему подходу.",R.string.intermediate_8);
        ids.put("Контрольный подход · 4–6 повторений. Результат задаёт вес следующей недели.",R.string.intermediate_9);
        ids.put("Тяжёлый блок · 3 подхода по 3 повторения.",R.string.intermediate_10);
        ids.put("Объём → техника → контроль. Прибавки 1,25 или 2,5 кг, только после подтверждения результата.",R.string.intermediate_11);
        ids.put("Настроить начальные веса",R.string.intermediate_12);
        ids.put("Старт: тяжёлый вес — 80% от 1ПМ, объёмный — 65%, лёгкий — 70% тяжёлого. Округление вниз до 1,25 кг. Далее тяжёлый и лёгкий веса растут на одну прибавку по контрольному дню; объёмный блок — отдельно по минимуму повторов. 6+ повторов: +2,5 кг; 5: +1,25 кг; 4 и меньше: вес остаётся. Облегчённые подходы контрольного дня: −15 кг на турнике, −20 кг на брусьях, минимум 0 кг. Это адаптация без микроблинов и ежемесячного теста 1ПМ.",R.string.intermediate_13);
        ids.put("Источник программы",R.string.intermediate_14);
        ids.put("Введи известный максимум дополнительного веса на одно повторение. Массу тела не добавляй. Настройка пересчитает будущие занятия.",R.string.intermediate_15);
        ids.put("Турник · 1ПМ, кг",R.string.intermediate_16);
        ids.put("Брусья · 1ПМ, кг",R.string.intermediate_17);
        ids.put("Начальные веса",R.string.intermediate_18);
        ids.put("Проверь фактические повторы в подходах. Для объёмного блока учитывается худший подход, для контрольного — первый тяжёлый. При необходимости вернись и исправь повторы.",R.string.intermediate_19);

        ids.put("О редакторе",R.string.editor_extra_0);
        ids.put("Действия упражнения",R.string.editor_extra_1);

        ids.put("Заметка — до 2000 символов",R.string.editor_backup_0);
        ids.put("Заметка сохраняется для этого упражнения в плане.",R.string.editor_backup_1);
        ids.put("Заметка к упражнению",R.string.editor_backup_2);
        ids.put("Изменения применяются к будущим занятиям. Текущая тренировка и история сохраняются.",R.string.editor_backup_3);
        ids.put("Редактор плана",R.string.editor_backup_4);
        ids.put("Копировать день",R.string.editor_backup_5);
        ids.put(" · копия",R.string.editor_backup_6);
        ids.put("← Все дни",R.string.editor_backup_7);
        ids.put("Переименовать день",R.string.editor_backup_8);
        ids.put("Удерживай ⋮⋮ и перетащи упражнение. Кнопки − / + меняют число подходов.",R.string.editor_backup_9);
        ids.put("Переместить упражнение",R.string.editor_backup_10);
        ids.put("Уменьшить подходы",R.string.editor_backup_11);
        ids.put("Добавить подход",R.string.editor_backup_12);
        ids.put("Переместить вверх",R.string.editor_backup_13);
        ids.put("Переместить вниз",R.string.editor_backup_14);
        ids.put("Копировать упражнение",R.string.editor_backup_15);
        ids.put("Загрузка копий…",R.string.editor_backup_16);
        ids.put("История резервных копий",R.string.editor_backup_17);
        ids.put("Копии на этом устройстве. Для файла из другой папки используй «Восстановить из файла».",R.string.editor_backup_18);
        ids.put("Сохранённых копий пока нет",R.string.editor_backup_19);
        ids.put("Дни, упражнения, подходы и заметки",R.string.editor_backup_20);
        ids.put("Дата, размер и восстановление",R.string.editor_backup_21);

        ids.put("Закончил подход",R.string.panel_set_done);
        ids.put("Выключен",R.string.auto_folder_0);
        ids.put("Включить",R.string.auto_folder_1);
        ids.put("Загрузки → Trace → Backup",R.string.auto_folder_2);
        ids.put("Папка Загрузки → Trace → Backup создастся автоматически при первой копии. Затем копия сохраняется раз в 14 дней. Старые файлы остаются.",R.string.auto_folder_3);
        ids.put("На Android 8–9 папку нужно выбрать один раз. Затем копии сохраняются автоматически.",R.string.auto_folder_4);

        ids.put("Автобэкап каждые 2 недели",R.string.auto_backup_0);
        ids.put("Выбери папку — дальше всё автоматически",R.string.auto_backup_1);
        ids.put("Не удалось сохранить копию. Проверь доступ к папке и свободное место.",R.string.auto_backup_2);
        ids.put("Первая копия ожидает сохранения",R.string.auto_backup_3);
        ids.put("Автокопия: ",R.string.auto_backup_4);
        ids.put("Следующая — после ",R.string.auto_backup_5);
        ids.put("Первая копия сохранится после выбора папки. Затем — раз в 14 дней, когда Android разрешит фоновую задачу. Старые файлы не удаляются.",R.string.auto_backup_6);
        ids.put("Выбрать папку",R.string.auto_backup_7);
        ids.put("Отключить",R.string.auto_backup_8);

        ids.put("Удалить прогулку",R.string.walk_delete_0);
        ids.put("Удалить прогулку?",R.string.walk_delete_1);
        ids.put("Маршрут и запись этой прогулки будут удалены. Шаги за день и другие прогулки сохранятся.",R.string.walk_delete_2);

        ids.put("Заверши прогулку — здесь появятся её маршрут, время и расстояние.",R.string.walk_history_empty);
        ids.put("Нет точек GPS",R.string.map_style_0);
        ids.put("Ожидаем сигнал GPS",R.string.map_style_1);
        ids.put("Твой маршрут начинается здесь",R.string.map_style_2);
        ids.put("Карта появится после первой точки",R.string.map_style_3);
        ids.put("Начни прогулку, чтобы увидеть карту",R.string.map_style_4);
        ids.put("Расстояние GPS",R.string.map_style_5);
        ids.put("Время прогулки",R.string.map_style_6);
        ids.put("Уменьшить карту",R.string.map_style_7);
        ids.put("Увеличить карту",R.string.map_style_8);

        ids.put(" мин",R.string.walk_minutes);
        ids.put("Прогулка",R.string.walk_0);
        ids.put("Запись прогулки",R.string.walk_1);
        ids.put("Ищем GPS…",R.string.walk_2);
        ids.put("Завершить прогулку",R.string.walk_3);
        ids.put("Карта прогулки",R.string.walk_4);
        ids.put("Начать прогулку",R.string.walk_5);
        ids.put("О карте и записи",R.string.walk_6);
        ids.put("GPS записывается только во время прогулки. Карта OpenStreetMap загружается через интернет; сервер карты получает запросы участков карты. Маршруты хранятся на телефоне и входят в полную копию. Без сети линия маршрута сохраняется, но фон карты может быть недоступен. В помещении GPS может не найти точку. Ограничение записи — 24 часа.",R.string.walk_7);
        ids.put("Весь маршрут",R.string.walk_8);
        ids.put("Нет свежего сигнала GPS",R.string.walk_9);
        ids.put("Запись прервана. Начни новую прогулку.",R.string.walk_10);
        ids.put("Последняя прогулка",R.string.walk_11);
        ids.put("Нажми начать и бери телефон с собой",R.string.walk_12);
        ids.put("История прогулок",R.string.walk_13);
        ids.put("Запись была прервана",R.string.walk_14);
        ids.put("Для маршрута разреши точную геолокацию. Шагомер работает и без неё.",R.string.walk_15);
        ids.put("Включи геолокацию телефона, затем начни прогулку.",R.string.walk_16);

        ids.put("Силовой план",R.string.category_0);
        ids.put("Стритлифтинг",R.string.category_1);
        ids.put("Пауэрлифтинг",R.string.category_2);
        ids.put("Бодибилдинг",R.string.category_3);
        ids.put("Калистеника",R.string.category_4);
        ids.put("Кардио",R.string.category_5);
        ids.put("Своя категория",R.string.category_6);
        ids.put("Название категории — от 1 до 40 символов",R.string.category_7);
        ids.put("Изменить категорию",R.string.category_8);
        ids.put("Категория плана",R.string.category_9);
        ids.put("Название категории",R.string.category_10);

        ids.put("Шаги и настройки также будут заменены. ",R.string.backup_replace);
        ids.put("В дне должно остаться хотя бы одно упражнение",R.string.backup_0);
        ids.put("Повреждена полная резервная копия",R.string.backup_1);
        ids.put("Не удалось восстановить копию",R.string.backup_2);
        ids.put("Копия больше 50 МБ",R.string.backup_3);
        ids.put("Удалено: ",R.string.backup_4);
        ids.put("Вернуть",R.string.backup_5);
        ids.put("Удалить упражнение",R.string.backup_6);
        ids.put("Планы, обложки, история, шаги и настройки",R.string.backup_7);
        ids.put("Копия ещё не сохранялась",R.string.backup_8);
        ids.put("Последняя копия: ",R.string.backup_9);

        ids.put("Таблица или полученный план",R.string.import_file_hint);
        ids.put("Поделиться планом",R.string.share_0);
        ids.put("Открой этот файл с помощью Trace и добавь план из превью. Или сохрани файл: Планы → Из файла.",R.string.share_1);

        ids.put("Настроить обложку",R.string.crop_0);
        ids.put("Двигай фото пальцем. Разведи два пальца, чтобы увеличить.",R.string.crop_1);
        ids.put("Масштаб обложки",R.string.crop_2);
        ids.put("Сбросить положение",R.string.crop_3);

        ids.put("Удалить",R.string.plan_delete);
        ids.put("Удалить план",R.string.plan_0);
        ids.put("Удалить план?",R.string.plan_1);
        ids.put("План исчезнет из «Планов» и «Моих планов». Незавершённое занятие будет удалено. История завершённых тренировок останется.",R.string.plan_2);
        ids.put("Изменить обложку",R.string.plan_3);
        ids.put("Выбрать фото или скриншот",R.string.plan_4);
        ids.put("Вернуть стандартную обложку",R.string.plan_5);
        ids.put("Обложка плана",R.string.plan_6);
        ids.put("Сохраняем обложку…",R.string.plan_7);
        ids.put("Не удалось открыть изображение",R.string.plan_8);
        ids.put("Выбери изображение размером до 20 МБ",R.string.plan_9);

        ids.put("Твой ритм",R.string.walking_0);
        ids.put("ПОСЛЕДНИЕ 7 ДНЕЙ",R.string.walking_1);
        ids.put("За 7 дней: ",R.string.walking_2);
        ids.put(" шагов",R.string.walking_3);
        ids.put("Всего записано: ",R.string.walking_4);
        ids.put("Открыть шагомер  →",R.string.walking_5);
        ids.put("О данных ходьбы",R.string.walking_6);
        ids.put("График показывает записанные шаги за последние 7 дней. Нажми на день, чтобы увидеть итог. Прочерк означает, что записей нет. Километры приблизительные и рассчитаны по текущей длине шага. Ходьба не добавляет тренировки в календарь.",R.string.walking_7);
        ids.put("Нет записей шагов",R.string.walking_8);
        ids.put(" км",R.string.distance_0);
        ids.put(" см",R.string.distance_1);
        ids.put("Примерное расстояние",R.string.distance_2);
        ids.put("Длина шага",R.string.distance_3);
        ids.put("Длина шага, см",R.string.distance_4);
        ids.put("Длина шага — от 20 до 200 см",R.string.distance_5);
        ids.put("Расстояние = шаги × длина шага. По умолчанию 70 см — настрой под себя. Для калибровки раздели известное расстояние в сантиметрах на число шагов.",R.string.distance_6);
        ids.put("Шаги",R.string.steps_00);
        ids.put("Шаги за сегодня",R.string.steps_01);
        ids.put("ДВИЖЕНИЕ КАЖДЫЙ ДЕНЬ",R.string.steps_02);
        ids.put("Цель на день",R.string.steps_03);
        ids.put("Изменить цель",R.string.steps_04);
        ids.put("Цель — от 100 до 100 000 шагов",R.string.steps_05);
        ids.put("Датчик шагов недоступен",R.string.steps_06);
        ids.put("Этот телефон не предоставляет встроенный счётчик шагов.",R.string.steps_07);
        ids.put("Считает твой телефон",R.string.steps_08);
        ids.put("Бери телефон с собой — шаги записываются и при закрытом экране.",R.string.steps_09);
        ids.put("Выключить подсчёт",R.string.steps_10);
        ids.put("Включить подсчёт",R.string.steps_11);
        ids.put("Как работает подсчёт",R.string.steps_12);
        ids.put("Подсчёт начинается после включения. Прошлые шаги за сегодня недоступны. После перезагрузки или принудительной остановки открой Trace снова. Система может прерывать фоновую работу; пропущенные шаги не всегда восстановятся. При смене дня показания относятся к дате события датчика. Шаги и настройки входят в полную резервную копию в настройках Trace.",R.string.steps_13);
        ids.put("Цель достигнута",R.string.steps_14);
        ids.put("До цели: ",R.string.steps_15);
        ids.put("ПОДСЧЁТ ВКЛЮЧЁН",R.string.steps_16);
        ids.put("ПОДСЧЁТ ВЫКЛЮЧЕН",R.string.steps_17);
        ids.put("шагов сегодня",R.string.steps_18);
        ids.put("Разреши физическую активность для подсчёта шагов в настройках Trace.",R.string.steps_19);
        ids.put("Открыть настройки",R.string.steps_20);
        ids.put("Нужно разрешение на физическую активность",R.string.steps_21);
        ids.put("Шейко · 12 недель к соревнованиям",R.string.cycle_00);
        ids.put("Цикл для разрядников из файла sheyko.xlsx: недели 1–8 — подготовка, 9–12 — соревновательный этап. 35 тренировок; затем соревнования №36 без заданных попыток. Веса — проценты от твоих максимумов, округление 0,5 кг. Подсобные веса выбираются вручную. В расхождениях между краткой записью и ячейками использованы подробные ячейки подходов.",R.string.cycle_01);
        ids.put("Неделя 12 · Соревнования №36. В таблице нет весов и попыток для этого дня.",R.string.cycle_02);
        ids.put("План 1 подготовительный",R.string.cycle_03);
        ids.put("План 2 подготовительный",R.string.cycle_04);
        ids.put("План 3 соревновательный",R.string.cycle_05);
        ids.put("Проходка: в исходном плане есть подходы до 105% от заданных максимумов.",R.string.cycle_06);
        ids.put("Присед со штангой на груди",R.string.cycle_07);
        ids.put("Тяга на подставке",R.string.cycle_08);
        ids.put("Попеременный жим гантелей сидя",R.string.cycle_09);
        ids.put("Разведение рук с гантелями лежа",R.string.cycle_10);
        ids.put("Наклоны со штангой стоя",R.string.cycle_11);
        ids.put("Жим сидя под углом",R.string.cycle_12);
        ids.put("Приседания со штангой в \"ножницах\"",R.string.cycle_13);
        ids.put("Подъем штанги на трицепсы",R.string.cycle_14);
        ids.put("Наклон со штангой сидя",R.string.cycle_15);
        ids.put("Отжимания от пола (руки на ширине плеч)",R.string.cycle_16);
        ids.put("Широчайшие на блоке",R.string.cycle_17);
        ids.put("Гиперэкстензии",R.string.cycle_18);
        ids.put("Отжимания от пола (руки шире плеч)",R.string.cycle_19);
        ids.put("Приседания в глубину",R.string.cycle_20);
        ids.put("Широчайшие мышцы",R.string.cycle_21);
        ids.put("Жим ногами",R.string.cycle_22);
        ids.put("Разгибание бедра в тренажере",R.string.cycle_23);
        ids.put("Настройки",R.string.tr_000);
        ids.put("Планы",R.string.tr_001);
        ids.put("Мои планы",R.string.tr_002);
        ids.put("Тренировка",R.string.tr_003);
        ids.put("Прогресс",R.string.tr_004);
        ids.put("Мои тренировки",R.string.tr_005);
        ids.put("Библиотека программ",R.string.tr_006);
        ids.put(" · быстрый выбор",R.string.tr_007);
        ids.put("Дальше: ",R.string.tr_008);
        ids.put(" кг",R.string.tr_009);
        ids.put("Введи фактические повторы выше",R.string.tr_010);
        ids.put("Твои максимумы",R.string.tr_011);
        ids.put("кг",R.string.tr_012);
        ids.put("Один раз на всю программу",R.string.tr_013);
        ids.put("Присед",R.string.tr_014);
        ids.put("Жим",R.string.tr_015);
        ids.put("Тяга",R.string.tr_016);
        ids.put("Максимум: ",R.string.tr_017);
        ids.put("Изменить максимумы",R.string.tr_018);
        ids.put("Как считаются веса",R.string.tr_019);
        ids.put("Введи максимумы один раз. Проценты плана пересчитают рабочие веса всех будущих дней; выполненные подходы останутся в истории.",R.string.tr_020);
        ids.put("Рабочие веса",R.string.tr_021);
        ids.put("Приложение повышает их после занятия",R.string.tr_022);
        ids.put("Турник",R.string.tr_023);
        ids.put("Брусья",R.string.tr_024);
        ids.put("3 дня / нед",R.string.tr_025);
        ids.put(" подхода",R.string.tr_026);
        ids.put("5–8 повторов",R.string.tr_027);
        ids.put("Настроить рабочие веса",R.string.tr_028);
        ids.put("Прибавка после занятия",R.string.tr_029);
        ids.put("Правила и источник",R.string.tr_030);
        ids.put("Оригинальное видео Злата",R.string.tr_031);
        ids.put("Русский перевод · сообщение №68",R.string.tr_032);
        ids.put("Как работает программа",R.string.tr_033);
        ids.put("Понятно",R.string.tr_034);
        ids.put("Дополнительный вес, без массы тела. Для будущих занятий.",R.string.tr_035);
        ids.put("Подтягивания, кг",R.string.tr_036);
        ids.put("Брусья, кг",R.string.tr_037);
        ids.put("Подходов на упражнение: 3 или 4",R.string.tr_038);
        ids.put("Настройка программы Злата",R.string.tr_039);
        ids.put("Сохранить",R.string.tr_040);
        ids.put("Сколько повторов вышло в последних подходах? Следующий вес посчитаем сами.",R.string.tr_041);
        ids.put("В программе должны быть подтягивания и брусья",R.string.tr_042);
        ids.put("Турник · последний подход",R.string.tr_043);
        ids.put("Брусья · последний подход",R.string.tr_044);
        ids.put("Результат занятия",R.string.tr_045);
        ids.put("Сохранить и рассчитать веса",R.string.tr_046);
        ids.put("Подходы изменились. Открой сохранение заново.",R.string.tr_047);
        ids.put("Сегодня",R.string.tr_048);
        ids.put("В ПРОЦЕССЕ",R.string.tr_049);
        ids.put("СЛЕДУЮЩАЯ ТРЕНИРОВКА",R.string.tr_050);
        ids.put(" из ",R.string.tr_051);
        ids.put(" подходов",R.string.tr_052);
        ids.put("Продолжить тренировку  →",R.string.tr_053);
        ids.put(" блоков",R.string.tr_054);
        ids.put("Начать тренировку  →",R.string.tr_055);
        ids.put("Все дни завершены",R.string.tr_056);
        ids.put("Начать новый цикл",R.string.tr_057);
        ids.put("Открыть программу",R.string.tr_058);
        ids.put("ДАЛЬШЕ ПО ПЛАНУ",R.string.tr_059);
        ids.put("Моя программа и веса",R.string.tr_060);
        ids.put("Максимумы и расписание — во вкладке «Мои»",R.string.tr_061);
        ids.put("Твой первый план",R.string.tr_062);
        ids.put("Выбери программу или добавь свою.",R.string.tr_063);
        ids.put("Открыть библиотеку",R.string.tr_064);
        ids.put("Твой прогресс",R.string.tr_065);
        ids.put("тренировок",R.string.tr_066);
        ids.put("подходов",R.string.tr_067);
        ids.put(" подходов\n",R.string.tr_068);
        ids.put("ЛИЧНЫЙ ПЛАН",R.string.tr_069);
        ids.put("Мои программы",R.string.tr_070);
        ids.put("Твои дни и рабочие веса",R.string.tr_071);
        ids.put("История тренировок",R.string.tr_072);
        ids.put(" завершённых занятий",R.string.tr_073);
        ids.put("ПОСЛЕДНЯЯ ПРОГРАММА",R.string.tr_074);
        ids.put("МОЯ ПРОГРАММА",R.string.tr_075);
        ids.put("Пройдено ",R.string.tr_076);
        ids.put(" дней",R.string.tr_077);
        ids.put("СЛЕДУЮЩЕЕ ЗАНЯТИЕ",R.string.tr_078);
        ids.put("ТЕКУЩЕЕ ЗАНЯТИЕ",R.string.tr_079);
        ids.put(" подходов уже выполнено",R.string.tr_080);
        ids.put("Вся программа",R.string.tr_081);
        ids.put("Расписание и упражнения",R.string.tr_082);
        ids.put("Убрать из моих",R.string.tr_083);
        ids.put("Пока нет программ",R.string.tr_084);
        ids.put("Выбери план из каталога или создай свой.",R.string.tr_085);
        ids.put("Добавить программу",R.string.tr_086);
        ids.put("Перейти к каталогу и импорту",R.string.tr_087);
        ids.put("КАТАЛОГ ПРОГРАММ",R.string.tr_088);
        ids.put("Найди свой план",R.string.tr_089);
        ids.put("Готовые программы и твои собственные идеи.",R.string.tr_090);
        ids.put("Из файла",R.string.tr_091);
        ids.put("Свой план",R.string.tr_092);
        ids.put("Собери по упражнениям",R.string.tr_093);
        ids.put("Скачать шаблон таблицы",R.string.tr_094);
        ids.put("ВСЕ ПРОГРАММЫ · ",R.string.tr_095);
        ids.put("СТРИТЛИФТИНГ",R.string.tr_096);
        ids.put("СИЛОВОЙ ПЛАН",R.string.tr_097);
        ids.put("✓ В моих",R.string.tr_098);
        ids.put("Добавь в мои",R.string.tr_099);
        ids.put("Посмотреть план",R.string.tr_100);
        ids.put("Упражнения и расписание",R.string.tr_101);
        ids.put("Добавить в мои",R.string.tr_102);
        ids.put("ПРОГРАММА · ",R.string.tr_103);
        ids.put(" ЗАНЯТИЙ",R.string.tr_104);
        ids.put("О программе",R.string.tr_105);
        ids.put("Начать следующий день  →",R.string.tr_106);
        ids.put("Продолжить эту программу  →",R.string.tr_107);
        ids.put("Расписание программы",R.string.tr_108);
        ids.put("Завершено",R.string.tr_109);
        ids.put("Следующая тренировка",R.string.tr_110);
        ids.put("Запланировано",R.string.tr_111);
        ids.put("УПРАВЛЕНИЕ ПРОГРАММОЙ",R.string.tr_112);
        ids.put("Добавить день",R.string.tr_113);
        ids.put("Расширить тренировочный план",R.string.tr_114);
        ids.put("Экспортировать программу",R.string.tr_115);
        ids.put("Сохранить план в JSON",R.string.tr_116);
        ids.put("Создать копию для нового цикла",R.string.tr_117);
        ids.put("Убрать программу из моих?",R.string.tr_118);
        ids.put("\n\nИстория и рабочие веса сохранятся. Незавершённое занятие останется на паузе. Программу можно снова добавить из «Планов».",R.string.tr_119);
        ids.put("Оставить",R.string.tr_120);
        ids.put("Убрать",R.string.tr_121);
        ids.put("Программа убрана из моих",R.string.tr_122);
        ids.put("ТВОЯ АКТИВНОСТЬ",R.string.tr_123);
        ids.put("Каждая сохранённая тренировка — часть истории",R.string.tr_124);
        ids.put("ЗА ПОСЛЕДНИЕ 30 ДНЕЙ",R.string.tr_125);
        ids.put("сохранённых тренировок",R.string.tr_126);
        ids.put("активных дней",R.string.tr_127);
        ids.put("недель подряд",R.string.tr_128);
        ids.put("Календарь активности",R.string.tr_129);
        ids.put("Последние 12 месяцев · листай вбок",R.string.tr_130);
        ids.put("Пн",R.string.tr_131);
        ids.put("Вт",R.string.tr_132);
        ids.put("Ср",R.string.tr_133);
        ids.put("Чт",R.string.tr_134);
        ids.put("Пт",R.string.tr_135);
        ids.put("Сб",R.string.tr_136);
        ids.put("Вс",R.string.tr_137);
        ids.put("Нет сохранённых тренировок",R.string.tr_138);
        ids.put(" занятий · ",R.string.tr_139);
        ids.put(" тренировок, ",R.string.tr_140);
        ids.put("Меньше  ",R.string.tr_141);
        ids.put("  Больше подходов",R.string.tr_142);
        ids.put("Сохрани первую завершённую тренировку — здесь появится первая зелёная клетка.",R.string.tr_143);
        ids.put("ЗА ВСЁ ВРЕМЯ",R.string.tr_144);
        ids.put("Как считаем активность",R.string.tr_145);
        ids.put("Клетка — день сохранения занятия по времени телефона. Яркость зависит от выполненных подходов: 1–5, 6–10, 11–20, 21 и больше. Серия недель продолжается, если на прошлой неделе была тренировка: текущую неделю ещё можно заполнить. Незавершённые занятия не учитываются.",R.string.tr_146);
        ids.put("Вся история",R.string.tr_147);
        ids.put("Открыть результаты тренировок",R.string.tr_148);
        ids.put("Новый цикл",R.string.tr_149);
        ids.put("Создать копию программы с первого дня? История прошлого цикла останется.",R.string.tr_150);
        ids.put("Создать",R.string.tr_151);
        ids.put(" · новый цикл",R.string.tr_152);
        ids.put("Отмена",R.string.tr_153);
        ids.put("Отметка снята. Подход снова доступен.",R.string.tr_154);
        ids.put("↶  Отменить",R.string.tr_155);
        ids.put("Отменить последний подход",R.string.tr_156);
        ids.put("Сначала укажи вес: 0 — без отягощения",R.string.tr_157);
        ids.put("Начни занятие — здесь будут твои подходы.",R.string.tr_158);
        ids.put("ГОТОВ К ТРЕНИРОВКЕ",R.string.tr_159);
        ids.put("Все дни программы завершены",R.string.tr_160);
        ids.put("Выбрать программу",R.string.tr_161);
        ids.put("Включить панель в уведомлениях",R.string.tr_162);
        ids.put("Готово к сохранению",R.string.tr_163);
        ids.put("Тренировка на паузе",R.string.tr_164);
        ids.put("Двигайся в своём темпе",R.string.tr_165);
        ids.put("ТРЕНИРОВКА ВЫПОЛНЕНА",R.string.tr_166);
        ids.put("Отличная работа.",R.string.tr_167);
        ids.put("Все подходы готовы. Осталось сохранить результат.",R.string.tr_168);
        ids.put("Сохранить тренировку  ✓",R.string.tr_169);
        ids.put("ПАУЗА",R.string.tr_170);
        ids.put("ТЕКУЩИЙ ПОДХОД",R.string.tr_171);
        ids.put("Подход ",R.string.tr_172);
        ids.put("РАБОЧИЙ ВЕС",R.string.tr_173);
        ids.put("ПОВТОРЕНИЯ",R.string.tr_174);
        ids.put("раз",R.string.tr_175);
        ids.put("Изменить вес и повторения текущего подхода",R.string.tr_176);
        ids.put("% от максимума · ",R.string.tr_177);
        ids.put("Вес изменён вручную для этого подхода",R.string.tr_178);
        ids.put("Вес и повторы  ›",R.string.tr_179);
        ids.put("ЦЕЛЬ  5–8 ПОВТОРОВ",R.string.tr_180);
        ids.put("Изменить максимумы всей программы",R.string.tr_181);
        ids.put("Продолжить тренировку",R.string.tr_182);
        ids.put("Указать вес",R.string.tr_183);
        ids.put("✓  Подход выполнен",R.string.tr_184);
        ids.put("Пауза",R.string.tr_185);
        ids.put("ДАЛЕЕ",R.string.tr_186);
        ids.put("Укажи вес",R.string.tr_187);
        ids.put("  ·  подход ",R.string.tr_188);
        ids.put("МАРШРУТ ТРЕНИРОВКИ",R.string.tr_189);
        ids.put(" · выполнен",R.string.tr_190);
        ids.put("Изменить",R.string.tr_191);
        ids.put("Другая программа",R.string.tr_192);
        ids.put("Текущая сохранится на паузе",R.string.tr_193);
        ids.put("Как отмечать подходы",R.string.tr_194);
        ids.put("Нажми на галочку любого подхода, чтобы отметить или отменить его. Нажми на вес, чтобы записать фактический результат.",R.string.tr_195);
        ids.put("Отменить занятие без сохранения",R.string.tr_196);
        ids.put("Отменить тренировку?",R.string.tr_197);
        ids.put("Отметки текущего занятия будут удалены. Этот день можно начать заново.",R.string.tr_198);
        ids.put("Отменить занятие",R.string.tr_199);
        ids.put("Введите число ",R.string.tr_200);
        ids.put("от 0",R.string.tr_201);
        ids.put("больше 0",R.string.tr_202);
        ids.put(" до 2000",R.string.tr_203);
        ids.put("Нужно целое число от 1 до ",R.string.tr_204);
        ids.put("Рабочий вес, кг · 0 = без отягощения",R.string.tr_205);
        ids.put("Повторения",R.string.tr_206);
        ids.put("Остальные подходы этого блока",R.string.tr_207);
        ids.put("Этот подход уже выполнен",R.string.tr_208);
        ids.put("Введи максимумы, от которых строится план. Все процентные веса обновятся сразу — во всех днях и в оставшихся подходах текущего занятия.",R.string.tr_209);
        ids.put("Присед · 100%, кг",R.string.tr_210);
        ids.put("Жим лёжа · 100%, кг",R.string.tr_211);
        ids.put("Становая тяга · 100%, кг",R.string.tr_212);
        ids.put("Выполненные подходы и вручную выбранные веса сохранятся.",R.string.tr_213);
        ids.put("Максимумы на всю программу",R.string.tr_214);
        ids.put("Применить ко всем дням",R.string.tr_215);
        ids.put("Веса программы обновлены",R.string.tr_216);
        ids.put("Рабочие веса уже рассчитаны от твоих максимумов. Чтобы изменить вес сразу во всех днях, открой «Твои максимумы» в программе.",R.string.tr_217);
        ids.put("Вес выбирается в зале",R.string.tr_218);
        ids.put("＋ Добавить упражнение",R.string.tr_219);
        ids.put("Закрыть",R.string.tr_220);
        ids.put("Упражнение",R.string.tr_221);
        ids.put("Фиксированный вес, кг (пусто = выбрать в зале)",R.string.tr_222);
        ids.put("Подходы",R.string.tr_223);
        ids.put("Сохранить расчёт от максимума",R.string.tr_224);
        ids.put("Редактировать блок",R.string.tr_225);
        ids.put("Укажи название",R.string.tr_226);
        ids.put("ЖУРНАЛ РЕЗУЛЬТАТОВ",R.string.tr_227);
        ids.put("Прошлые занятия, веса и повторения.",R.string.tr_228);
        ids.put("Прогресс начинается здесь",R.string.tr_229);
        ids.put("Заверши первое занятие — результат появится здесь.",R.string.tr_230);
        ids.put("К тренировке",R.string.tr_231);
        ids.put("ИТОГО ЗА ВСЁ ВРЕМЯ",R.string.tr_232);
        ids.put(" подходов выполнено",R.string.tr_233);
        ids.put("Посмотреть результат",R.string.tr_234);
        ids.put("Упражнения, веса и повторения",R.string.tr_235);
        ids.put("ТРЕНИРОВКА СОХРАНЕНА",R.string.tr_236);
        ids.put("Без веса",R.string.tr_237);
        ids.put("Готово",R.string.tr_238);
        ids.put("Название программы",R.string.tr_239);
        ids.put("Моя программа",R.string.tr_240);
        ids.put("Своя программа",R.string.tr_241);
        ids.put("Добавить первый день",R.string.tr_242);
        ids.put("Введи название программы",R.string.tr_243);
        ids.put("Название дня",R.string.tr_244);
        ids.put("День ",R.string.tr_245);
        ids.put("Первое упражнение",R.string.tr_246);
        ids.put("Вес, кг · пусто = выбрать в зале",R.string.tr_247);
        ids.put("Новый тренировочный день",R.string.tr_248);
        ids.put("Добавить",R.string.tr_249);
        ids.put("Введи название дня и упражнения",R.string.tr_250);
        ids.put("Добавить упражнение",R.string.tr_251);
        ids.put("Введи название упражнения",R.string.tr_252);
        ids.put("Название",R.string.tr_253);
        ids.put(" дней · ",R.string.tr_254);
        ids.put("В ",R.string.tr_255);
        ids.put(" блоках вес не указан: выберешь его перед подходом.",R.string.tr_256);
        ids.put("ДЕНЬ ",R.string.tr_257);
        ids.put("Проверка импорта",R.string.tr_258);
        ids.put("Твои данные. Твои правила.",R.string.tr_259);
        ids.put("Твой дневник силы",R.string.tr_260);
        ids.put("НА ТЕЛЕФОНЕ · БЕЗ АККАУНТА",R.string.tr_261);
        ids.put("ДАННЫЕ И РЕЗЕРВНЫЕ КОПИИ",R.string.tr_262);
        ids.put("Сохранить копию",R.string.tr_263);
        ids.put("Программы, история и текущее занятие",R.string.tr_264);
        ids.put("Восстановить из файла",R.string.tr_265);
        ids.put("Загрузить ранее сохранённую копию",R.string.tr_266);
        ids.put("КАК ЭТО РАБОТАЕТ",R.string.tr_267);
        ids.put("Добавление программ",R.string.tr_268);
        ids.put("XLS Шейко · CSV · XLSX · JSON",R.string.tr_269);
        ids.put("Можно загрузить исходную XLS-таблицу Шейко, JSON программы или CSV / XLSX по шаблону. В XLSX используется первый лист с пятью колонками.",R.string.tr_270);
        ids.put("Импорт программы",R.string.tr_271);
        ids.put("Trace  /  ВЕРСИЯ 0.12.1",R.string.tr_272);
        ids.put("Повреждены сохранённые занятия",R.string.tr_273);
        ids.put("Повреждена связь занятия с программой",R.string.tr_274);
        ids.put("Это не резервная копия Trace",R.string.tr_275);
        ids.put("Повреждена программа в копии",R.string.tr_276);
        ids.put("В копии отсутствует активная программа",R.string.tr_277);
        ids.put("Восстановить копию?",R.string.tr_278);
        ids.put("Текущие данные будут заменены: ",R.string.tr_279);
        ids.put(" программ, ",R.string.tr_280);
        ids.put(" тренировок. Сначала сохрани текущую копию, если она нужна.",R.string.tr_281);
        ids.put("Восстановить",R.string.tr_282);
        ids.put("Повреждена тренировка в копии",R.string.tr_283);
        ids.put("Повреждён прогресс",R.string.tr_284);
        ids.put("Повреждены подходы",R.string.tr_285);
        ids.put("Файл сохранён",R.string.tr_286);
        ids.put("Импортированная программа",R.string.tr_287);
        ids.put("Читаю файл…",R.string.tr_288);
        ids.put("Не получилось",R.string.tr_289);
        ids.put("Проверь данные и попробуй ещё раз.",R.string.tr_290);
        ids.put("Сохрани результат занятия",R.string.tr_291);
        ids.put("Укажи вес в приложении",R.string.tr_292);
        ids.put(" кг  ×  ",R.string.tr_293);
        ids.put(" повт.",R.string.tr_294);
        ids.put("Тренировка выполнена",R.string.tr_295);
        ids.put("Указать повторы и сохранить",R.string.tr_296);
        ids.put("Сохранить тренировку",R.string.tr_297);
        ids.put("Указать рабочий вес",R.string.tr_298);
        ids.put("Подход выполнен",R.string.tr_299);
        ids.put("ГОТОВО",R.string.tr_300);
        ids.put("ПОДХОД ",R.string.tr_301);
        ids.put("Выполнено ",R.string.tr_302);
        ids.put("Отменить последний выполненный подход",R.string.tr_303);
        ids.put("Продолжить",R.string.tr_304);
        ids.put("Текущая тренировка",R.string.tr_305);
        ids.put("Сохрани тренировку в историю",R.string.tr_306);
        ids.put(" кг × ",R.string.tr_307);
        ids.put(" · готово ",R.string.tr_308);
        ids.put("Отменить",R.string.tr_309);
        ids.put("Сохрани результат",R.string.tr_310);
        ids.put("Укажи вес в Trace",R.string.tr_311);
        ids.put("Готово ",R.string.tr_312);
        ids.put(" · сохрани результат",R.string.tr_313);
        ids.put(" · выполнено ",R.string.tr_314);
        ids.put("Отменить подход",R.string.tr_315);
        ids.put("Все подходы · выполнено ",R.string.tr_316);
        ids.put("Некорректный JSON",R.string.tr_317);
        ids.put("Максимум должен быть больше 0 и не больше 2000 кг",R.string.tr_318);
        ids.put("Программа завершена",R.string.tr_319);
        ids.put("Нужны название и 1–366 тренировочных дней",R.string.tr_320);
        ids.put(": нет упражнений",R.string.tr_321);
        ids.put("Проверь упражнение, подходы и повторения в дне ",R.string.tr_322);
        ids.put("Некорректный вес",R.string.tr_323);
        ids.put("Некорректный процент или исходный максимум",R.string.tr_324);
        ids.put("В программе слишком много подходов",R.string.tr_325);
        ids.put("Файл больше 5 МБ",R.string.tr_326);
        ids.put("Нужна таблица с заголовком и упражнениями",R.string.tr_327);
        ids.put("Поддерживается XLS Шейко или таблица с 5 колонками: день;упражнение;подходы;повторения;вес. Шаблон доступен в библиотеке.",R.string.tr_328);
        ids.put("Строка ",R.string.tr_329);
        ids.put(": нужны ровно 5 колонок",R.string.tr_330);
        ids.put(": укажи день",R.string.tr_331);
        ids.put(": проверь числа",R.string.tr_332);
        ids.put("Неизвестная структура листа План",R.string.tr_333);
        ids.put(" · День ",R.string.tr_334);
        ids.put("Не найдено начало дня",R.string.tr_335);
        ids.put("Не распознаны подходы в строке ",R.string.tr_336);
        ids.put("Неизвестная формула в строке ",R.string.tr_337);
        ids.put(". Импорт остановлен, чтобы не потерять пересчёт весов.",R.string.tr_338);
        ids.put("Распакованная таблица слишком большая",R.string.tr_339);
        ids.put("Не найден первый лист XLSX",R.string.tr_340);
        ids.put("В XLSX должно быть 5 колонок по шаблону",R.string.tr_341);
        ids.put("Для импорта XLSX сохрани значения вместо формул. Процентные формулы поддержаны в XLS Шейко.",R.string.tr_342);
        ids.put("Не удалось загрузить программу",R.string.tr_343);
        ids.put("Не удалось сохранить тренировку",R.string.tr_344);
        ids.put("Сначала задай рабочие веса Злата",R.string.tr_345);
        ids.put("Неделя ",R.string.tr_346);
        ids.put("Подтягивания с весом",R.string.tr_347);
        ids.put("Брусья с весом",R.string.tr_348);
        ids.put("Укажи дополнительный вес от 0 до 1995 кг и 3 или 4 подхода",R.string.tr_349);
        ids.put("Подтягивания: ",R.string.tr_350);
        ids.put("Брусья: ",R.string.tr_351);
        ids.put("Шейко · КМС / МС",R.string.tr_352);
        ids.put("Матвей Злат · турник и брусья",R.string.tr_353);
        ids.put("Жим из-за головы",R.string.tr_354);
        ids.put("Жим лёжа",R.string.tr_355);
        ids.put("Наклонный жим",R.string.tr_356);
        ids.put("Наклоны сидя",R.string.tr_357);
        ids.put("Наклоны стоя",R.string.tr_358);
        ids.put("наклоны стоя",R.string.tr_359);
        ids.put("Пресс",R.string.tr_360);
        ids.put("Разводка",R.string.tr_361);
        ids.put("Разгибания рук",R.string.tr_362);
        ids.put("Становая тяга",R.string.tr_363);
        ids.put("Тяга до колен",R.string.tr_364);
        ids.put("Тяга из ямы",R.string.tr_365);
        ids.put("Тяга с плинтов",R.string.tr_366);
        ids.put("Язык приложения",R.string.tr_367);
        ids.put("Русский",R.string.tr_368);
        ids.put("English",R.string.tr_369);
        ids.put("Выбери язык интерфейса",R.string.tr_370);
        ids.put("Открытая схема Злата 2018 года, по русскому переводу ролика.\n\nПоследний подход: 8 и более повторений → +5 кг; 7 → +2,5 кг; 6 → +1,25 кг; 5 и меньше → без прибавки. Адаптация Trace под блины от 1,25 кг: прибавка 0,5 кг отключена. Расчёт отдельно для каждого упражнения, от веса последнего подхода по порядку в плане.\n\nНачинай с веса, с которым можешь выполнить 10–12 чистых повторений, работая в диапазоне 5–8. Разминочные подходы выполняй отдельно.\n\n12 занятий — организация дневника, не авторское ограничение длительности. В конце можно создать копию цикла. Исторические результаты не пересчитываются.",R.string.tr_371);
        ids.put("день;упражнение;подходы;повторения;вес\nДень 1;Присед;3;5;60\nДень 1;Жим лёжа;3;5;40\nДень 2;Становая тяга;3;5;80\n",R.string.tr_372);
        ids.put("Базовая схема 2018 года: 3 занятия в неделю, 3–4 подхода по 5–8 повторений. Здесь 12 занятий для удобства дневника, а не авторский срок цикла. Между занятиями — день отдыха. После цикла можно создать копию.",R.string.tr_373);
        ids.put("Trace  /  ВЕРСИЯ 0.27.0",R.string.tr_374);
    }
    public static Context wrap(Context c){String code=c.getSharedPreferences("trace-settings",0).getString("language","ru");Configuration config=new Configuration(c.getResources().getConfiguration());config.setLocale(Locale.forLanguageTag(code));return c.createConfigurationContext(config);}
    public static void init(Context c){language=c.getSharedPreferences("trace-settings",0).getString("language","ru");localized=wrap(c.getApplicationContext());}
    public static boolean english(){return language.equals("en");}
    public static Locale locale(){return Locale.forLanguageTag(language);}
    public static void set(Context c,String code){if(!code.equals("ru")&&!code.equals("en"))throw new IllegalArgumentException("Unsupported language");c.getSharedPreferences("trace-settings",0).edit().putString("language",code).commit();init(c);}
    public static String t(String source){Integer id=ids.get(source);return !english()||localized==null||id==null?source:localized.getString(id);}
    public static String content(String source){if(!english()||source==null)return source;String translated=t(source);if(!translated.equals(source))return translated;
        if(source.matches("Неделя \\d+ · День \\d+"))return source.replace("Неделя ","Week ").replace("День ","Day ");
        if(source.startsWith("Неделя ")&&source.contains(" · ")){String[] parts=source.split(" · ",2);String tail=t(parts[1]);if(!tail.equals(parts[1]))return parts[0].replace("Неделя ","Week ")+" · "+tail;}
        if(source.matches("День \\d+"))return source.replace("День ","Day ");
        if(source.startsWith("Подтягивания: ")&&source.contains("Брусья: "))return source.replace("Подтягивания: ","Pull-ups: ").replace("Брусья: ","Dips: ").replace(" кг"," kg");
        return source;
    }
}
