package com.podhod.app;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.OpenableColumns;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    final int BG=Color.rgb(13,19,28), CARD=Color.rgb(24,33,46), LINE=Color.rgb(43,56,73), TEXT=Color.rgb(245,248,255), MUTED=Color.rgb(173,186,205), GREEN=Color.rgb(111,227,203);
    final int BLUE=Color.rgb(146,174,255); LinearLayout actionDock,quickActions;
    android.graphics.Bitmap backgroundPhoto;
    final android.util.SparseArray<android.graphics.Bitmap> covers=new android.util.SparseArray<>();
    WalkingProgress walkingProgress;
    boolean walkTab;
    StepsPage stepsView; final Handler stepHandler=new Handler(Looper.getMainLooper());
    final Runnable stepTick=new Runnable(){public void run(){if(page.equals("steps")&&stepsView!=null)stepsView.refresh();if(page.equals("progress")&&walkingProgress!=null)walkingProgress.refresh();stepHandler.postDelayed(this,2000);}};
    Store store; LinearLayout root,body;String page="mine",selected="";String exportText="";String coverTarget="";
    final BroadcastReceiver changed=new BroadcastReceiver(){public void onReceive(Context c,Intent i){render();}};
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+0.5f);}
    @Override protected void attachBaseContext(Context base){super.attachBaseContext(Lang.wrap(base));}
    @Override public void onCreate(Bundle saved){super.onCreate(saved);store=Store.get(this);if(saved!=null){walkTab=saved.getBoolean("walkTab",false);page=saved.getString("page","mine");selected=saved.getString("selected","");try(InputStream in=openFileInput("pending-export.json")){exportText=new String(FullBackup.read(in),StandardCharsets.UTF_8);}catch(Exception ignored){}coverTarget=saved.getString("coverTarget","");}if(saved==null&&getIntent().getBooleanExtra("workout",false))page="workout";if(getIntent().getBooleanExtra("steps",false)&&saved==null){page="steps";walkTab=getIntent().getBooleanExtra("walk",false);}render();receivePlan(getIntent());}
    @Override protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putBoolean("walkTab",walkTab);b.putString("page",page);b.putString("selected",selected);b.putString("coverTarget",coverTarget);}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);if(i.getBooleanExtra("workout",false))page="workout";if(i.getBooleanExtra("steps",false)){page="steps";walkTab=i.getBooleanExtra("walk",false);}render();receivePlan(i);}
    @android.annotation.SuppressLint("UnspecifiedRegisterReceiverFlag") // Older Android is protected by a signature permission.
    @Override protected void onStart(){super.onStart();IntentFilter filter=new IntentFilter("com.podhod.app.CHANGED");if(Build.VERSION.SDK_INT>=33)registerReceiver(changed,filter,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(changed,filter,"com.podhod.app.INTERNAL",null);Notices.update(this);try{Steps.resume(this);}catch(RuntimeException ignored){}stepHandler.post(stepTick);render();}
    @Override protected void onStop(){stepHandler.removeCallbacks(stepTick);unregisterReceiver(changed);super.onStop();}
    @Override public void onBackPressed(){if(!page.equals("mine")){page="mine";render();}else super.onBackPressed();}

    GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(Lang.content(s));t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("tnum");t.setIncludeFontPadding(false);t.setLineSpacing(dp(3),1);return t;}
    TextView title(String s,int size){TextView t=text(s,size,TEXT);t.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));return t;}
    void space(LinearLayout l,int n){View v=new View(this);l.addView(v,new LinearLayout.LayoutParams(1,dp(n)));}
    void label(LinearLayout l,String s){TextView t=text(s,13,MUTED);l.addView(t);space(l,10);}
    LinearLayout card(LinearLayout parent){LinearLayout c=column();c.setPadding(dp(20),dp(20),dp(20),dp(20));GradientDrawable bg=shape(CARD,24);bg.setStroke(dp(1),0xFF283548);c.setBackground(bg);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(14);parent.addView(c,lp);return c;}
    void clickable(View v,Runnable action){v.setClickable(true);v.setFocusable(true);v.setOnClickListener(x->action.run());}
    TextView button(LinearLayout parent,String name,boolean primary,Runnable click){TextView b=title(name,16);b.setTextColor(primary?BG:TEXT);b.setGravity(Gravity.CENTER);b.setMinHeight(dp(54));b.setPadding(dp(16),dp(14),dp(16),dp(14));b.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x30FFFFFF),shape(primary?GREEN:LINE,18),null));clickable(b,click);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(10);parent.addView(b,lp);return b;}
    void link(LinearLayout l,String s,Runnable action){TextView t=text(s,15,GREEN);t.setMinHeight(dp(48));t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(0,dp(12),0,dp(12));clickable(t,action);l.addView(t);}
    void divider(LinearLayout l){View v=new View(this);v.setBackgroundColor(LINE);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(1));lp.topMargin=dp(12);lp.bottomMargin=dp(12);l.addView(v,lp);}
    TextView badge(LinearLayout l,String name,int color){TextView t=text(name,12,color);t.setTypeface(Typeface.DEFAULT_BOLD);t.setPadding(dp(10),dp(6),dp(10),dp(6));t.setBackground(shape((color&0x00FFFFFF)|0x18000000,8));l.addView(t,new LinearLayout.LayoutParams(-2,-2));return t;}
    void progress(LinearLayout l,int done,int total){ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(Math.max(1,total));bar.setProgress(done);bar.setProgressTintList(android.content.res.ColorStateList.valueOf(GREEN));bar.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(LINE));l.addView(bar,new LinearLayout.LayoutParams(-1,dp(5)));}
    void stat(LinearLayout row,String value,String name,int color){LinearLayout cell=column();cell.setPadding(dp(4),dp(6),dp(4),dp(6));TextView n=title(value,34);n.setTextColor(color);cell.addView(n);cell.addView(text(name,13,MUTED));row.addView(cell,new LinearLayout.LayoutParams(0,-2,1));}
    void photoBackground(View view,int mode){if(backgroundPhoto==null)backgroundPhoto=android.graphics.BitmapFactory.decodeResource(getResources(),R.drawable.gym_background);view.setBackground(new PhotoBackdrop(backgroundPhoto,getResources().getDisplayMetrics().density,mode));}
    void coverBackground(View view,int resource){android.graphics.Bitmap photo=covers.get(resource);if(photo==null){android.graphics.BitmapFactory.Options options=new android.graphics.BitmapFactory.Options();options.inSampleSize=2;photo=android.graphics.BitmapFactory.decodeResource(getResources(),resource,options);covers.put(resource,photo);}view.setBackground(new PhotoBackdrop(photo,getResources().getDisplayMetrics().density,3));}
    void planBackground(View view,JSONObject p){android.graphics.Bitmap custom=p==null?null:PlanImages.decode(p.optString("coverImage"));if(custom!=null)view.setBackground(new PhotoBackdrop(custom,getResources().getDisplayMetrics().density,3,new CoverFrame((float)p.optDouble("coverX",.5),(float)p.optDouble("coverY",.5),(float)p.optDouble("coverZoom",1))));else coverBackground(view,p!=null&&Zlat.is(p)?R.drawable.street_cover:R.drawable.strength_cover);}
    LinearLayout programCover(LinearLayout parent,JSONObject p,String eyebrow,boolean showTitle){LinearLayout cover=column();cover.setPadding(dp(18),dp(18),dp(18),dp(18));cover.setMinimumHeight(dp(showTitle?156:110));cover.setGravity(Gravity.BOTTOM);planBackground(cover,p);badge(cover,eyebrow,p!=null&&Zlat.is(p)?GREEN:BLUE);if(showTitle){space(cover,12);cover.addView(title(p.optString("name"),24));}parent.addView(cover,new LinearLayout.LayoutParams(-1,-2));return cover;}
    LinearLayout programCard(LinearLayout parent,JSONObject p,String eyebrow){LinearLayout outer=card(parent);outer.setPadding(0,0,0,0);outer.setBackground(shape(Zlat.is(p)?0xFF172D28:0xFF192538,24));programCover(outer,p,eyebrow,true);LinearLayout content=column();content.setPadding(dp(18),dp(18),dp(18),dp(18));outer.addView(content);if(!eyebrow.equals(PlanCategory.label(p).toUpperCase(Lang.locale()))){content.addView(text(PlanCategory.label(p),13,BLUE));space(content,8);}return content;}
    void render(){
        if(page.equals("home"))page="mine";
        if(!page.equals("steps"))walkTab=false;
        walkingProgress=null;stepsView=null;quickActions=null;root=column();if(page.equals("home"))photoBackground(root,0);else root.setBackgroundColor(page.equals("library")?0xFF171525:page.equals("history")?0xFF191813:page.equals("workout")?0xFF0B1718:page.equals("progress")?0xFF101E18:BG);
        root.setFocusableInTouchMode(true);setContentView(root);root.requestApplyInsets();
        LinearLayout top=new LinearLayout(this);top.setPadding(dp(22),dp(6),dp(14),dp(6));top.setGravity(Gravity.CENTER_VERTICAL);
        ImageView mark=new ImageView(this);mark.setImageResource(R.drawable.ic_trace);top.addView(mark,new LinearLayout.LayoutParams(dp(26),dp(26)));
        TextView brand=title("  Trace",20);brand.setGravity(Gravity.CENTER_VERTICAL);top.addView(brand,new LinearLayout.LayoutParams(0,dp(48),1));
        ImageView settings=new ImageView(this);settings.setImageDrawable(new LineIcon("settings",MUTED));settings.setPadding(dp(13),dp(13),dp(13),dp(13));settings.setContentDescription(Lang.t("Настройки"));clickable(settings,()->{page="settings";render();});top.addView(settings,new LinearLayout.LayoutParams(dp(48),dp(48)));root.addView(top);
        ScrollView scroll=new StepsSwipeScroll(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);scroll.setVerticalScrollBarEnabled(false);body=column();body.setPadding(dp(20),dp(14),dp(20),dp(16));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        actionDock=column();actionDock.setPadding(dp(20),dp(4),dp(20),dp(10));actionDock.setBackground(shape(CARD,24));
        switch(page){case "mine":programs(true);break;case "library":programs(false);break;case "history":history();break;case "progress":progressPage();break;case "steps":stepsView=new StepsPage(this);break;case "program":programView();break;case "workout":workout();break;case "settings":settings();break;default:programs(true);}
        if(actionDock.getChildCount()>0)root.addView(actionDock);
        LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(8),dp(10),dp(8),dp(10));nav.setBackgroundColor(BG);String[] names={Lang.t("Планы"),Lang.t("Мои планы"),Lang.t("Тренировка"),Lang.t("Прогресс"),Lang.t("Шаги")},keys={"library","mine","workout","progress","steps"};
        String activeTab=(page.equals("program")||page.equals("history")||page.equals("settings"))?"mine":page;
        for(int i=0;i<keys.length;i++){
            final String key=keys[i];boolean current=activeTab.equals(key);
            LinearLayout item=column();item.setGravity(Gravity.CENTER);item.setMinimumHeight(dp(80));item.setPadding(dp(2),dp(8),dp(2),dp(8));
            FrameLayout pill=new FrameLayout(this);
            ImageView icon=new ImageView(this);icon.setImageDrawable(new LineIcon(key,current?BG:TEXT));
            pill.addView(icon,new FrameLayout.LayoutParams(dp(28),dp(28),Gravity.CENTER));
            item.addView(pill,new LinearLayout.LayoutParams(dp(36),dp(36)));space(item,6);
            TextView t=text(names[i],12,current?BG:TEXT);t.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));t.setGravity(Gravity.CENTER);t.setMaxLines(2);t.setAutoSizeTextTypeUniformWithConfiguration(9,12,1,android.util.TypedValue.COMPLEX_UNIT_SP);
            item.addView(t,new LinearLayout.LayoutParams(-1,-2));item.setSelected(current);
            item.setContentDescription(key.equals("mine")?Lang.t("Мои тренировки"):key.equals("library")?Lang.t("Библиотека программ"):names[i]);
            GradientDrawable tile=shape(current?GREEN:0xFF1E2A3B,16);tile.setStroke(dp(1),current?GREEN:0xFF40516A);
            item.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x207FE3CB),tile,shape(Color.WHITE,16)));
            clickable(item,()->{if(key.equals("steps"))walkTab=false;page=key;render();});LinearLayout.LayoutParams tabParams=new LinearLayout.LayoutParams(0,-2,1f);if(i>0)tabParams.leftMargin=dp(5);nav.addView(item,tabParams);
        }
        JSONObject deleted=DeletedItems.last(store.data);if(deleted!=null){LinearLayout undo=column();undo.setPadding(dp(20),dp(6),dp(20),dp(6));undo.setBackgroundColor(CARD);TextView notice=text(Lang.t("Удалено: ")+Lang.content(deleted.optString("name")),14,MUTED);notice.setMaxLines(1);notice.setEllipsize(android.text.TextUtils.TruncateAt.END);undo.addView(notice);link(undo,Lang.t("Вернуть"),()->{if(DeletedItems.undo(store.data)){store.save();Notices.update(this);render();}});root.addView(undo);}
        root.addView(nav);
        root.setOnApplyWindowInsetsListener((v,insets)->{
            v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),0);
            nav.setPadding(dp(8),dp(10),dp(8),dp(10)+insets.getSystemWindowInsetBottom());
            return insets;
        });
        root.requestApplyInsets();root.requestFocus();
    }

    ArrayList<JSONObject> programsSorted(boolean mine){ArrayList<JSONObject> list=new ArrayList<>();JSONArray a=store.data.optJSONArray("programs");for(int i=0;i<a.length();i++)if(!mine||a.optJSONObject(i).optBoolean("mine"))list.add(a.optJSONObject(i));list.sort((a1,b)->Long.compare(b.optLong("lastUsed"),a1.optLong("lastUsed")));return list;}

    void hint(LinearLayout parent,String name,String explanation){TextView detail=text(explanation,14,MUTED);detail.setPadding(0,0,0,dp(12));detail.setVisibility(View.GONE);TextView toggle=text(name+"  ⌄",14,BLUE);toggle.setMinHeight(dp(48));toggle.setGravity(Gravity.CENTER_VERTICAL);clickable(toggle,()->{boolean show=detail.getVisibility()!=View.VISIBLE;detail.setVisibility(show?View.VISIBLE:View.GONE);toggle.setText(name+(show?"  ⌃":"  ⌄"));});parent.addView(toggle);parent.addView(detail);}
    void tags(LinearLayout parent,String... labels){LinearLayout row=new LinearLayout(this);for(String label:labels){TextView t=text(label,12,MUTED);t.setGravity(Gravity.CENTER);t.setPadding(dp(4),dp(9),dp(4),dp(9));t.setBackground(shape(BG,10));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);if(row.getChildCount()>0)lp.leftMargin=dp(6);row.addView(t,lp);}parent.addView(row);}
    void metricTile(LinearLayout row,String label,String value,String unit,int color){LinearLayout tile=column();tile.setPadding(dp(14),dp(16),dp(14),dp(16));tile.setBackground(shape(BG,18));tile.addView(text(label,14,MUTED));space(tile,10);TextView number=title(value,32);number.setTextColor(color);tile.addView(number);space(tile,4);tile.addView(text(unit,13,MUTED));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);if(row.getChildCount()>0)lp.leftMargin=dp(10);row.addView(tile,lp);}
    void repChoices(LinearLayout parent,EditText input,String exercise,double kg){label(parent,exercise+Lang.t(" · быстрый выбор"));LinearLayout row=new LinearLayout(this);for(int n=5;n<=8;n++){final int reps=n;TextView choice=title(String.valueOf(n),18);choice.setGravity(Gravity.CENTER);choice.setBackground(shape(LINE,12));clickable(choice,()->input.setText(String.valueOf(reps)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(48),1);if(n>5)lp.leftMargin=dp(8);row.addView(choice,lp);}parent.addView(row);TextView preview=text("",14,GREEN);preview.setPadding(0,dp(10),0,dp(18));parent.addView(preview);Runnable update=()->{try{int reps=Integer.parseInt(input.getText().toString());preview.setText(Lang.t("Дальше: ")+Engine.number(kg)+" → "+Engine.number(Math.min(2000,kg+Zlat.increment(reps)))+Lang.t(" кг"));for(int i=0;i<row.getChildCount();i++){TextView t=(TextView)row.getChildAt(i);boolean selected=reps==i+5;t.setTextColor(selected?BG:TEXT);t.setBackground(shape(selected?GREEN:LINE,12));}}catch(NumberFormatException e){preview.setText(Lang.t("Введи фактические повторы выше"));}};input.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){update.run();}public void afterTextChanged(android.text.Editable e){}});update.run();}
    void heading(String name,String subtitle){body.addView(title(name,30));space(body,6);if(!subtitle.isEmpty())body.addView(text(subtitle,15,MUTED));space(body,22);}
    void weightsPanel(LinearLayout parent,JSONObject p){weightsPanel(parent,p,false);}
    void weightsPanel(LinearLayout parent,JSONObject p,boolean inline){
        if(Zlat.is(p)){zlatPanel(parent,p,inline);return;}JSONObject maxima=p.optJSONObject("maxima");if(maxima==null||maxima.length()==0)return;
        LinearLayout c=inline?parent:card(parent);LinearLayout header=new LinearLayout(this);TextView title=title(Lang.t("Твои максимумы"),18);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView tag=text(Lang.t("кг"),14,MUTED);header.addView(tag);c.addView(header);space(c,6);c.addView(text(Lang.t("Один раз на всю программу"),13,MUTED));space(c,16);
        LinearLayout values=new LinearLayout(this);String[] names={Lang.t("Присед"),Lang.t("Жим"),Lang.t("Тяга")};
        for(int i=0;i<3;i++){final int index=i;LinearLayout cell=column();cell.setPadding(dp(10),dp(14),dp(6),dp(14));cell.setBackground(shape(BG,14));cell.addView(text(names[i],13,MUTED));space(cell,5);TextView number=title(maxima.has(Importer.LIFTS[i])?Engine.number(maxima.optDouble(Importer.LIFTS[i])):"—",25);number.setTextColor(i==1?BLUE:GREEN);cell.addView(number);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);if(i>0)lp.leftMargin=dp(8);values.addView(cell,lp);clickable(cell,()->maxima(p));cell.setContentDescription(Lang.t("Максимум: ")+names[index]);}
        c.addView(values);button(c,Lang.t("Изменить максимумы"),false,()->maxima(p));hint(c,Lang.t("Как считаются веса"),Lang.t("Введи максимумы один раз. Проценты плана пересчитают рабочие веса всех будущих дней; выполненные подходы останутся в истории."));
    }
    void zlatPanel(LinearLayout parent,JSONObject p,boolean inline){LinearLayout c=inline?parent:card(parent);c.addView(title(Lang.t("Рабочие веса"),22));space(c,6);c.addView(text(Lang.t("Приложение повышает их после занятия"),13,MUTED));space(c,18);JSONObject weights=p.optJSONObject("workingWeights");LinearLayout row=new LinearLayout(this);metricTile(row,Lang.t("Турник"),weights==null?"—":"+"+Engine.number(weights.optDouble("pullup")),Lang.t("кг"),BLUE);metricTile(row,Lang.t("Брусья"),weights==null?"—":"+"+Engine.number(weights.optDouble("dip")),Lang.t("кг"),GREEN);c.addView(row);space(c,14);tags(c,Lang.t("3 дня / нед"),p.optInt("zlatSets",3)+Lang.t(" подхода"),Lang.t("5–8 повторов"));button(c,Lang.t("Настроить рабочие веса"),false,()->zlatSetup(p,()->{}));if(!p.optString("lastProgression").isEmpty())hint(c,Lang.t("Прибавка после занятия"),p.optString("lastProgression"));link(c,Lang.t("Правила и источник"),()->{LinearLayout b=form();b.addView(text(Lang.t("Открытая схема Злата 2018 года, по русскому переводу ролика.\n\nПоследний подход: 8 и более повторений → +5 кг; 7 → +2,5 кг; 6 → +1,25 кг; 5 → +0,5 кг; меньше 5 → без прибавки. Расчёт отдельно для каждого упражнения, от веса последнего подхода по порядку в плане.\n\nНачинай с веса, с которым можешь выполнить 10–12 чистых повторений, работая в диапазоне 5–8. Разминочные подходы выполняй отдельно.\n\n12 занятий — организация дневника, не авторское ограничение длительности. В конце можно создать копию цикла. Исторические результаты не пересчитываются."),15,MUTED));link(b,Lang.t("Оригинальное видео Злата"),()->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.youtube.com/watch?v=AeB4znuGuSo"))));link(b,Lang.t("Русский перевод · сообщение №68"),()->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://forum.steelfactor.ru/index.php?page=3&showtopic=46569"))));panel(Lang.t("Как работает программа"),b,Lang.t("Понятно"),()->{},false);});}
    void zlatSetup(JSONObject p,Runnable after){LinearLayout b=form();b.addView(text(Lang.t("Дополнительный вес, без массы тела. Для будущих занятий."),14,MUTED));space(b,16);JSONObject w=p.optJSONObject("workingWeights");EditText pull=input(b,Lang.t("Подтягивания, кг"),w==null?"":Engine.number(w.optDouble("pullup")),true),dip=input(b,Lang.t("Брусья, кг"),w==null?"":Engine.number(w.optDouble("dip")),true),sets=input(b,Lang.t("Подходов на упражнение: 3 или 4"),String.valueOf(p.optInt("zlatSets",3)),true);formDialog(Lang.t("Настройка программы Злата"),b,Lang.t("Сохранить"),()->{double pw=positive(pull,true),dw=positive(dip,true);int sn=integer(sets,4);Zlat.configure(p,pw,dw,sn);store.save();render();after.run();});}
    void zlatFinish(JSONObject session){if(Engine.doneCount(session)!=session.optJSONArray("sets").length())return;LinearLayout b=form();b.addView(text(Lang.t("Сколько повторов вышло в последних подходах? Следующий вес посчитаем сами."),15,MUTED));space(b,16);JSONObject pull=Zlat.last(session,"pullup"),dip=Zlat.last(session,"dip");if(pull==null||dip==null){error(new IllegalArgumentException(Lang.t("В программе должны быть подтягивания и брусья")));return;}EditText pr=input(b,Lang.t("Турник · последний подход"),String.valueOf(pull.optInt("reps")),true);repChoices(b,pr,Lang.t("Турник"),pull.optDouble("kg"));divider(b);EditText dr=input(b,Lang.t("Брусья · последний подход"),String.valueOf(dip.optInt("reps")),true);repChoices(b,dr,Lang.t("Брусья"),dip.optDouble("kg"));int revision=session.optInt("revision");formDialog(Lang.t("Результат занятия"),b,Lang.t("Сохранить и рассчитать веса"),()->{int rp=integer(pr,1000),rd=integer(dr,1000);if(store.active()!=session||session.optInt("revision")!=revision)throw new IllegalArgumentException(Lang.t("Подходы изменились. Открой сохранение заново."));Engine.put(pull,"reps",rp);Engine.put(dip,"reps",rd);Engine.put(session,"confirmedRevision",revision);act("finish");});}

    void home(){
        heading(Lang.t("Сегодня"),new SimpleDateFormat("EEEE, d MMMM",Lang.locale()).format(new Date()));
        JSONObject active=store.active();ArrayList<JSONObject> mine=programsSorted(true);JSONObject p=active!=null?store.program(active.optString("programId")):(mine.isEmpty()?null:mine.get(0));
        if(p!=null){LinearLayout c=card(body);GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xFF234743,0xFF1D2C40});bg.setCornerRadius(dp(24));photoBackground(c,1);badge(c,active!=null?Lang.t("В ПРОЦЕССЕ"):Lang.t("СЛЕДУЮЩАЯ ТРЕНИРОВКА"),GREEN);space(c,16);c.addView(title(p.optString("name"),25));space(c,8);
            JSONArray days=p.optJSONArray("days");int next=p.optInt("nextDay");
            if(active!=null){c.addView(text(active.optString("dayName"),16,MUTED));space(c,18);int done=Engine.doneCount(active),total=active.optJSONArray("sets").length();progress(c,done,total);space(c,8);c.addView(text(done+Lang.t(" из ")+total+Lang.t(" подходов"),13,MUTED));button(c,Lang.t("Продолжить тренировку  →"),true,()->{page="workout";render();});}
            else if(next<days.length()){JSONObject day=days.optJSONObject(next);c.addView(text(day.optString("name"),16,MUTED));space(c,14);tags(c,day.optJSONArray("groups").length()+Lang.t(" блоков"),daySummary(day).split("\n")[0]);button(c,Lang.t("Начать тренировку  →"),true,()->start(p));}
            else{c.addView(text(Lang.t("Все дни завершены"),16,GREEN));button(c,Lang.t("Начать новый цикл"),true,()->repeat(p));}
            link(c,Lang.t("Открыть программу"),()->open(p));
            int preview=p.optInt("nextDay")+(active!=null?1:0);if(preview<days.length()){space(body,10);label(body,Lang.t("ДАЛЬШЕ ПО ПЛАНУ"));JSONObject nextDay=days.optJSONObject(preview);actionRow(body,"arrow",nextDay.optString("name"),daySummary(nextDay),()->dayDialog(p,preview));divider(body);}
            actionRow(body,"mine",Lang.t("Моя программа и веса"),Lang.t("Максимумы и расписание — во вкладке «Мои»"),()->{page="mine";render();});
        }else{LinearLayout c=card(body);c.addView(title(Lang.t("Твой первый план"),24));space(c,8);c.addView(text(Lang.t("Выбери программу или добавь свою."),15,MUTED));button(c,Lang.t("Открыть библиотеку"),true,()->{page="library";render();});}
        JSONArray h=store.data.optJSONArray("history");int count=0;for(int i=0;i<h.length();i++)count+=Engine.doneCount(h.optJSONObject(i));LinearLayout stats=card(body);label(stats,Lang.t("Твой прогресс"));LinearLayout row=new LinearLayout(this);stat(row,String.valueOf(h.length()),Lang.t("тренировок"),TEXT);stat(row,String.valueOf(count),Lang.t("подходов"),TEXT);stats.addView(row);
    }

    String daySummary(JSONObject d){JSONArray a=d.optJSONArray("groups");int n=0;LinkedHashSet<String> names=new LinkedHashSet<>();for(int i=0;i<a.length();i++){JSONObject g=a.optJSONObject(i);n+=g.optInt("sets");names.add(Lang.content(g.optString("exercise")));}return n+Lang.t(" подходов\n")+String.join(" · ",names);}

    void programs(boolean mine){
        if(mine){
            badge(body,Lang.t("ЛИЧНЫЙ ПЛАН"),BLUE);space(body,14);heading(Lang.t("Мои программы"),Lang.t("Твои дни и рабочие веса"));actionRow(body,"history",Lang.t("История тренировок"),store.data.optJSONArray("history").length()+Lang.t(" завершённых занятий"),()->{page="history";render();});space(body,10);
            ArrayList<JSONObject> plans=programsSorted(true);
            for(int index=0;index<plans.size();index++){
                JSONObject p=plans.get(index);JSONArray days=p.optJSONArray("days");int next=p.optInt("nextDay");
                LinearLayout c=programCard(body,p,index==0?Lang.t("ПОСЛЕДНЯЯ ПРОГРАММА"):Lang.t("МОЯ ПРОГРАММА"));
                TextView stage=text(Lang.t("Пройдено ")+next+Lang.t(" из ")+days.length()+Lang.t(" дней"),14,MUTED);c.addView(stage);space(c,10);progress(c,next,days.length());space(c,20);
                if(next<days.length()){JSONObject day=days.optJSONObject(next);label(c,store.sessionFor(p)==null?Lang.t("СЛЕДУЮЩЕЕ ЗАНЯТИЕ"):Lang.t("ТЕКУЩЕЕ ЗАНЯТИЕ"));c.addView(title(day.optString("name"),20));space(c,6);c.addView(text(daySummary(day),13,MUTED));}
                button(c,store.sessionFor(p)==null?Lang.t("Начать тренировку  →"):Lang.t("Продолжить тренировку  →"),true,()->start(p));
                if(store.sessionFor(p)!=null){space(c,8);c.addView(text(Engine.doneCount(store.sessionFor(p))+Lang.t(" подходов уже выполнено"),13,GREEN));}
                divider(c);weightsPanel(c,p,true);divider(c);
                actionRow(c,"arrow",Lang.t("Вся программа"),Lang.t("Расписание и упражнения"),()->open(p));link(c,Lang.t("Убрать из моих"),()->removeProgram(p));

            }
            if(plans.isEmpty()){heading(Lang.t("Пока нет программ"),Lang.t("Выбери план из каталога или создай свой."));}
            actionRow(body,"library",Lang.t("Добавить программу"),Lang.t("Перейти к каталогу и импорту"),()->{page="library";render();});return;
        }
        badge(body,Lang.t("КАТАЛОГ ПРОГРАММ"),0xFFC5ADFF);space(body,14);heading(Lang.t("Найди свой план"),Lang.t("Готовые программы и твои собственные идеи."));
        LinearLayout tools=new LinearLayout(this);body.addView(tools,new LinearLayout.LayoutParams(-1,-2));
        catalogTile(tools,"file",Lang.t("Из файла"),Lang.t("Таблица или полученный план"),()->pick(40));catalogTile(tools,"library",Lang.t("Свой план"),Lang.t("Собери по упражнениям"),()->editor(null));
        link(body,Lang.t("Скачать шаблон таблицы"),()->export("trace-template.csv",Lang.t(TEMPLATE)));space(body,18);label(body,Lang.t("ВСЕ ПРОГРАММЫ · ")+programsSorted(false).size());
        for(JSONObject p:programsSorted(false)){
            LinearLayout c=programCard(body,p,PlanCategory.label(p).toUpperCase(Lang.locale()));
            tags(c,p.optJSONArray("days").length()+Lang.t(" дней"),p.optBoolean("mine")?Lang.t("✓ В моих"):Lang.t("Добавь в мои"));space(c,8);
            actionRow(c,"arrow",Lang.t("Посмотреть план"),Lang.t("Упражнения и расписание"),()->open(p));
            link(c,Lang.t("Поделиться планом"),()->sharePlan(p));
            if(PlanManagement.canDelete(p))link(c,Lang.t("Удалить план"),()->deletePlan(p));
            if(!p.optBoolean("mine"))button(c,Lang.t("Добавить в мои"),false,()->{Engine.put(p,"mine",true);Engine.put(p,"lastUsed",System.currentTimeMillis());store.save();render();});
        }
    }
    void catalogTile(LinearLayout parent,String icon,String name,String subtitle,Runnable click){LinearLayout c=column();c.setPadding(dp(14),dp(18),dp(14),dp(18));GradientDrawable bg=shape(0xFF2C2440,20);bg.setStroke(dp(1),0xFF55446F);c.setBackground(bg);largeIcon(c,icon,0xFFC5ADFF);space(c,16);c.addView(title(name,18));space(c,8);c.addView(text(subtitle,13,MUTED));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);if(parent.getChildCount()>0)lp.leftMargin=dp(12);parent.addView(c,lp);clickable(c,click);}

    void open(JSONObject p){selected=p.optString("id");page="program";render();}

    void programView(){
        JSONObject p=store.program(selected);if(p==null){page="mine";programs(true);return;}
        LinearLayout overview=programCard(body,p,Lang.t("ПРОГРАММА · ")+p.optJSONArray("days").length()+Lang.t(" ЗАНЯТИЙ"));
        link(overview,Lang.t("Изменить категорию"),()->category(p));
        link(overview,Lang.t("Изменить обложку"),()->coverOptions(p));
        link(overview,Lang.t("Поделиться планом"),()->sharePlan(p));
        if(!p.optString("description").isEmpty())hint(overview,Lang.t("О программе"),p.optString("description"));weightsPanel(overview,p,true);

        if(p.optBoolean("mine")&&p.optInt("nextDay")<p.optJSONArray("days").length())button(body,store.sessionFor(p)==null?Lang.t("Начать следующий день  →"):Lang.t("Продолжить эту программу  →"),true,()->start(p));
        if(!p.optBoolean("mine"))button(body,Lang.t("Добавить в мои"),true,()->{Engine.put(p,"mine",true);Engine.put(p,"lastUsed",System.currentTimeMillis());store.save();render();});
        space(body,24);label(body,Lang.t("Расписание программы"));JSONArray days=p.optJSONArray("days");
        for(int d=0;d<days.length();d++){
            final int di=d;JSONObject day=days.optJSONObject(d);if(!day.optString("phase").isEmpty()&&(d==0||!day.optString("phase").equals(days.optJSONObject(d-1).optString("phase")))){space(body,12);label(body,Lang.content(day.optString("phase")));space(body,10);}boolean next=d==p.optInt("nextDay"),done=d<p.optInt("nextDay");LinearLayout c=card(body);c.setPadding(dp(16),dp(16),dp(16),dp(16));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);
            TextView number=title(done?"✓":String.format(Locale.ROOT,"%02d",d+1),18);number.setGravity(Gravity.CENTER);number.setTextColor(next?BG:done?GREEN:MUTED);number.setBackground(shape(next?GREEN:LINE,14));row.addView(number,new LinearLayout.LayoutParams(dp(46),dp(46)));
            LinearLayout content=column();content.setPadding(dp(14),0,0,0);content.addView(title(day.optString("name"),17));content.addView(text(done?Lang.t("Завершено"):next?Lang.t("Следующая тренировка"):Lang.t("Запланировано"),13,next?GREEN:MUTED));row.addView(content,new LinearLayout.LayoutParams(0,-2,1));TextView arrow=text("›",28,MUTED);row.addView(arrow);c.addView(row);space(c,12);c.addView(text(daySummary(day),13,MUTED));clickable(c,()->dayDialog(p,di));
        }
        if(!p.optString("terminalNote").isEmpty()){LinearLayout event=card(body);event.addView(text(p.optString("terminalNote"),15,BLUE));}
        LinearLayout tools=card(body);label(tools,Lang.t("УПРАВЛЕНИЕ ПРОГРАММОЙ"));actionRow(tools,"library",Lang.t("Добавить день"),Lang.t("Расширить тренировочный план"),()->addDay(p));actionRow(tools,"export",Lang.t("Экспортировать программу"),Lang.t("Сохранить план в JSON"),()->export("trace-program.json",p.toString()));
        if(p.optInt("nextDay")>0)link(body,Lang.t("Создать копию для нового цикла"),()->repeat(p));
        if(p.optBoolean("mine"))link(body,Lang.t("Убрать из моих"),()->removeProgram(p));
        if(PlanManagement.canDelete(p))link(body,Lang.t("Удалить план"),()->deletePlan(p));
    }

    void deletePlan(JSONObject p){new AlertDialog.Builder(this).setTitle(Lang.t("Удалить план?"))
        .setMessage(p.optString("name")+"\n\n"+Lang.t("План исчезнет из «Планов» и «Моих планов». Незавершённое занятие будет удалено. История завершённых тренировок останется."))
        .setNegativeButton(Lang.t("Отмена"),null).setPositiveButton(Lang.t("Удалить"),(d,w)->{DeletedItems.plan(store.data,p);store.save();Notices.update(this);selected="";page="library";render();}).show();}
    void category(JSONObject p){String[] labels=new String[PlanCategory.LABELS.length];for(int i=0;i<labels.length;i++)labels[i]=Lang.t(PlanCategory.LABELS[i]);
        new AlertDialog.Builder(this).setTitle(Lang.t("Категория плана")).setSingleChoiceItems(labels,PlanCategory.index(p),(dialog,index)->{dialog.dismiss();if(index==6){LinearLayout box=form();EditText name=input(box,Lang.t("Название категории"),p.optString("categoryName"),false);formDialog(Lang.t("Своя категория"),box,Lang.t("Сохранить"),()->{PlanCategory.set(p,index,name.getText().toString());store.save();render();});}else{PlanCategory.set(p,index,"");store.save();render();}}).setNegativeButton(Lang.t("Отмена"),null).show();
    }
    void sharePlan(JSONObject p){try{startActivity(Intent.createChooser(PlanShare.intent(this,p),Lang.t("Поделиться планом")));}catch(Exception e){error(e);}}
    void coverOptions(JSONObject p){
        String[] options=p.optString("coverImage").isEmpty()?new String[]{Lang.t("Выбрать фото или скриншот")}:new String[]{Lang.t("Выбрать фото или скриншот"),Lang.t("Настроить обложку"),Lang.t("Вернуть стандартную обложку")};
        new AlertDialog.Builder(this).setTitle(Lang.t("Обложка плана")).setItems(options,(d,which)->{
            if(which==1){CoverEditor.show(this,p,p.optString("coverImage"),true);return;}
            if(which==2){p.remove("coverImage");p.remove("coverX");p.remove("coverY");p.remove("coverZoom");store.save();render();return;}
            coverTarget=p.optString("id");
            Intent picker=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);
            startActivityForResult(picker,44);
        }).show();
    }

    void removeProgram(JSONObject p){new AlertDialog.Builder(this).setTitle(Lang.t("Убрать программу из моих?"))
        .setMessage(p.optString("name")+Lang.t("\n\nИстория и рабочие веса сохранятся. Незавершённое занятие останется на паузе. Программу можно снова добавить из «Планов»."))
        .setNegativeButton(Lang.t("Оставить"),null).setPositiveButton(Lang.t("Убрать"),(d,w)->{store.removeFromMine(p);Notices.update(this);page="mine";render();Toast.makeText(this,Lang.t("Программа убрана из моих"),Toast.LENGTH_SHORT).show();}).show();}

    void progressPage(){
        java.time.LocalDate today=java.time.LocalDate.now();ProgressData data=new ProgressData(store.data.optJSONArray("history"),today,java.time.ZoneId.systemDefault());
        badge(body,Lang.t("ТВОЯ АКТИВНОСТЬ"),GREEN);space(body,14);heading(Lang.t("Прогресс"),Lang.t("Каждая сохранённая тренировка — часть истории"));
        walkingProgress=new WalkingProgress(this);space(body,6);
        LinearLayout hero=card(body);coverBackground(hero,R.drawable.street_cover);label(hero,Lang.t("ЗА ПОСЛЕДНИЕ 30 ДНЕЙ"));TextView count=title(String.valueOf(data.last30),56);count.setTextColor(GREEN);hero.addView(count);hero.addView(text(Lang.t("сохранённых тренировок"),15,MUTED));space(hero,16);
        LinearLayout stats=new LinearLayout(this);stat(stats,String.valueOf(data.activeDays),Lang.t("активных дней"),TEXT);stat(stats,String.valueOf(data.weeklyStreak),Lang.t("недель подряд"),GREEN);hero.addView(stats);
        LinearLayout calendar=card(body);calendar.addView(title(Lang.t("Календарь активности"),20));space(calendar,6);calendar.addView(text(Lang.t("Последние 12 месяцев · листай вбок"),13,MUTED));space(calendar,18);
        LinearLayout calendarRow=new LinearLayout(this);LinearLayout weekdays=column();space(weekdays,22);String[] dayNames={Lang.t("Пн"),Lang.t("Вт"),Lang.t("Ср"),Lang.t("Чт"),Lang.t("Пт"),Lang.t("Сб"),Lang.t("Вс")};for(String dayName:dayNames){TextView dayLabel=text(dayName,10,MUTED);dayLabel.setGravity(Gravity.CENTER_VERTICAL);weekdays.addView(dayLabel,new LinearLayout.LayoutParams(dp(25),dp(30)));}calendarRow.addView(weekdays);HorizontalScrollView scroll=new HorizontalScrollView(this);scroll.setHorizontalScrollBarEnabled(false);LinearLayout grid=new LinearLayout(this);scroll.addView(grid);calendarRow.addView(scroll,new LinearLayout.LayoutParams(0,-2,1));calendar.addView(calendarRow);
        java.time.LocalDate start=today.minusWeeks(52).with(java.time.temporal.TemporalAdjusters.previousOrSame(java.time.DayOfWeek.MONDAY));
        java.time.format.DateTimeFormatter month=java.time.format.DateTimeFormatter.ofPattern("MMM",Lang.locale());
        java.time.format.DateTimeFormatter full=java.time.format.DateTimeFormatter.ofPattern("d MMMM yyyy",Lang.locale());
        int[] colors={0xFF263C35,0xFF235D47,0xFF2B8E61,0xFF45BE82,0xFF82EFBD};
        LinearLayout detail=column();detail.setPadding(0,dp(18),0,0);
        java.util.function.Consumer<java.time.LocalDate> show=day->{detail.removeAllViews();detail.addView(title(day.format(full),19));space(detail,8);if(data.count(day)==0){detail.addView(text(Lang.t("Нет сохранённых тренировок"),14,MUTED));}else{detail.addView(text(data.count(day)+Lang.t(" занятий · ")+data.sets(day)+Lang.t(" подходов"),14,GREEN));for(JSONObject session:data.days.get(day))actionRow(detail,"history",session.optString("dayName"),session.optString("programName"),()->historyDetail(session));}};
        final View[] selection={null};
        for(int week=0;week<53;week++){
            LinearLayout col=column();java.time.LocalDate monday=start.plusWeeks(week);
            TextView m=text(week==0||monday.getDayOfMonth()<=7?monday.format(month):"",10,MUTED);m.setSingleLine(true);col.addView(m,new LinearLayout.LayoutParams(dp(30),dp(22)));
            for(int weekday=0;weekday<7;weekday++){
                java.time.LocalDate date=monday.plusDays(weekday);boolean future=date.isAfter(today);FrameLayout target=new FrameLayout(this);View dot=new View(this);dot.setBackground(shape(colors[data.level(date)],5));target.addView(dot,new FrameLayout.LayoutParams(dp(22),dp(22),Gravity.CENTER));col.addView(target,new LinearLayout.LayoutParams(dp(30),dp(30)));
                if(future){target.setVisibility(View.INVISIBLE);continue;}
                target.setContentDescription(date.format(full)+": "+data.count(date)+Lang.t(" тренировок, ")+data.sets(date)+Lang.t(" подходов"));
                clickable(target,()->{if(selection[0]!=null)selection[0].setBackground(null);GradientDrawable border=shape(Color.TRANSPARENT,7);border.setStroke(dp(1),TEXT);target.setBackground(border);selection[0]=target;show.accept(date);});
                if(date.equals(today)){GradientDrawable border=shape(Color.TRANSPARENT,7);border.setStroke(dp(1),TEXT);target.setBackground(border);selection[0]=target;}
            }grid.addView(col);
        }
        scroll.post(()->scroll.fullScroll(View.FOCUS_RIGHT));space(calendar,12);LinearLayout legend=new LinearLayout(this);legend.setGravity(Gravity.CENTER_VERTICAL);legend.addView(text(Lang.t("Меньше  "),12,MUTED));for(int color:colors){View dot=new View(this);dot.setBackground(shape(color,3));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(12),dp(12));lp.rightMargin=dp(4);legend.addView(dot,lp);}legend.addView(text(Lang.t("  Больше подходов"),12,MUTED));calendar.addView(legend);calendar.addView(detail);show.accept(today);
        if(data.sessions==0){space(body,4);body.addView(text(Lang.t("Сохрани первую завершённую тренировку — здесь появится первая зелёная клетка."),15,MUTED));space(body,16);}
        LinearLayout totals=card(body);label(totals,Lang.t("ЗА ВСЁ ВРЕМЯ"));LinearLayout row=new LinearLayout(this);stat(row,String.valueOf(data.sessions),Lang.t("тренировок"),TEXT);stat(row,String.valueOf(data.sets),Lang.t("подходов"),GREEN);totals.addView(row);hint(totals,Lang.t("Как считаем активность"),Lang.t("Клетка — день сохранения занятия по времени телефона. Яркость зависит от выполненных подходов: 1–5, 6–10, 11–20, 21 и больше. Серия недель продолжается, если на прошлой неделе была тренировка: текущую неделю ещё можно заполнить. Незавершённые занятия не учитываются."));
        actionRow(body,"history",Lang.t("Вся история"),Lang.t("Открыть результаты тренировок"),()->{page="history";render();});
    }

    void start(JSONObject p){if(Zlat.is(p)&&!p.optBoolean("configured")){zlatSetup(p,()->start(p));return;}try{store.start(p);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},1);page="workout";Notices.update(this);render();}catch(Exception e){error(e);}}
    void startWalk(){
        if(!WalkService.permitted(this)){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},94);return;}
        android.location.LocationManager manager=getSystemService(android.location.LocationManager.class);
        if(manager==null||!manager.isProviderEnabled(android.location.LocationManager.GPS_PROVIDER)){new AlertDialog.Builder(this).setMessage(Lang.t("Включи геолокацию телефона, затем начни прогулку.")).setPositiveButton(Lang.t("Открыть настройки"),(d,w)->startActivity(new Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS))).setNegativeButton(Lang.t("Отмена"),null).show();return;}
        try{startForegroundService(new Intent(this,WalkService.class).setAction("start"));if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},83);}catch(Exception e){error(e);}
    }
    void enableSteps(){
        if(!Steps.available(this))return;
        if(!Steps.permitted(this)){
            if(Steps.prefs(this).getBoolean("asked",false)&&!shouldShowRequestPermissionRationale(Manifest.permission.ACTIVITY_RECOGNITION)){
                new AlertDialog.Builder(this).setMessage(Lang.t("Разреши физическую активность для подсчёта шагов в настройках Trace.")).setPositiveButton(Lang.t("Открыть настройки"),(d,w)->startActivity(new Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())))).setNegativeButton(Lang.t("Отмена"),null).show();return;
            }
            if(Build.VERSION.SDK_INT>=29){Steps.prefs(this).edit().putBoolean("asked",true).apply();requestPermissions(new String[]{Manifest.permission.ACTIVITY_RECOGNITION},82);}return;
        }
        try{Steps.enable(this);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},83);stepHandler.postDelayed(()->{if(!isFinishing()&&page.equals("steps"))render();},500);render();}catch(RuntimeException e){error(e);}
    }
    @Override public void onRequestPermissionsResult(int r,String[] ps,int[] result){super.onRequestPermissionsResult(r,ps,result);if(r==94){if(WalkService.permitted(this))startWalk();else new AlertDialog.Builder(this).setMessage(Lang.t("Для маршрута разреши точную геолокацию. Шагомер работает и без неё.")).setPositiveButton(Lang.t("Открыть настройки"),(d,w)->startActivity(new Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())))).setNegativeButton(Lang.t("Отмена"),null).show();}if(r==82){if(Steps.permitted(this))enableSteps();else Toast.makeText(this,Lang.t("Нужно разрешение на физическую активность"),Toast.LENGTH_LONG).show();}Notices.update(this);render();}
    void repeat(JSONObject p){new AlertDialog.Builder(this).setTitle(Lang.t("Новый цикл")).setMessage(Lang.t("Создать копию программы с первого дня? История прошлого цикла останется.")).setPositiveButton(Lang.t("Создать"),(d,w)->{JSONObject q=Engine.copy(p);Engine.put(q,"id",Engine.id());Engine.put(q,"name",p.optString("name")+Lang.t(" · новый цикл"));Engine.put(q,"nextDay",0);if(Zlat.is(q)&&q.optJSONObject("workingWeights")!=null)Zlat.configure(q,q.optJSONObject("workingWeights").optDouble("pullup"),q.optJSONObject("workingWeights").optDouble("dip"),q.optInt("zlatSets",3));Engine.put(q,"mine",true);Engine.put(q,"lastUsed",System.currentTimeMillis());store.data.optJSONArray("programs").put(q);store.save();open(q);}).setNegativeButton(Lang.t("Отмена"),null).show();}
    void act(String action){JSONObject s=store.active();if(s==null)return;if(action.equals("finish")&&Zlat.is(store.program(s.optString("programId")))&&s.optInt("confirmedRevision",-1)!=s.optInt("revision")){zlatFinish(s);return;}boolean changed=store.action(s.optString("id"),s.optInt("revision"),action);Notices.update(this);if(store.active()==null)page="history";render();if(changed&&action.equals("undo"))Toast.makeText(this,Lang.t("Отметка снята. Подход снова доступен."),Toast.LENGTH_SHORT).show();}
    void undoControl(int count){quickActions=new LinearLayout(this);actionDock.addView(quickActions,new LinearLayout.LayoutParams(-1,dp(48)));TextView undo=text(Lang.t("↶  Отменить"),14,MUTED);undo.setGravity(Gravity.CENTER);undo.setContentDescription(Lang.t("Отменить последний подход"));clickable(undo,()->act("undo"));undo.setEnabled(count>0);undo.setAlpha(count>0?1f:.4f);quickActions.addView(undo,new LinearLayout.LayoutParams(0,-1,1));}
    boolean markSet(int index,boolean done){
        JSONObject s=store.active();if(s==null)return false;JSONObject set=s.optJSONArray("sets").optJSONObject(index);if(set==null)return false;
        if(done&&set.optDouble("kg",-1)<0){Toast.makeText(this,Lang.t("Сначала укажи вес: 0 — без отягощения"),Toast.LENGTH_SHORT).show();editSet(index);return false;}
        int y=((ScrollView)body.getParent()).getScrollY();boolean changed=store.setDone(s.optString("id"),s.optInt("revision"),index,done);
        if(changed){Notices.update(this);render();ScrollView scroll=(ScrollView)body.getParent();scroll.post(()->scroll.scrollTo(0,y));}return changed;
    }

    void workout(){
        JSONObject s=store.active();if(s==null){heading(Lang.t("Тренировка"),Lang.t("Начни занятие — здесь будут твои подходы."));ArrayList<JSONObject> mine=programsSorted(true);if(!mine.isEmpty()){JSONObject p=mine.get(0);LinearLayout c=programCard(body,p,Lang.t("ГОТОВ К ТРЕНИРОВКЕ"));space(c,10);JSONArray days=p.optJSONArray("days");int next=p.optInt("nextDay");if(next<days.length()){c.addView(text(days.optJSONObject(next).optString("name"),16,MUTED));button(c,Lang.t("Начать тренировку  →"),true,()->start(p));}else{c.addView(text(Lang.t("Все дни программы завершены"),16,MUTED));button(c,Lang.t("Начать новый цикл"),true,()->repeat(p));}}button(body,Lang.t("Выбрать программу"),false,()->{page="mine";render();});return;}
        JSONArray sets=s.optJSONArray("sets");int cursor=s.optInt("cursor");JSONObject program=store.program(s.optString("programId"));heading(s.optString("dayName"),s.optString("programName"));
        if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)link(body,Lang.t("Включить панель в уведомлениях"),()->startActivity(new Intent(android.provider.Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(android.provider.Settings.EXTRA_APP_PACKAGE,getPackageName())));
        LinearLayout sessionStatus=new LinearLayout(this);sessionStatus.setGravity(Gravity.CENTER_VERTICAL);sessionStatus.setPadding(dp(12),dp(8),dp(16),dp(8));sessionStatus.setBackground(shape(0xFF182C29,20));sessionStatus.addView(new WorkoutRing(this,Engine.doneCount(s),sets.length()),new LinearLayout.LayoutParams(dp(72),dp(72)));LinearLayout summary=column();summary.setPadding(dp(14),0,0,0);summary.addView(title(Engine.doneCount(s)+Lang.t(" из ")+sets.length()+Lang.t(" подходов"),20));space(summary,5);summary.addView(text(cursor>=sets.length()?Lang.t("Готово к сохранению"):s.optBoolean("paused")?Lang.t("Тренировка на паузе"):Lang.t("Двигайся в своём темпе"),13,MUTED));sessionStatus.addView(summary,new LinearLayout.LayoutParams(0,-2,1));body.addView(sessionStatus);space(body,16);
        LinearLayout hero=card(body);planBackground(hero,program);

        if(cursor>=sets.length()){badge(hero,Lang.t("ТРЕНИРОВКА ВЫПОЛНЕНА"),GREEN);space(hero,16);hero.addView(title(Lang.t("Отличная работа."),28));space(hero,10);hero.addView(text(Lang.t("Все подходы готовы. Осталось сохранить результат."),16,MUTED));button(actionDock,Lang.t("Сохранить тренировку  ✓"),true,()->act("finish"));undoControl(Engine.doneCount(s));}
        if(cursor<sets.length()){
        JSONObject current=sets.optJSONObject(cursor);boolean paused=s.optBoolean("paused");badge(hero,paused?Lang.t("ПАУЗА"):Lang.t("ТЕКУЩИЙ ПОДХОД"),GREEN);space(hero,14);hero.addView(title(current.optString("exercise"),28));space(hero,4);hero.addView(text(Lang.t("Подход ")+current.optInt("ordinal")+" / "+current.optInt("sets"),14,MUTED));space(hero,14);
        double kg=current.optDouble("kg",-1);LinearLayout numbers=new LinearLayout(this);metricTile(numbers,Lang.t("РАБОЧИЙ ВЕС"),kg<0?"—":Engine.number(kg),Lang.t("кг"),TEXT);metricTile(numbers,Lang.t("ПОВТОРЕНИЯ"),String.valueOf(current.optInt("reps")),Lang.t("раз"),GREEN);hero.addView(numbers);clickable(numbers,()->editSet(cursor));numbers.setContentDescription(Lang.t("Изменить вес и повторения текущего подхода"));
        space(hero,16);HorizontalScrollView steps=new HorizontalScrollView(this);steps.setHorizontalScrollBarEnabled(false);LinearLayout markers=new LinearLayout(this);steps.addView(markers);for(int n=0;n<sets.length();n++){JSONObject item=sets.optJSONObject(n);if(item.optInt("group")!=current.optInt("group"))continue;boolean checked=item.optBoolean("done"),active=n==cursor;TextView mark=text(checked?"✓":String.valueOf(item.optInt("ordinal")),13,checked||active?BG:TEXT);mark.setGravity(Gravity.CENTER);mark.setBackground(shape(checked?GREEN:active?0xFFE1FFF5:0xC0283937,10));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(34),dp(34));lp.rightMargin=dp(6);markers.addView(mark,lp);}hero.addView(steps);

        if(current.has("factor")&&!current.optBoolean("manualWeight")&&program!=null){space(hero,12);hero.addView(text(Engine.number(current.optDouble("factor")*100)+Lang.t("% от максимума · ")+Engine.number(program.optJSONObject("maxima").optDouble(current.optString("lift")))+Lang.t(" кг"),13,BLUE));}
        else if(current.optBoolean("manualWeight")){space(hero,12);hero.addView(text(Lang.t("Вес изменён вручную для этого подхода"),13,BLUE));}
        link(hero,Lang.t("Вес и повторы  ›"),()->editSet(cursor));if(Zlat.is(program))badge(hero,Lang.t("ЦЕЛЬ  5–8 ПОВТОРОВ"),GREEN);
        if(program!=null&&program.optJSONObject("maxima").length()>0)link(body,Lang.t("Изменить максимумы всей программы"),()->maxima(program));
        if(paused)button(actionDock,Lang.t("Продолжить тренировку"),true,()->act("pause"));else button(actionDock,kg<0?Lang.t("Указать вес"):Lang.t("✓  Подход выполнен"),true,()->{if(kg<0)editSet(cursor);else act("next");});
        undoControl(Engine.doneCount(s));if(!paused){TextView pause=text(Lang.english()?"Pause":Lang.t("Пауза"),14,MUTED);pause.setGravity(Gravity.CENTER);clickable(pause,()->act("pause"));quickActions.addView(pause,new LinearLayout.LayoutParams(0,-1,1));}
        }
        if(cursor<sets.length()){int next=cursor+1;while(next<sets.length()&&sets.optJSONObject(next).optBoolean("done"))next++;if(next<sets.length()){JSONObject upcoming=sets.optJSONObject(next);LinearLayout teaser=card(body);teaser.setBackground(shape(0xFF202C3E,18));label(teaser,Lang.t("ДАЛЕЕ"));teaser.addView(title(upcoming.optString("exercise"),18));space(teaser,8);double weight=upcoming.optDouble("kg",-1);teaser.addView(text((weight<0?Lang.t("Укажи вес"):Engine.number(weight)+Lang.t(" кг"))+" × "+upcoming.optInt("reps")+Lang.t("  ·  подход ")+upcoming.optInt("ordinal"),14,BLUE));}}
        space(body,10);label(body,Lang.t("МАРШРУТ ТРЕНИРОВКИ"));String previous="";LinearLayout exerciseCard=null;
        for(int i=0;i<sets.length();i++){
            final int index=i;JSONObject set=sets.optJSONObject(i);String name=Lang.content(set.optString("exercise"));
            if(!name.equals(previous)){exerciseCard=card(body);LinearLayout exerciseHeader=new LinearLayout(this);exerciseHeader.setGravity(Gravity.CENTER_VERTICAL);ImageView exerciseIcon=new ImageView(this);exerciseIcon.setImageDrawable(new LineIcon("mine",GREEN));exerciseIcon.setPadding(dp(8),dp(8),dp(8),dp(8));exerciseIcon.setBackground(shape(0xFF26413A,12));exerciseHeader.addView(exerciseIcon,new LinearLayout.LayoutParams(dp(40),dp(40)));TextView exerciseName=title(name,18);exerciseName.setPadding(dp(12),0,0,0);exerciseHeader.addView(exerciseName,new LinearLayout.LayoutParams(0,-2,1));exerciseCard.addView(exerciseHeader);space(exerciseCard,10);previous=name;}
            LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),dp(10),dp(10),dp(10));if(i==cursor)row.setBackground(shape(0xFF243D40,12));
            boolean done=set.optBoolean("done");CheckBox check=new CheckBox(this);check.setButtonTintList(android.content.res.ColorStateList.valueOf(done?GREEN:MUTED));check.setChecked(done);check.setMinWidth(0);check.setPadding(0,0,0,0);check.setContentDescription(Lang.t("Подход ")+(index+1)+": "+name);row.addView(check,new LinearLayout.LayoutParams(dp(48),dp(48)));check.setOnCheckedChangeListener((view,checked)->{if(!markSet(index,checked)){check.setOnCheckedChangeListener(null);check.setChecked(set.optBoolean("done"));}});
            double w=set.optDouble("kg",-1);LinearLayout details=column();details.addView(text((w<0?Lang.t("Указать вес"):Engine.number(w)+Lang.t(" кг"))+" × "+set.optInt("reps"),16,done?MUTED:TEXT));details.addView(text(Lang.t("Подход ")+set.optInt("ordinal")+"/"+set.optInt("sets")+(done?Lang.t(" · выполнен"):""),12,MUTED));row.addView(details,new LinearLayout.LayoutParams(0,-2,1));clickable(details,()->editSet(index));TextView note=text(Lang.t("Изменить"),12,BLUE);note.setGravity(Gravity.CENTER);note.setMinHeight(dp(48));clickable(note,()->editSet(index));row.addView(note);exerciseCard.addView(row);
        }
        actionRow(body,"mine",Lang.t("Другая программа"),Lang.t("Текущая сохранится на паузе"),()->{page="mine";render();});hint(body,Lang.t("Как отмечать подходы"),Lang.t("Нажми на галочку любого подхода, чтобы отметить или отменить его. Нажми на вес, чтобы записать фактический результат."));link(body,Lang.t("Отменить занятие без сохранения"),()->new AlertDialog.Builder(this).setTitle(Lang.t("Отменить тренировку?")).setMessage(Lang.t("Отметки текущего занятия будут удалены. Этот день можно начать заново.")).setNegativeButton(Lang.t("Оставить"),null).setPositiveButton(Lang.t("Отменить занятие"),(dialog,which)->{store.data.remove("active");store.save();Notices.update(this);page="mine";render();}).show());
    }


    EditText input(LinearLayout box,String caption,String value,boolean numeric){box.addView(text(caption,14,MUTED));space(box,8);EditText e=new EditText(this);e.setTextColor(TEXT);e.setTextSize(20);e.setSingleLine(true);e.setSelectAllOnFocus(true);e.setText(value);e.setPadding(dp(14),dp(12),dp(14),dp(12));android.content.res.ColorStateList stroke=new android.content.res.ColorStateList(new int[][]{new int[]{android.R.attr.state_focused},new int[]{}},new int[]{GREEN,LINE});GradientDrawable field=shape(BG,14);field.setStroke(dp(1),stroke);e.setBackground(field);if(numeric)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);box.addView(e,new LinearLayout.LayoutParams(-1,dp(58)));space(box,18);return e;}
    LinearLayout form(){LinearLayout f=column();f.setPadding(dp(24),dp(16),dp(24),dp(8));return f;}
    AlertDialog formDialog(String name,LinearLayout box,String action,Runnable save){return panel(name,box,action,save,true);}
    AlertDialog panel(String name,LinearLayout box,String action,Runnable save,boolean cancel){
        LinearLayout shell=column();shell.setPadding(0,dp(12),0,dp(16));shell.setBackground(shape(CARD,28));
        View handle=new View(this);handle.setBackground(shape(LINE,3));LinearLayout.LayoutParams grip=new LinearLayout.LayoutParams(dp(36),dp(4));grip.gravity=Gravity.CENTER_HORIZONTAL;grip.bottomMargin=dp(20);shell.addView(handle,grip);
        TextView header=title(name,24);header.setPadding(dp(24),0,dp(24),dp(8));shell.addView(header);
        ScrollView scroll=new ScrollView(this){@Override protected void onMeasure(int w,int h){int limit=(int)(getResources().getDisplayMetrics().heightPixels*.53);super.onMeasure(w,MeasureSpec.makeMeasureSpec(Math.min(MeasureSpec.getSize(h),limit),MeasureSpec.AT_MOST));}};
        scroll.setVerticalScrollBarEnabled(false);scroll.setClipToPadding(false);scroll.addView(box);shell.addView(scroll,new LinearLayout.LayoutParams(-1,-2,1));
        LinearLayout footer=column();footer.setPadding(dp(24),0,dp(24),0);shell.addView(footer);AlertDialog dialog=new AlertDialog.Builder(this).setView(shell).create();
        button(footer,action,true,()->{try{save.run();dialog.dismiss();}catch(Exception e){error(e);}});
        if(cancel){TextView back=button(footer,Lang.t("Отмена"),false,dialog::dismiss);back.setBackgroundColor(Color.TRANSPARENT);back.setTextColor(MUTED);}
        dialog.setOnShowListener(d->{Window window=dialog.getWindow();if(window!=null){window.setBackgroundDrawableResource(android.R.color.transparent);window.setLayout(getResources().getDisplayMetrics().widthPixels-dp(24),-2);window.setGravity(Gravity.BOTTOM);window.setDimAmount(.65f);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);}});dialog.show();return dialog;
    }
    void largeIcon(LinearLayout parent,String name,int color){ImageView icon=new ImageView(this);if(name.equals("trace"))icon.setImageResource(R.drawable.ic_trace);else icon.setImageDrawable(new LineIcon(name,color));icon.setPadding(dp(15),dp(15),dp(15),dp(15));icon.setBackground(shape((color&0xFFFFFF)|0x18000000,20));parent.addView(icon,new LinearLayout.LayoutParams(dp(60),dp(60)));}
    void actionRow(LinearLayout parent,String iconName,String name,String subtitle,Runnable action){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,dp(14),0,dp(14));row.setMinimumHeight(dp(72));ImageView icon=new ImageView(this);icon.setImageDrawable(new LineIcon(iconName,BLUE));icon.setPadding(dp(10),dp(10),dp(10),dp(10));icon.setBackground(shape(0xFF273449,14));row.addView(icon,new LinearLayout.LayoutParams(dp(42),dp(42)));LinearLayout content=column();content.setPadding(dp(12),0,dp(8),0);content.addView(title(name,16));space(content,5);content.addView(text(subtitle,13,MUTED));row.addView(content,new LinearLayout.LayoutParams(0,-2,1));row.addView(text("›",24,MUTED));row.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x187FE3CB),null,shape(Color.WHITE,14)));clickable(row,action);parent.addView(row,new LinearLayout.LayoutParams(-1,-2));}
    
    double positive(EditText e,boolean zero){double n=Double.parseDouble(e.getText().toString().trim().replace(',','.'));if(!Double.isFinite(n)||n<(zero?0:0.01)||n>2000)throw new IllegalArgumentException(Lang.t("Введите число ")+(zero?Lang.t("от 0"):Lang.t("больше 0"))+Lang.t(" до 2000"));return n;}
    int integer(EditText e,int max){double n=positive(e,false);if(n!=Math.rint(n)||n>max)throw new IllegalArgumentException(Lang.t("Нужно целое число от 1 до ")+max);return (int)n;}
    void editSet(int index){JSONObject session=store.active();if(session==null)return;String sessionId=session.optString("id");JSONArray sets=session.optJSONArray("sets");JSONObject set=sets.optJSONObject(index);LinearLayout box=form();EditText kg=input(box,Lang.t("Рабочий вес, кг · 0 = без отягощения"),set.optDouble("kg",-1)<0?"":Engine.number(set.optDouble("kg")),true);EditText reps=input(box,Lang.t("Повторения"),String.valueOf(set.optInt("reps")),true);CheckBox all=new CheckBox(this);all.setText(Lang.t("Остальные подходы этого блока"));all.setTextColor(TEXT);box.addView(all);
        formDialog(set.optString("exercise"),box,Lang.t("Сохранить"),()->{double w=positive(kg,true);int r=integer(reps,1000);JSONObject active=store.active();if(active==null||!active.optString("id").equals(sessionId))throw new IllegalArgumentException(Lang.t("Этот подход уже выполнен"));for(int n=index;n<sets.length();n++){JSONObject x=sets.optJSONObject(n);if(n==index||(all.isChecked()&&!x.optBoolean("done")&&x.optInt("group")==set.optInt("group"))){Engine.put(x,"kg",w);Engine.put(x,"reps",r);JSONObject plan=store.program(active.optString("programId"));if(x.has("factor")&&plan!=null)Engine.put(x,"manualWeight",Math.abs(w-Engine.weight(x,plan.optJSONObject("maxima"),plan.optDouble("step",2.5)))>.00001);}}Engine.put(active,"revision",active.optInt("revision")+1);store.save();Notices.update(this);render();});}

    void maxima(JSONObject p){if(Zlat.is(p)){zlatSetup(p,()->{});return;}
        LinearLayout box=form();box.addView(text(Lang.t("Введи максимумы, от которых строится план. Все процентные веса обновятся сразу — во всех днях и в оставшихся подходах текущего занятия."),15,MUTED));space(box,18);JSONObject max=p.optJSONObject("maxima");String[] names={Lang.t("Присед · 100%, кг"),Lang.t("Жим лёжа · 100%, кг"),Lang.t("Становая тяга · 100%, кг")};ArrayList<EditText> inputs=new ArrayList<>();ArrayList<String> keys=new ArrayList<>();
        for(int i=0;i<3;i++)if(max.has(Importer.LIFTS[i])){keys.add(Importer.LIFTS[i]);inputs.add(input(box,names[i],Engine.number(max.optDouble(Importer.LIFTS[i])),true));}
        box.addView(text(Lang.t("Выполненные подходы и вручную выбранные веса сохранятся."),13,MUTED));
        formDialog(Lang.t("Максимумы на всю программу"),box,Lang.t("Применить ко всем дням"),()->{JSONObject changed=Engine.copy(max);for(int i=0;i<keys.size();i++)Engine.put(changed,keys.get(i),positive(inputs.get(i),false));store.updateMaxima(p,changed,0);Notices.update(this);render();Toast.makeText(this,Lang.t("Веса программы обновлены"),Toast.LENGTH_SHORT).show();});
    }

    AlertDialog dayPanel;
    void dayDialog(JSONObject p,int d){JSONObject day=p.optJSONArray("days").optJSONObject(d);LinearLayout box=form();if(!day.optString("note").isEmpty()){box.addView(text(day.optString("note"),15,GREEN));space(box,12);}box.addView(text(Lang.t("Рабочие веса уже рассчитаны от твоих максимумов. Чтобы изменить вес сразу во всех днях, открой «Твои максимумы» в программе."),13,MUTED));JSONArray groups=day.optJSONArray("groups");for(int i=0;i<groups.length();i++){final int gi=i;final JSONObject g=groups.optJSONObject(i);LinearLayout c=card(box);c.addView(title(g.optString("exercise"),17));double w=Engine.weight(g,p.optJSONObject("maxima"),2.5);c.addView(text((w<0?Lang.t("Вес выбирается в зале"):Engine.number(w)+Lang.t(" кг"))+" · "+g.optInt("sets")+" × "+g.optInt("reps"),14,MUTED));link(c,Lang.t("Изменить"),()->editGroup(p,g));if(groups.length()>1)link(c,Lang.t("Удалить упражнение"),()->{DeletedItems.exercise(store.data,p,d,gi);store.save();if(dayPanel!=null)dayPanel.dismiss();render();});}button(box,Lang.t("＋ Добавить упражнение"),false,()->addGroup(p,day));dayPanel=panel(day.optString("name"),box,Lang.t("Закрыть"),()->{},false);}
    void editGroup(JSONObject p,JSONObject g){LinearLayout box=form();EditText exercise=input(box,Lang.t("Упражнение"),g.optString("exercise"),false);double w=Engine.weight(g,p.optJSONObject("maxima"),2.5);EditText kg=input(box,Lang.t("Фиксированный вес, кг (пусто = выбрать в зале)"),w<0?"":Engine.number(w),true);EditText sets=input(box,Lang.t("Подходы"),String.valueOf(g.optInt("sets")),true),reps=input(box,Lang.t("Повторения"),String.valueOf(g.optInt("reps")),true);CheckBox preserve=new CheckBox(this);preserve.setText(Lang.t("Сохранить расчёт от максимума"));preserve.setTextColor(TEXT);preserve.setChecked(g.has("factor"));if(g.has("factor")){box.addView(preserve);kg.setEnabled(false);preserve.setOnCheckedChangeListener((b,checked)->kg.setEnabled(!checked));}
        formDialog(Lang.t("Редактировать блок"),box,Lang.t("Сохранить"),()->{String name=exercise.getText().toString().trim();if(name.isEmpty())throw new IllegalArgumentException(Lang.t("Укажи название"));int sn=integer(sets,100),rn=integer(reps,1000);double weight=kg.getText().toString().trim().isEmpty()?-1:positive(kg,true);Engine.put(g,"exercise",name);Engine.put(g,"sets",sn);Engine.put(g,"reps",rn);if(!preserve.isChecked()){g.remove("factor");g.remove("lift");Engine.put(g,"kg",weight);}store.save();render();});}
    void history(){
        badge(body,Lang.t("ЖУРНАЛ РЕЗУЛЬТАТОВ"),0xFFE6C58A);space(body,14);heading(Lang.t("Твой прогресс"),Lang.t("Прошлые занятия, веса и повторения."));JSONArray h=store.data.optJSONArray("history");
        if(h.length()==0){LinearLayout c=card(body);coverBackground(c,R.drawable.strength_cover);largeIcon(c,"history",0xFFE6C58A);space(c,20);c.addView(title(Lang.t("Прогресс начинается здесь"),24));space(c,10);c.addView(text(Lang.t("Заверши первое занятие — результат появится здесь."),16,MUTED));button(c,Lang.t("К тренировке"),true,()->{page="workout";render();});return;}
        int count=0;for(int i=0;i<h.length();i++)count+=Engine.doneCount(h.optJSONObject(i));LinearLayout stats=card(body);stats.setBackground(shape(0xFF302A20,16));badge(stats,Lang.t("ИТОГО ЗА ВСЁ ВРЕМЯ"),0xFFE6C58A);space(stats,12);LinearLayout values=new LinearLayout(this);stat(values,String.valueOf(h.length()),Lang.t("тренировок"),TEXT);stat(values,String.valueOf(count),Lang.t("подходов"),GREEN);stats.addView(values);
        String month="";for(int i=h.length()-1;i>=0;i--){JSONObject session=h.optJSONObject(i);Date date=new Date(session.optLong("ended"));String m=new SimpleDateFormat("LLLL yyyy",Lang.locale()).format(date);if(!m.equals(month)){space(body,12);label(body,m.toUpperCase(Lang.locale()));month=m;}LinearLayout c=card(body);GradientDrawable paper=shape(0xFF28251F,12);paper.setStroke(dp(1),0xFF514735);c.setBackground(paper);badge(c,new SimpleDateFormat("d MMM · HH:mm",Lang.locale()).format(date),BLUE);space(c,14);c.addView(title(session.optString("dayName"),22));space(c,6);c.addView(text(session.optString("programName"),14,MUTED));space(c,16);c.addView(text("✓  "+Engine.doneCount(session)+Lang.t(" подходов выполнено"),14,GREEN));actionRow(c,"arrow",Lang.t("Посмотреть результат"),Lang.t("Упражнения, веса и повторения"),()->historyDetail(session));}
    }
    void historyDetail(JSONObject session){LinearLayout box=form();badge(box,Lang.t("ТРЕНИРОВКА СОХРАНЕНА"),GREEN);space(box,12);box.addView(text(session.optString("programName"),14,MUTED));space(box,20);JSONArray sets=session.optJSONArray("sets");String previous="";LinearLayout c=null;for(int i=0;i<sets.length();i++){JSONObject set=sets.optJSONObject(i);String name=Lang.content(set.optString("exercise"));if(!name.equals(previous)){c=card(box);c.addView(title(name,18));space(c,12);previous=name;}LinearLayout row=new LinearLayout(this);row.setPadding(0,dp(9),0,dp(9));TextView mark=text(set.optBoolean("done")?"✓":"—",16,GREEN);row.addView(mark,new LinearLayout.LayoutParams(dp(28),-2));double kg=set.optDouble("kg",-1);TextView result=text((kg<0?Lang.t("Без веса"):Engine.number(kg)+Lang.t(" кг"))+" × "+set.optInt("reps"),16,TEXT);row.addView(result,new LinearLayout.LayoutParams(0,-2,1));row.addView(text("#"+(i+1),13,MUTED));c.addView(row);}panel(Lang.content(session.optString("dayName")),box,Lang.t("Готово"),()->{},false);}
    
    static final String TEMPLATE="день;упражнение;подходы;повторения;вес\nДень 1;Присед;3;5;60\nДень 1;Жим лёжа;3;5;40\nДень 2;Становая тяга;3;5;80\n";
    void editor(JSONObject ignored){LinearLayout box=form();EditText name=input(box,Lang.t("Название программы"),Lang.t("Моя программа"),false);formDialog(Lang.t("Своя программа"),box,Lang.t("Добавить первый день"),()->{String title=name.getText().toString().trim();if(title.isEmpty())throw new IllegalArgumentException(Lang.t("Введи название программы"));JSONObject p=Importer.newProgram(title);addDay(p);});}
    void addDay(JSONObject p){LinearLayout box=form();EditText day=input(box,Lang.t("Название дня"),Lang.t("День ")+(p.optJSONArray("days").length()+1),false);EditText exercise=input(box,Lang.t("Первое упражнение"),"",false);EditText sets=input(box,Lang.t("Подходы"),"3",true);EditText reps=input(box,Lang.t("Повторения"),"5",true);EditText kg=input(box,Lang.t("Вес, кг · пусто = выбрать в зале"),"",true);formDialog(Lang.t("Новый тренировочный день"),box,Lang.t("Добавить"),()->{String dn=day.getText().toString().trim(),en=exercise.getText().toString().trim();if(dn.isEmpty()||en.isEmpty())throw new IllegalArgumentException(Lang.t("Введи название дня и упражнения"));JSONObject g=new JSONObject();Engine.put(g,"exercise",en);Engine.put(g,"sets",integer(sets,100));Engine.put(g,"reps",integer(reps,1000));Engine.put(g,"kg",kg.getText().toString().trim().isEmpty()?-1:positive(kg,true));JSONObject d=Engine.obj("{\"groups\":[]}");Engine.put(d,"name",dn);d.optJSONArray("groups").put(g);p.optJSONArray("days").put(d);if(!p.has("id")){Engine.put(p,"id",Engine.id());Engine.put(p,"mine",true);Engine.put(p,"lastUsed",System.currentTimeMillis());store.data.optJSONArray("programs").put(p);}store.save();open(p);});}
    void pick(int code){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,code);}
    void addGroup(JSONObject p,JSONObject day){LinearLayout box=form();EditText name=input(box,Lang.t("Упражнение"),"",false),sets=input(box,Lang.t("Подходы"),"3",true),reps=input(box,Lang.t("Повторения"),"5",true),kg=input(box,Lang.t("Вес, кг · пусто = выбрать в зале"),"",true);formDialog(Lang.t("Добавить упражнение"),box,Lang.t("Добавить"),()->{String n=name.getText().toString().trim();if(n.isEmpty())throw new IllegalArgumentException(Lang.t("Введи название упражнения"));JSONObject g=new JSONObject();Engine.put(g,"exercise",n);Engine.put(g,"sets",integer(sets,100));Engine.put(g,"reps",integer(reps,1000));Engine.put(g,"kg",kg.getText().toString().trim().isEmpty()?-1:positive(kg,true));day.optJSONArray("groups").put(g);store.save();render();});}
    AlertDialog importPreview;
    void preview(JSONObject p){LinearLayout box=form();EditText name=input(box,Lang.t("Название"),p.optString("name"),false);int sets=0,missing=0;StringBuilder summary=new StringBuilder();JSONArray days=p.optJSONArray("days");for(int i=0;i<days.length();i++){JSONObject d=days.optJSONObject(i);summary.append(d.optString("name")).append("\n").append(daySummary(d)).append("\n\n");JSONArray groups=d.optJSONArray("groups");for(int g=0;g<groups.length();g++){sets+=groups.optJSONObject(g).optInt("sets");if(groups.optJSONObject(g).optDouble("kg",-1)<0)missing++;}}
        box.addView(title(days.length()+Lang.t(" дней · ")+sets+Lang.t(" подходов"),19));space(box,10);if(missing>0)box.addView(text(Lang.t("В ")+missing+Lang.t(" блоках вес не указан: выберешь его перед подходом."),14,GREEN));space(box,12);for(int di=0;di<days.length();di++){JSONObject day=days.optJSONObject(di);LinearLayout c=card(box);badge(c,Lang.t("ДЕНЬ ")+(di+1),BLUE);space(c,12);c.addView(title(day.optString("name"),18));space(c,8);c.addView(text(daySummary(day),14,MUTED));}importPreview=formDialog(Lang.t("Проверка импорта"),box,Lang.t("Добавить в мои"),()->{Engine.put(p,"name",name.getText().toString().trim());Engine.validateProgram(p);Engine.put(p,"id",Engine.id());Engine.put(p,"mine",true);Engine.put(p,"nextDay",0);Engine.put(p,"lastUsed",System.currentTimeMillis());store.data.optJSONArray("programs").put(p);store.save();open(p);});}
    void export(String name,String content){exportText=content;if(!rememberExport())return;startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType(name.endsWith("csv")?"text/csv":"application/json").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,name),41);}
    void settings(){
        heading(Lang.t("Настройки"),Lang.t("Твои данные. Твои правила."));
        LinearLayout intro=card(body);photoBackground(intro,1);largeIcon(intro,"trace",GREEN);space(intro,16);intro.addView(title("Trace",28));space(intro,6);intro.addView(text(Lang.t("Твой дневник силы"),15,MUTED));space(intro,14);badge(intro,Lang.t("НА ТЕЛЕФОНЕ · БЕЗ АККАУНТА"),GREEN);
        LinearLayout languageCard=card(body);label(languageCard,Lang.t("Язык приложения"));LinearLayout choices=new LinearLayout(this);languageCard.addView(choices);String[] codes={"ru","en"},labels={"Русский","English"};for(int i=0;i<codes.length;i++){final String code=codes[i];boolean chosen=Lang.english()==code.equals("en");TextView choice=title((chosen?"✓  ":"")+labels[i],16);choice.setGravity(Gravity.CENTER);choice.setTextColor(chosen?BG:TEXT);choice.setBackground(shape(chosen?GREEN:LINE,14));clickable(choice,()->{if(Lang.english()==code.equals("en"))return;Lang.set(this,code);Notices.update(this);recreate();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(54),1);if(i>0)lp.leftMargin=dp(10);choices.addView(choice,lp);}
        label(body,Lang.t("ДАННЫЕ И РЕЗЕРВНЫЕ КОПИИ"));LinearLayout backup=card(body);actionRow(backup,"export",Lang.t("Сохранить копию"),Lang.t("Планы, обложки, история, шаги и настройки"),()->backup());long last=getSharedPreferences("trace-settings",0).getLong("lastBackupAt",0);backup.addView(text(last==0?Lang.t("Копия ещё не сохранялась"):Lang.t("Последняя копия: ")+new SimpleDateFormat("d MMM yyyy · HH:mm",Lang.locale()).format(new Date(last)),13,MUTED));divider(backup);actionRow(backup,"file",Lang.t("Восстановить из файла"),Lang.t("Загрузить ранее сохранённую копию"),()->pick(42));
        label(body,Lang.t("КАК ЭТО РАБОТАЕТ"));LinearLayout tips=card(body);actionRow(tips,"library",Lang.t("Добавление программ"),Lang.t("XLS Шейко · CSV · XLSX · JSON"),()->{LinearLayout b=form();b.addView(text(Lang.t("Можно загрузить исходную XLS-таблицу Шейко, JSON программы или CSV / XLSX по шаблону. В XLSX используется первый лист с пятью колонками."),16,MUTED));panel(Lang.t("Импорт программы"),b,Lang.t("Понятно"),()->{},false);});space(body,8);TextView version=text(Lang.t("Trace  /  ВЕРСИЯ 0.20.6"),12,MUTED);version.setGravity(Gravity.CENTER);body.addView(version);space(body,12);
    }
    
    void restore(JSONObject backup){JSONObject data=FullBackup.workouts(backup);if(data.has("savedSessions")){JSONObject saved=data.optJSONObject("savedSessions");if(saved==null)throw new IllegalArgumentException(Lang.t("Повреждены сохранённые занятия"));Iterator<String> sessions=saved.keys();while(sessions.hasNext()){String key=sessions.next();JSONObject session=saved.optJSONObject(key);validateSession(session);if(!key.equals(session.optString("programId")))throw new IllegalArgumentException(Lang.t("Повреждена связь занятия с программой"));}}JSONArray programs=data.optJSONArray("programs"),history=data.optJSONArray("history");if(programs==null||history==null)throw new IllegalArgumentException(Lang.t("Это не резервная копия Trace"));HashSet<String> ids=new HashSet<>();for(int i=0;i<programs.length();i++){JSONObject p=programs.optJSONObject(i);Engine.validateProgram(p);if(p.optString("id").isEmpty()||!ids.add(p.optString("id"))||p.optInt("nextDay")<0||p.optInt("nextDay")>p.optJSONArray("days").length())throw new IllegalArgumentException(Lang.t("Повреждена программа в копии"));}for(int i=0;i<history.length();i++)validateSession(history.optJSONObject(i));if(data.has("active")){validateSession(data.optJSONObject("active"));if(!ids.contains(data.optJSONObject("active").optString("programId")))throw new IllegalArgumentException(Lang.t("В копии отсутствует активная программа"));}new AlertDialog.Builder(this).setTitle(Lang.t("Восстановить копию?")).setMessage((backup.has("format")?Lang.t("Шаги и настройки также будут заменены. "):"")+Lang.t("Текущие данные будут заменены: ")+programs.length()+Lang.t(" программ, ")+history.length()+Lang.t(" тренировок. Сначала сохрани текущую копию, если она нужна.")).setNegativeButton(Lang.t("Отмена"),null).setPositiveButton(Lang.t("Восстановить"),(d,w)->{try{FullBackup.apply(this,store,backup,data);Notices.update(this);page="mine";recreate();}catch(Exception e){error(e);}}).show();}
    void validateSession(JSONObject s){if(s==null||s.optJSONArray("sets")==null||s.optString("id").isEmpty())throw new IllegalArgumentException(Lang.t("Повреждена тренировка в копии"));JSONArray a=s.optJSONArray("sets");if(a.length()==0||s.optInt("cursor")<0||s.optInt("cursor")>a.length())throw new IllegalArgumentException(Lang.t("Повреждён прогресс"));for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null||x.optString("exercise").isEmpty()||x.optInt("reps")<1||x.optInt("sets")<1||!Double.isFinite(x.optDouble("kg",-1))||x.optDouble("kg",-1)<-1)throw new IllegalArgumentException(Lang.t("Повреждены подходы"));}}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();if(request==44){
        final String target=coverTarget;coverTarget="";
        Toast.makeText(this,Lang.t("Читаю файл…"),Toast.LENGTH_SHORT).show();
        new Thread(()->{try{String encoded=PlanImages.read(getApplicationContext(),uri);runOnUiThread(()->{
            JSONObject p=store.program(target);if(p==null)return;
            if(!isDestroyed()&&!isFinishing())CoverEditor.show(this,p,encoded,false);
        });}catch(Exception e){runOnUiThread(()->{if(!isDestroyed())error(e);});}},"trace-cover").start();return;
    }if(request==41||request==43){try(OutputStream out=getContentResolver().openOutputStream(uri)){out.write(exportText.getBytes(StandardCharsets.UTF_8));out.flush();out.close();if(request==43){getSharedPreferences("trace-settings",0).edit().putLong("lastBackupAt",System.currentTimeMillis()).commit();render();}Toast.makeText(this,Lang.t("Файл сохранён"),Toast.LENGTH_SHORT).show();}catch(Exception e){error(e);}return;}if(request!=40&&request!=42)return;
        importFile(uri,request==42);}
    void importFile(Uri uri,boolean backupFile){
        String name=Lang.t("Импортированная программа");try(android.database.Cursor c=getContentResolver().query(uri,null,null,null,null)){if(c!=null&&c.moveToFirst())name=c.getString(c.getColumnIndexOrThrow(OpenableColumns.DISPLAY_NAME));}catch(Exception ignored){}final String filename=name;Toast.makeText(this,Lang.t("Читаю файл…"),Toast.LENGTH_SHORT).show();new Thread(()->{try(InputStream in=getContentResolver().openInputStream(uri)){byte[] bytes=backupFile?FullBackup.read(in):Importer.read(in);JSONObject imported=backupFile?Engine.obj(new String(bytes,StandardCharsets.UTF_8)):Importer.parse(bytes,filename);runOnUiThread(()->{if(isFinishing()||isDestroyed())return;try{if(backupFile)restore(imported);else preview(imported);}catch(Exception e){error(e);}});}catch(Exception e){runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())error(e);});}},"import").start();}
    boolean rememberExport(){try(OutputStream out=openFileOutput("pending-export.json",0)){out.write(exportText.getBytes(StandardCharsets.UTF_8));return true;}catch(Exception e){error(e);return false;}}
    void backup(){try{exportText=FullBackup.create(this,store.data).toString();if(exportText.getBytes(StandardCharsets.UTF_8).length>FullBackup.LIMIT)throw new IllegalArgumentException(Lang.t("Копия больше 50 МБ"));if(!rememberExport())return;startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"trace-backup.json"),43);}catch(Exception e){error(e);}}
    void receivePlan(Intent intent){
        String action=intent.getAction();if(!Intent.ACTION_VIEW.equals(action)&&!Intent.ACTION_SEND.equals(action))return;
        Uri uri=Intent.ACTION_VIEW.equals(action)?intent.getData():intent.getParcelableExtra(Intent.EXTRA_STREAM);
        intent.setAction(null);intent.setData(null);intent.removeExtra(Intent.EXTRA_STREAM);
        if(uri==null||!"content".equals(uri.getScheme()))return;
        importFile(uri,false);
    }
    void error(Exception e){new AlertDialog.Builder(this).setTitle(Lang.t("Не получилось")).setMessage(e.getMessage()==null?Lang.t("Проверь данные и попробуй ещё раз."):e.getMessage()).setPositiveButton(Lang.t("Понятно"),null).show();}
}
