package com.podhod.app;
import android.app.*;
import android.content.ClipData;
import android.view.*;
import android.widget.*;
import org.json.*;
/** Day cards and a focused exercise editor. Running workouts keep their snapshots. */
final class PlanEditor {
 final MainActivity a;final JSONObject plan;JSONObject lastValid;AlertDialog dialog;LinearLayout list;int dayIndex=-1;
 PlanEditor(MainActivity a,JSONObject plan){this.a=a;this.plan=plan;this.lastValid=Engine.copy(plan);}
 void show(){LinearLayout box=a.form();a.hint(box,Lang.t("О редакторе"),Lang.t("Изменения применяются к будущим занятиям. Текущая тренировка и история сохраняются."));list=a.column();box.addView(list);draw();dialog=a.panel(Lang.t("Редактор плана"),box,Lang.t("Закрыть"),()->a.render(),false);}
 void save(){try{Engine.validateProgram(plan);a.store.save();lastValid=Engine.copy(plan);}catch(Exception e){java.util.ArrayList<String> keys=new java.util.ArrayList<>();plan.keys().forEachRemaining(keys::add);for(String key:keys)plan.remove(key);lastValid.keys().forEachRemaining(key->Engine.put(plan,key,lastValid.opt(key)));if(dayIndex>=plan.optJSONArray("days").length())dayIndex=-1;a.error(e);}a.render();draw();}
 void draw(){list.removeAllViews();JSONArray days=plan.optJSONArray("days");
  if(dayIndex<0){a.link(list,Lang.t("Название программы"),()->rename(plan,"name",Lang.t("Название программы")));for(int i=0;i<days.length();i++){int index=i;JSONObject day=days.optJSONObject(i);LinearLayout card=a.card(list);a.actionRow(card,"library",day.optString("name"),a.daySummary(day),()->{dayIndex=index;draw();});a.link(card,Lang.t("Копировать день"),()->{PlanEditing.copyDay(plan,index,day.optString("name")+Lang.t(" · копия"));save();});}a.button(list,Lang.t("Добавить день"),true,()->{LinearLayout b=a.form();EditText name=a.input(b,Lang.t("Название дня"),Lang.t("День ")+(days.length()+1),false);a.formDialog(Lang.t("Добавить день"),b,Lang.t("Добавить"),()->{String n=name.getText().toString().trim();if(n.isEmpty())throw new IllegalArgumentException(Lang.t("Укажи название"));JSONObject day=Engine.obj("{\"groups\":[]}");Engine.put(day,"name",n);editExercise(day,null,()->{days.put(day);dayIndex=days.length()-1;save();});});});return;}
  JSONObject day=days.optJSONObject(dayIndex);a.link(list,Lang.t("← Все дни"),()->{dayIndex=-1;draw();});a.actionRow(list,"library",day.optString("name"),Lang.t("Переименовать день"),()->rename(day,"name",Lang.t("Название дня")));a.space(list,12);list.addView(a.text(Lang.t("Удерживай ⋮⋮ и перетащи упражнение. Кнопки − / + меняют число подходов."),13,a.MUTED));JSONArray groups=day.optJSONArray("groups");
  for(int i=0;i<groups.length();i++){int index=i;JSONObject group=groups.optJSONObject(i);LinearLayout card=a.card(list);LinearLayout heading=new LinearLayout(a);TextView handle=a.text("⋮⋮",26,a.MUTED);handle.setGravity(Gravity.CENTER);handle.setContentDescription(Lang.t("Переместить упражнение"));heading.addView(handle,new LinearLayout.LayoutParams(a.dp(48),a.dp(48)));TextView title=a.title(Lang.content(group.optString("exercise")),18);heading.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView menu=a.title("⋯",24);menu.setGravity(Gravity.CENTER);menu.setContentDescription(Lang.t("Действия упражнения"));heading.addView(menu,new LinearLayout.LayoutParams(a.dp(48),a.dp(48)));a.clickable(title,()->editExercise(day,group,this::save));a.clickable(menu,()->{PopupMenu popup=new PopupMenu(a,menu);popup.getMenu().add(0,0,0,Lang.t("Изменить"));popup.getMenu().add(0,1,1,Lang.t("Заметка к упражнению"));popup.getMenu().add(0,2,2,Lang.t("Копировать упражнение"));if(groups.length()>1)popup.getMenu().add(0,3,3,Lang.t("Удалить упражнение"));popup.setOnMenuItemClickListener(item->{switch(item.getItemId()){case 0:editExercise(day,group,this::save);break;case 1:ExerciseNotes.edit(a,plan,null,group.optString("exercise"),this::save);break;case 2:groups.put(Engine.copy(group));save();break;case 3:DeletedItems.exercise(a.store.data,plan,dayIndex,index);save();break;}return true;});popup.show();});card.addView(heading);
   handle.setOnLongClickListener(v->{v.startDragAndDrop(ClipData.newPlainText("exercise",String.valueOf(index)),new View.DragShadowBuilder(card),Integer.valueOf(index),0);return true;});
   card.setOnDragListener((v,event)->{switch(event.getAction()){case DragEvent.ACTION_DRAG_STARTED:return event.getLocalState() instanceof Integer;case DragEvent.ACTION_DRAG_ENTERED:v.setAlpha(.6f);return true;case DragEvent.ACTION_DRAG_EXITED:case DragEvent.ACTION_DRAG_ENDED:v.setAlpha(1);return true;case DragEvent.ACTION_DROP:v.setAlpha(1);PlanEditing.move(groups,(Integer)event.getLocalState(),index);save();return true;default:return true;}});
   double kg=Engine.weight(group,plan.optJSONObject("maxima"),plan.optDouble("step",2.5));card.addView(a.text((kg<0?Lang.t("Вес выбирается в зале"):Engine.number(kg)+Lang.t(" кг"))+" · "+group.optInt("sets")+" × "+group.optInt("reps"),15,a.MUTED));String note=ExerciseNotes.get(plan,group.optString("exercise"));if(!note.isEmpty())card.addView(a.text(note,14,a.GREEN));
   LinearLayout quick=new LinearLayout(a);control(quick,"−",Lang.t("Уменьшить подходы"),()->{PlanEditing.sets(group,-1);save();});control(quick,"+",Lang.t("Добавить подход"),()->{PlanEditing.sets(group,1);save();});control(quick,"↑",Lang.t("Переместить вверх"),()->{PlanEditing.move(groups,index,index-1);save();});control(quick,"↓",Lang.t("Переместить вниз"),()->{PlanEditing.move(groups,index,index+1);save();});card.addView(quick);

  }a.button(list,Lang.t("＋ Добавить упражнение"),true,()->editExercise(day,null,this::save));
 }
 void control(LinearLayout row,String label,String description,Runnable run){TextView button=a.title(label,22);button.setGravity(Gravity.CENTER);button.setContentDescription(description);button.setBackground(a.shape(a.LINE,12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,a.dp(48),1);lp.setMargins(a.dp(3),a.dp(8),a.dp(3),0);row.addView(button,lp);a.clickable(button,run);}
 void rename(JSONObject object,String key,String title){LinearLayout b=a.form();EditText input=a.input(b,title,object.optString(key),false);a.formDialog(title,b,Lang.t("Сохранить"),()->{String value=input.getText().toString().trim();if(value.isEmpty())throw new IllegalArgumentException(Lang.t("Укажи название"));Engine.put(object,key,value);save();});}
 void editExercise(JSONObject day,JSONObject existing,Runnable after){JSONObject g=existing==null?Engine.obj("{\"sets\":3,\"reps\":5,\"kg\":-1}"):Engine.copy(existing);LinearLayout b=a.form();EditText name=a.input(b,Lang.t("Упражнение"),g.optString("exercise"),false),sets=a.input(b,Lang.t("Подходы"),String.valueOf(g.optInt("sets")),true),reps=a.input(b,Lang.t("Повторения"),String.valueOf(g.optInt("reps")),true);double weight=Engine.weight(g,plan.optJSONObject("maxima"),plan.optDouble("step",2.5));EditText kg=a.input(b,Lang.t("Вес, кг · пусто = выбрать в зале"),weight<0?"":Engine.number(weight),true);CheckBox factor=new CheckBox(a);factor.setText(Lang.t("Сохранить расчёт от максимума"));factor.setTextColor(a.TEXT);factor.setChecked(g.has("factor"));if(g.has("factor")){b.addView(factor);kg.setEnabled(false);factor.setOnCheckedChangeListener((v,on)->kg.setEnabled(!on));}
  a.formDialog(Lang.t("Упражнение"),b,Lang.t("Сохранить"),()->{String n=name.getText().toString().trim();if(n.isEmpty())throw new IllegalArgumentException(Lang.t("Укажи название"));int sn=a.integer(sets,100),rn=a.integer(reps,1000);double w=factor.isChecked()?-1:kg.getText().toString().trim().isEmpty()?-1:a.positive(kg,true);JSONObject target=existing==null?g:existing;String oldName=target.optString("exercise");if(!oldName.equals(n)&&ExerciseNotes.get(plan,n).isEmpty()&&!ExerciseNotes.get(plan,oldName).isEmpty())ExerciseNotes.set(plan,n,ExerciseNotes.get(plan,oldName));Engine.put(target,"exercise",n);Engine.put(target,"sets",sn);Engine.put(target,"reps",rn);if(!factor.isChecked()){target.remove("factor");target.remove("lift");Engine.put(target,"kg",w);}if(existing==null)day.optJSONArray("groups").put(target);after.run();});
 }
}
