package com.podhod.app;
import android.app.*;import android.content.*;import android.widget.*;import org.json.*;
final class WalkPanel {
 final MainActivity a;final LinearLayout card,history;final WalkMap map;final TextView status,summary,duration,pace,button;String lastHistory="";
 WalkPanel(MainActivity a,LinearLayout parent){this.a=a;card=a.card(parent);card.setPadding(a.dp(14),a.dp(16),a.dp(14),a.dp(16));a.badge(card,Lang.t("НА СВЕЖЕМ ВОЗДУХЕ"),0xFFFF9868);a.space(card,10);card.addView(a.title(Lang.t("Твой маршрут"),28));status=a.text("",13,a.MUTED);card.addView(status);a.space(card,14);map=new WalkMap(a);card.addView(map,new LinearLayout.LayoutParams(-1,a.dp(330)));a.space(card,16);LinearLayout metrics=new LinearLayout(a);card.addView(metrics);summary=metric(a,metrics,Lang.t("КИЛОМЕТРЫ"));duration=metric(a,metrics,Lang.t("ВРЕМЯ"));pace=metric(a,metrics,Lang.t("МИН / КМ"));a.space(card,8);button=a.button(card,Lang.t("Начать прогулку"),true,()->{if(WalkService.running)a.startService(new Intent(a,WalkService.class).setAction("stop"));else a.startWalk();a.stepHandler.postDelayed(()->{if(a.stepsView!=null)a.stepsView.refresh();},500);});mapTools(a,card,map);a.hint(card,Lang.t("О карте и записи"),Lang.t("Средний темп рассчитан по полному времени, включая остановки. GPS записывается только во время прогулки. Карта OpenStreetMap требует интернет; маршруты сохраняются на телефоне. Без сети запись продолжается, но фон карты может быть недоступен. Лимит — 24 часа."));history=a.column();parent.addView(history);refresh();
 }
 static TextView metric(MainActivity a,LinearLayout row,String label){LinearLayout cell=a.column();cell.setPadding(a.dp(5),a.dp(8),a.dp(5),a.dp(8));row.addView(cell,new LinearLayout.LayoutParams(0,-2,1));TextView value=a.title("—",24);value.setTextColor(0xFFFFB18A);value.setMaxLines(1);value.setAutoSizeTextTypeUniformWithConfiguration(14,24,1,android.util.TypedValue.COMPLEX_UNIT_SP);cell.addView(value);a.space(cell,4);cell.addView(a.text(label,10,a.MUTED));return value;}
 static void mapTools(MainActivity a,LinearLayout box,WalkMap map){
  a.space(box,10);LinearLayout row=new LinearLayout(a);box.addView(row);TextView minus=a.text("−",24,a.GREEN),plus=a.text("+",24,a.GREEN),fit=a.text("⌖  "+Lang.t("Весь маршрут"),13,a.GREEN);
  minus.setContentDescription(Lang.t("Уменьшить карту"));plus.setContentDescription(Lang.t("Увеличить карту"));
  for(TextView b:new TextView[]{minus,plus,fit}){b.setGravity(android.view.Gravity.CENTER);b.setBackground(a.shape(a.BG,12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(b==fit?0:a.dp(48),a.dp(48),b==fit?1:0);if(row.getChildCount()>0)lp.leftMargin=a.dp(8);row.addView(b,lp);}
  a.clickable(minus,()->map.zoom(-1));a.clickable(plus,()->map.zoom(1));a.clickable(fit,()->{map.zoomOffset=0;map.panX=map.panY=0;map.invalidate();});
  TextView credit=a.text("© OpenStreetMap contributors",11,a.MUTED);credit.setMinHeight(a.dp(40));credit.setGravity(android.view.Gravity.CENTER_VERTICAL);box.addView(credit);a.clickable(credit,()->a.startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse("https://www.openstreetmap.org/copyright"))));
 }

 void refresh(){JSONObject data=Walks.data(a),active=data.optJSONObject("active");JSONArray list=data.optJSONArray("history");JSONObject shown=active!=null?active:list.optJSONObject(list.length()-1);map.route(shown);summary.setText(String.format(Lang.locale(),"%.2f",shown==null?0:shown.optDouble("meters")/1000));long minutes=shown==null?0:Math.max(0,(shown.optLong("ended",System.currentTimeMillis())-shown.optLong("started"))/60000);duration.setText(WalkVisuals.time(shown,System.currentTimeMillis()));pace.setText(WalkVisuals.pace(shown,System.currentTimeMillis()));boolean running=WalkService.running;status.setTextColor(running?a.GREEN:a.MUTED);
  status.setText(running?(active==null||active.optJSONArray("points").length()==0?Lang.t("Ищем GPS…"):System.currentTimeMillis()-active.optLong("lastFix")>120000?Lang.t("Нет свежего сигнала GPS"):Lang.t("Запись прогулки")):active!=null?Lang.t("Запись прервана. Начни новую прогулку."):shown!=null?Lang.t("Последняя прогулка"):Lang.t("Нажми начать и бери телефон с собой"));button.setText(Lang.t(running?"Завершить прогулку":"Начать прогулку"));
  String signature=list.length()+":"+(list.length()==0?"":list.optJSONObject(list.length()-1).optString("id"));if(!signature.equals(lastHistory)){lastHistory=signature;history.removeAllViews();a.space(history,18);history.addView(a.title(Lang.t("История прогулок"),23));double meters=0;for(int i=0;i<list.length();i++)meters+=list.optJSONObject(i).optDouble("meters");history.addView(a.text(list.length()+Lang.t(" прогулок · ")+String.format(Lang.locale(),"%.1f",meters/1000)+Lang.t(" км"),14,a.MUTED));a.space(history,12);if(list.length()==0){LinearLayout empty=a.card(history);empty.addView(a.text(Lang.t("Заверши прогулку — здесь появятся её маршрут, время и расстояние."),15,a.MUTED));}for(int i=list.length()-1;i>=0;i--){JSONObject walk=list.optJSONObject(i);LinearLayout item=a.card(history);String date=new java.text.SimpleDateFormat("d MMM yyyy · HH:mm",Lang.locale()).format(new java.util.Date(walk.optLong("started")));a.label(item,date);a.space(item,10);LinearLayout row=new LinearLayout(a);item.addView(row);row.addView(new WalkVisuals.Route(a,walk),new LinearLayout.LayoutParams(a.dp(96),a.dp(96)));LinearLayout info=a.column();info.setPadding(a.dp(14),0,0,0);row.addView(info,new LinearLayout.LayoutParams(0,-2,1));info.addView(a.title(String.format(Lang.locale(),"%.2f",walk.optDouble("meters")/1000)+Lang.t(" км"),26));info.addView(a.text(WalkVisuals.time(walk,System.currentTimeMillis())+" · "+WalkVisuals.pace(walk,System.currentTimeMillis())+Lang.t(" мин/км"),14,a.MUTED));if(walk.optBoolean("interrupted"))info.addView(a.text(Lang.t("Запись была прервана"),12,a.MUTED));a.link(item,Lang.t("Открыть маршрут"),()->detail(walk));a.clickable(row,()->detail(walk));}}

 }
 void detail(JSONObject walk){LinearLayout box=a.form();box.addView(a.title(new java.text.SimpleDateFormat("d MMM yyyy · HH:mm",Lang.locale()).format(new java.util.Date(walk.optLong("started"))),22));LinearLayout stats=new LinearLayout(a);box.addView(stats);metric(a,stats,Lang.t("КИЛОМЕТРЫ")).setText(String.format(Lang.locale(),"%.2f",walk.optDouble("meters")/1000));metric(a,stats,Lang.t("ВРЕМЯ")).setText(WalkVisuals.time(walk,System.currentTimeMillis()));metric(a,stats,Lang.t("МИН / КМ")).setText(WalkVisuals.pace(walk,System.currentTimeMillis()));a.space(box,12);WalkMap view=new WalkMap(a);view.route(walk);box.addView(view,new LinearLayout.LayoutParams(-1,a.dp(330)));mapTools(a,box,view);if(walk.optBoolean("interrupted"))box.addView(a.text(Lang.t("Запись была прервана"),14,a.MUTED));final AlertDialog[] detail={null};
 TextView delete=a.text(Lang.t("Удалить прогулку"),15,0xFFFFA5A5);delete.setMinHeight(a.dp(48));delete.setGravity(android.view.Gravity.CENTER_VERTICAL);box.addView(delete);
 a.clickable(delete,()->new AlertDialog.Builder(a).setTitle(Lang.t("Удалить прогулку?"))
 .setMessage(new java.text.SimpleDateFormat("d MMM yyyy · HH:mm",Lang.locale()).format(new java.util.Date(walk.optLong("started")))+"\n"+Walks.summary(walk)+"\n\n"+Lang.t("Маршрут и запись этой прогулки будут удалены. Шаги за день и другие прогулки сохранятся."))
 .setNegativeButton(Lang.t("Отмена"),null).setPositiveButton(Lang.t("Удалить"),(d,w)->{try{Walks.deleteHistory(a,walk.optString("id"));if(detail[0]!=null)detail[0].dismiss();refresh();}catch(Exception e){a.error(e);}}).show());
 detail[0]=a.panel(Lang.t("Карта прогулки"),box,Lang.t("Закрыть"),()->{},false);}
}
