package com.podhod.app;
import android.app.*;import android.content.*;import android.widget.*;import org.json.*;
final class WalkPanel {
 final MainActivity a;final LinearLayout card,history;final WalkMap map;final TextView status,summary,duration,pace,button;String lastHistory="",pendingResult="";
 WalkPanel(MainActivity a,LinearLayout parent){this.a=a;card=a.card(parent);card.setPadding(a.dp(14),a.dp(16),a.dp(14),a.dp(16));a.badge(card,Lang.t("НА СВЕЖЕМ ВОЗДУХЕ"),0xFFFF9868);a.space(card,10);card.addView(a.title(Lang.t("Твой маршрут"),28));status=a.text("",13,a.MUTED);card.addView(status);a.space(card,14);map=new WalkMap(a);mapFrame(a,card,map);a.space(card,16);LinearLayout metrics=new LinearLayout(a);card.addView(metrics);summary=metric(a,metrics,Lang.t("КИЛОМЕТРЫ"));duration=metric(a,metrics,Lang.t("ВРЕМЯ"));pace=metric(a,metrics,Lang.t("МИН / КМ"));a.space(card,8);button=a.button(card,Lang.t("Начать прогулку"),true,()->{if(WalkService.running){JSONObject active=Walks.data(a).optJSONObject("active");pendingResult=active==null?"":active.optString("id");a.startService(new Intent(a,WalkService.class).setAction("stop"));}else a.startWalk();a.stepHandler.postDelayed(()->{if(a.stepsView!=null)a.stepsView.refresh();},500);});mapTools(a,card,map);a.hint(card,Lang.t("О карте и записи"),Lang.t("Средний темп рассчитан по полному времени, включая остановки. GPS записывается только во время прогулки. Карта OpenStreetMap требует интернет; маршруты сохраняются на телефоне. Без сети запись продолжается, но фон карты может быть недоступен. Лимит — 24 часа."));history=a.column();parent.addView(history);refresh();
 }
 static TextView metric(MainActivity a,LinearLayout row,String label){LinearLayout cell=a.column();cell.setPadding(a.dp(5),a.dp(8),a.dp(5),a.dp(8));row.addView(cell,new LinearLayout.LayoutParams(0,-2,1));TextView value=a.title("—",24);value.setTextColor(0xFFFFB18A);value.setMaxLines(1);value.setAutoSizeTextTypeUniformWithConfiguration(14,24,1,android.util.TypedValue.COMPLEX_UNIT_SP);cell.addView(value);a.space(cell,4);cell.addView(a.text(label,10,a.MUTED));return value;}
 static void mapFrame(MainActivity a,LinearLayout box,WalkMap map){mapFrame(a,box,map,380);}
 static void mapFrame(MainActivity a,LinearLayout box,WalkMap map,int height){
  FrameLayout frame=new FrameLayout(a);frame.setBackground(a.shape(0xFF152432,22));frame.setClipToOutline(true);box.addView(frame,new LinearLayout.LayoutParams(-1,a.dp(height)));frame.addView(map,new FrameLayout.LayoutParams(-1,-1));
  LinearLayout controls=a.column();FrameLayout.LayoutParams dock=new FrameLayout.LayoutParams(a.dp(48),-2,android.view.Gravity.TOP|android.view.Gravity.RIGHT);dock.setMargins(a.dp(12),a.dp(12),a.dp(12),0);frame.addView(controls,dock);
  String[] icons={"+","−","⌖"},labels={Lang.t("Увеличить карту"),Lang.t("Уменьшить карту"),Lang.t("Весь маршрут")};
  for(int i=0;i<3;i++){final int action=i;TextView control=a.text(icons[i],25,0xFFF4F8FC);control.setGravity(android.view.Gravity.CENTER);control.setContentDescription(labels[i]);control.setBackground(a.shape(0xF21A2938,14));control.setElevation(a.dp(3));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,a.dp(48));lp.bottomMargin=a.dp(8);controls.addView(control,lp);a.clickable(control,()->{if(action==2)map.fit();else map.zoom(action==0?1:-1);});}
  TextView hint=a.text(Lang.english()?"Pinch to zoom · drag to explore":"Раздвигай пальцы · двигай карту",11,0xFFF4F8FC);hint.setPadding(a.dp(12),a.dp(7),a.dp(12),a.dp(7));hint.setBackground(a.shape(0xE6192938,12));FrameLayout.LayoutParams hp=new FrameLayout.LayoutParams(-2,-2,android.view.Gravity.BOTTOM|android.view.Gravity.CENTER_HORIZONTAL);hp.bottomMargin=a.dp(12);frame.addView(hint,hp);
 }
 static void mapTools(MainActivity a,LinearLayout box,WalkMap map){
  a.space(box,12);box.addView(a.text(Lang.english()?"Route speed · km/h":"Скорость на маршруте · км/ч",12,a.MUTED));a.space(box,6);
  android.view.View gradient=new android.view.View(a);android.graphics.drawable.GradientDrawable colors=new android.graphics.drawable.GradientDrawable(android.graphics.drawable.GradientDrawable.Orientation.LEFT_RIGHT,new int[]{WalkSpeed.color(0),WalkSpeed.color(6/3.6),WalkSpeed.color(12/3.6)});colors.setCornerRadius(a.dp(4));gradient.setBackground(colors);box.addView(gradient,new LinearLayout.LayoutParams(-1,a.dp(6)));a.space(box,4);
  LinearLayout scale=new LinearLayout(a);box.addView(scale);String[] labels={Lang.english()?"0 · Slower":"0 · Медленнее","6",Lang.english()?"12+ · Faster":"12+ · Быстрее"};for(int i=0;i<3;i++){TextView label=a.text(labels[i],11,a.MUTED);label.setGravity(i==0?android.view.Gravity.LEFT:i==1?android.view.Gravity.CENTER:android.view.Gravity.RIGHT);scale.addView(label,new LinearLayout.LayoutParams(0,-2,1));}
  box.addView(a.text(Lang.english()?"Smoothed GPS estimate · gray: speed unavailable":"Сглаженная оценка GPS · серый: скорость неизвестна",11,a.MUTED));
  TextView credit=a.text("© OpenStreetMap contributors",11,a.MUTED);credit.setMinHeight(a.dp(40));credit.setGravity(android.view.Gravity.CENTER_VERTICAL);box.addView(credit);a.clickable(credit,()->a.startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse("https://www.openstreetmap.org/copyright"))));
 }

 void refresh(){JSONObject data=Walks.data(a),active=data.optJSONObject("active");JSONArray list=data.optJSONArray("history");JSONObject shown=active!=null?active:list.optJSONObject(list.length()-1);map.route(shown);summary.setText(String.format(Lang.locale(),"%.2f",shown==null?0:shown.optDouble("meters")/1000));long minutes=shown==null?0:Math.max(0,(shown.optLong("ended",System.currentTimeMillis())-shown.optLong("started"))/60000);duration.setText(WalkVisuals.time(shown,System.currentTimeMillis()));pace.setText(WalkVisuals.pace(shown,System.currentTimeMillis()));boolean running=WalkService.running;status.setTextColor(running?a.GREEN:a.MUTED);
  status.setText(running?(active==null||active.optJSONArray("points").length()==0?Lang.t("Ищем GPS…"):System.currentTimeMillis()-active.optLong("lastFix")>120000?Lang.t("Нет свежего сигнала GPS"):Lang.t("Запись прогулки")):active!=null?Lang.t("Запись прервана. Начни новую прогулку."):shown!=null?Lang.t("Последняя прогулка"):Lang.t("Нажми начать и бери телефон с собой"));button.setText(Lang.t(running?"Завершить прогулку":"Начать прогулку"));
  if(!pendingResult.isEmpty()&&active==null){for(int i=0;i<list.length();i++){JSONObject done=list.optJSONObject(i);if(pendingResult.equals(done.optString("id"))){pendingResult="";a.stepHandler.post(()->detail(done));break;}}}
  String signature=list.length()+":"+(list.length()==0?"":list.optJSONObject(list.length()-1).optString("id"));if(!signature.equals(lastHistory)){lastHistory=signature;history.removeAllViews();a.space(history,18);history.addView(a.title(Lang.t("История прогулок"),23));double meters=0;for(int i=0;i<list.length();i++)meters+=list.optJSONObject(i).optDouble("meters");history.addView(a.text(list.length()+Lang.t(" прогулок · ")+String.format(Lang.locale(),"%.1f",meters/1000)+Lang.t(" км"),14,a.MUTED));a.space(history,12);if(list.length()==0){LinearLayout empty=a.card(history);empty.addView(a.text(Lang.t("Заверши прогулку — здесь появятся её маршрут, время и расстояние."),15,a.MUTED));}for(int i=list.length()-1;i>=0;i--){JSONObject walk=list.optJSONObject(i);LinearLayout item=a.card(history);String date=new java.text.SimpleDateFormat("d MMM yyyy · HH:mm",Lang.locale()).format(new java.util.Date(walk.optLong("started")));a.label(item,date);if(!walk.optString("title").isEmpty())item.addView(a.title(walk.optString("title"),20));PrivacyEye.add(a,item,"walk",walk);a.space(item,10);LinearLayout row=new LinearLayout(a);item.addView(row);row.addView(new WalkVisuals.Route(a,walk),new LinearLayout.LayoutParams(a.dp(96),a.dp(96)));LinearLayout info=a.column();info.setPadding(a.dp(14),0,0,0);row.addView(info,new LinearLayout.LayoutParams(0,-2,1));info.addView(a.title(String.format(Lang.locale(),"%.2f",walk.optDouble("meters")/1000)+Lang.t(" км"),26));info.addView(a.text(WalkVisuals.time(walk,System.currentTimeMillis())+" · "+WalkVisuals.pace(walk,System.currentTimeMillis())+Lang.t(" мин/км"),14,a.MUTED));if(walk.optBoolean("interrupted"))info.addView(a.text(Lang.t("Запись была прервана"),12,a.MUTED));a.link(item,Lang.t("Открыть маршрут"),()->detail(walk));a.clickable(row,()->detail(walk));}}

 }
 void detail(JSONObject walk){WalkSocial.result(a,walk,()->{lastHistory="";refresh();});}
}
