package com.podhod.app;
import android.app.*;
import android.view.*;
import android.widget.*;
import com.google.firebase.firestore.*;
import org.json.*;
import java.util.*;

/** Only explicitly published walks, freshly authorized by Firestore on each open. */
final class WalkFeed {
 final MainActivity a;final LinearLayout box,list;final TextView status,more,refresh;final AlertDialog dialog;final String uid;List<Entry> entries=new ArrayList<>();int cursor;boolean busy;
 static class Entry {String owner,name,connection;Map<String,Object> portrait;DocumentSnapshot doc;JSONObject payload;}
 static String s(String en,String ru){return FriendsPanel.s(en,ru);}
 static void open(MainActivity a){new WalkFeed(a);}
 WalkFeed(MainActivity a){this.a=a;uid=FriendsPanel.uid(a);box=a.form();status=a.text(s("Walks shared by your friends","Прогулки, которыми поделились друзья"),14,a.MUTED);box.addView(status);refresh=a.text(s("Refresh ↻","Обновить ↻"),14,a.GREEN);refresh.setGravity(Gravity.CENTER_VERTICAL);box.addView(refresh,new LinearLayout.LayoutParams(-1,a.dp(44)));a.clickable(refresh,this::load);list=a.column();box.addView(list);more=a.button(box,s("More walks","Ещё прогулки"),false,this::next);more.setVisibility(View.GONE);dialog=a.panel(s("Friends’ walks","Прогулки друзей"),box,s("Close","Закрыть"),()->{},false);load();}
 boolean active(){return dialog.isShowing()&&!a.isDestroyed()&&uid.equals(FriendsPanel.uid(a));}
 void busy(boolean on){busy=on;refresh.setEnabled(!on);more.setEnabled(!on);}
 void load(){if(busy)return;busy(true);status.setText(s("Loading friends’ walks…","Загружаем прогулки друзей…"));FriendsPanel.run(a,store->{List<Entry> found=new ArrayList<>();for(DocumentSnapshot c:store.connections())if("accepted".equals(c.getString("status"))){String owner=store.peer(c);Map<String,Object> portrait=store.portrait(owner);for(DocumentSnapshot doc:store.feed(owner,"walk"))if("friends".equals(doc.getString("audience"))){Entry e=new Entry();e.owner=owner;e.name=FriendsProfile.name(portrait,store.peerName(c));e.connection=c.getId();e.portrait=portrait;e.doc=doc;found.add(e);}}found.sort((x,y)->Long.compare(y.doc.getLong("updatedAt"),x.doc.getLong("updatedAt")));return found;},found->{if(!active())return;entries=found;cursor=0;list.removeAllViews();busy(false);if(entries.isEmpty()){status.setText(s("Nothing shared yet","Пока нет публикаций"));list.addView(a.text(s("Completed walks stay private until your friends choose to publish them here.","Завершённые прогулки скрыты, пока друзья не решат показать их здесь."),15,a.MUTED));more.setVisibility(View.GONE);}else next();},()->{if(!active())return;busy(false);status.setText(s("Could not refresh · try again","Не удалось обновить · попробуй снова"));});}
 void next(){if(busy||cursor>=entries.size())return;busy(true);int end=Math.min(cursor+5,entries.size());List<Entry> page=new ArrayList<>(entries.subList(cursor,end));FriendsPanel.run(a,store->{for(Entry e:page)e.payload=store.download(e.owner,e.doc.getId());return page;},loaded->{if(!active())return;for(Entry e:loaded)card(e);cursor=end;busy(false);status.setText(s("Shared with friends · newest first","Для друзей · сначала новые"));more.setVisibility(cursor<entries.size()?View.VISIBLE:View.GONE);},()->{if(!active())return;busy(false);status.setText(s("A walk may have been hidden. Refresh to try again.","Возможно, прогулку скрыли. Попробуй обновить ленту."));});}
 void card(Entry e){JSONObject walk=e.payload.optJSONObject("walk");LinearLayout card=a.card(list),author=new LinearLayout(a);author.setGravity(Gravity.CENTER_VERTICAL);card.addView(author);author.addView(FriendsProfile.avatar(a,e.portrait,e.name,42),new LinearLayout.LayoutParams(a.dp(42),a.dp(42)));LinearLayout name=a.column();name.setPadding(a.dp(12),0,0,0);author.addView(name,new LinearLayout.LayoutParams(0,-2,1));name.addView(a.title(e.name,17));name.addView(a.text(FriendsPanel.walkName(walk),12,a.MUTED));a.clickable(author,()->FriendsPanel.profile(a,e.owner,e.name,e.portrait,e.connection));a.space(card,14);
 LinearLayout hero=a.column();hero.setPadding(a.dp(14),a.dp(14),a.dp(14),a.dp(14));WalkSocial.backdrop(a,hero,walk);card.addView(hero,new LinearLayout.LayoutParams(-1,-2));hero.addView(a.title(WalkSocial.title(walk),23));if(e.payload.optBoolean("routeShared")&&walk.optJSONArray("points").length()>0)hero.addView(new WalkVisuals.Route(a,walk),new LinearLayout.LayoutParams(-1,a.dp(160)));else{a.space(hero,18);a.badge(hero,s("A MOMENT OUTSIDE","МОМЕНТ НА СВЕЖЕМ ВОЗДУХЕ"),0xFFFFB18A);a.space(hero,18);}WalkSocial.metrics(a,card,walk);
 LinearLayout actions=new LinearLayout(a);card.addView(actions);FriendsPanel.compact(a,actions,s("View walk","Посмотреть"),true,()->WalkSocial.openShared(a,e.owner,e.doc.getId()));FriendsPanel.compact(a,actions,s("Message","Написать"),false,()->FriendChat.open(a,e.connection,e.name));}
}
