package com.podhod.app;
import android.content.Context;import android.graphics.*;import android.view.*;import android.util.LruCache;import org.json.*;import java.io.*;import java.net.*;import java.util.*;import java.util.concurrent.*;
/** OSM tiles fetched only for the visible viewport, with a seven-day disk cache. */
final class WalkMap extends View {
 static final LruCache<String,Bitmap> images=new LruCache<String,Bitmap>(12*1024*1024){protected int sizeOf(String k,Bitmap b){return b.getByteCount();}};
 static final Set<String> pending=Collections.synchronizedSet(new HashSet<>());static final Map<String,Long> failed=new ConcurrentHashMap<>();static final ExecutorService pool=Executors.newFixedThreadPool(2);
 JSONArray points=new JSONArray();final Paint paint=new Paint(3);int zoomOffset;float panX,panY,lastX,lastY;boolean online=true;
 WalkMap(Context c){super(c);setBackgroundColor(0xFF18212E);setContentDescription(Lang.t("Карта прогулки"));}
 void route(JSONObject walk){points=walk==null?new JSONArray():walk.optJSONArray("points");invalidate();}
 static double y(double lat){lat=Math.max(-85.0511,Math.min(85.0511,lat));double r=Math.toRadians(lat);return (1-Math.log(Math.tan(r)+1/Math.cos(r))/Math.PI)*128;}
 void zoom(int delta){zoomOffset=Math.max(-8,Math.min(8,zoomOffset+delta));panX=panY=0;invalidate();}
 protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();if(points==null||points.length()==0){paint.setColor(0xFFADBACD);paint.setTextSize(14*getResources().getDisplayMetrics().density);paint.setTextAlign(Paint.Align.CENTER);c.drawText(Lang.t("Карта прогулки"),w/2,h/2,paint);return;}
  int n=points.length();double[] xs=new double[n],ys=new double[n];double minX=Double.MAX_VALUE,maxX=-Double.MAX_VALUE,minY=Double.MAX_VALUE,maxY=-Double.MAX_VALUE;
  for(int i=0;i<n;i++){JSONArray p=points.optJSONArray(i);double x=(p.optDouble(1)+180)/360*256;if(i>0){while(x-xs[i-1]>128)x-=256;while(x-xs[i-1]<-128)x+=256;}xs[i]=x;ys[i]=y(p.optDouble(0));minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,ys[i]);maxY=Math.max(maxY,ys[i]);}
  double fit=Math.min(Math.max(1,w-64)/Math.max(.00001,maxX-minX),Math.max(1,h-64)/Math.max(.00001,maxY-minY));int z=Math.max(1,Math.min(18,(n==1?16:(int)Math.floor(Math.log(fit)/Math.log(2)))+zoomOffset));double scale=Math.pow(2,z),left=(minX+maxX)/2*scale-w/2-panX,top=(minY+maxY)/2*scale-h/2-panY;int tiles=1<<z;
  paint.setColor(0xFF283547);paint.setStrokeWidth(1);
  for(int tx=(int)Math.floor(left/256);tx<=(int)Math.floor((left+w)/256);tx++)for(int ty=(int)Math.floor(top/256);ty<=(int)Math.floor((top+h)/256);ty++){float px=(float)(tx*256-left),py=(float)(ty*256-top);if(ty<0||ty>=tiles)continue;String key=z+"-"+Math.floorMod(tx,tiles)+"-"+ty;Bitmap bitmap=images.get(key);if(bitmap!=null)c.drawBitmap(bitmap,null,new RectF(px,py,px+256,py+256),paint);else{c.drawLine(px,py,px+256,py,paint);c.drawLine(px,py,px,py+256,paint);if(online)fetch(key,z,Math.floorMod(tx,tiles),ty);}}
  Path path=new Path();for(int i=0;i<n;i++){float x=(float)(xs[i]*scale-left),yy=(float)(ys[i]*scale-top);if(i==0||points.optJSONArray(i).optBoolean(4))path.moveTo(x,yy);else path.lineTo(x,yy);}paint.setStyle(Paint.Style.STROKE);paint.setStrokeJoin(Paint.Join.ROUND);paint.setStrokeCap(Paint.Cap.ROUND);paint.setStrokeWidth(8);paint.setColor(0xFF102927);c.drawPath(path,paint);paint.setStrokeWidth(5);paint.setColor(0xFF30C6AA);c.drawPath(path,paint);paint.setStyle(Paint.Style.FILL);paint.setColor(0xFF146D5D);c.drawCircle((float)(xs[0]*scale-left),(float)(ys[0]*scale-top),9,paint);paint.setColor(0xFFFFC88C);c.drawCircle((float)(xs[n-1]*scale-left),(float)(ys[n-1]*scale-top),9,paint);
 }
 void fetch(String key,int z,int x,int y){if(failed.getOrDefault(key,0L)>System.currentTimeMillis()||!pending.add(key))return;File folder=new File(getContext().getCacheDir(),"walk-map-tiles");pool.execute(()->{try{folder.mkdirs();File f=new File(folder,key+".png");Bitmap b=null;if(f.isFile()&&System.currentTimeMillis()-f.lastModified()<7L*86400000)b=BitmapFactory.decodeFile(f.getPath());if(b==null){HttpURLConnection connection=(HttpURLConnection)new URL("https://tile.openstreetmap.org/"+z+"/"+x+"/"+y+".png").openConnection();connection.setConnectTimeout(8000);connection.setReadTimeout(8000);connection.setRequestProperty("User-Agent","Trace/0.20.0 (https://github.com/david-daveee/Trace)");try{if(connection.getResponseCode()!=200)throw new IOException();ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(InputStream in=connection.getInputStream()){byte[] buf=new byte[8192];int size;while((size=in.read(buf))!=-1){if(bytes.size()+size>1024*1024)throw new IOException();bytes.write(buf,0,size);}}byte[] raw=bytes.toByteArray();b=BitmapFactory.decodeByteArray(raw,0,raw.length);if(b==null)throw new IOException();try(FileOutputStream out=new FileOutputStream(f)){out.write(raw);}}finally{connection.disconnect();}}images.put(key,b);postInvalidate();}catch(Exception e){failed.put(key,System.currentTimeMillis()+60000);}finally{pending.remove(key);}});}
 public boolean onTouchEvent(MotionEvent e){switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:lastX=e.getX();lastY=e.getY();getParent().requestDisallowInterceptTouchEvent(true);return true;case MotionEvent.ACTION_MOVE:panX+=e.getX()-lastX;panY+=e.getY()-lastY;lastX=e.getX();lastY=e.getY();invalidate();return true;case MotionEvent.ACTION_UP:performClick();case MotionEvent.ACTION_CANCEL:getParent().requestDisallowInterceptTouchEvent(false);return true;}return true;}
 public boolean performClick(){super.performClick();return true;}
}
