package com.podhod.app;
import android.app.*;import android.content.*;import android.widget.*;import org.json.*;
final class WalkPanel {
 final MainActivity a;final LinearLayout card,history;final WalkMap map;final TextView status,summary,duration,button;String lastHistory="";
 WalkPanel(MainActivity a,LinearLayout parent){this.a=a;card=a.card(parent);card.addView(a.title(Lang.t("Прогулка"),24));a.space(card,8);status=a.text("",14,a.MUTED);card.addView(status);a.space(card,12);map=new WalkMap(a);card.addView(map,new LinearLayout.LayoutParams(-1,a.dp(250)));mapTools(a,card,map);LinearLayout metrics=new LinearLayout(a);card.addView(metrics);LinearLayout distanceBox=a.column(),timeBox=a.column();for(LinearLayout cell:new LinearLayout[]{distanceBox,timeBox}){cell.setPadding(a.dp(14),a.dp(14),a.dp(14),a.dp(14));cell.setBackground(a.shape(a.BG,16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);if(metrics.getChildCount()>0)lp.leftMargin=a.dp(8);metrics.addView(cell,lp);}summary=a.title("",26);distanceBox.addView(summary);a.space(distanceBox,6);distanceBox.addView(a.text(Lang.t("Расстояние GPS"),12,a.MUTED));duration=a.title("",26);timeBox.addView(duration);a.space(timeBox,6);timeBox.addView(a.text(Lang.t("Время прогулки"),12,a.MUTED));button=a.button(card,Lang.t("Начать прогулку"),true,()->{if(WalkService.running){a.startService(new Intent(a,WalkService.class).setAction("stop"));}else a.startWalk();a.stepHandler.postDelayed(()->{if(a.stepsView!=null)a.stepsView.refresh();},500);});
  a.hint(card,Lang.t("О карте и записи"),Lang.t("GPS записывается только во время прогулки. Карта OpenStreetMap загружается через интернет; сервер карты получает запросы участков карты. Маршруты хранятся на телефоне и входят в полную копию. Без сети линия маршрута сохраняется, но фон карты может быть недоступен. В помещении GPS может не найти точку. Ограничение записи — 24 часа."));
  history=a.column();card.addView(history);refresh();
 }
 static void mapTools(MainActivity a,LinearLayout box,WalkMap map){
  a.space(box,10);LinearLayout row=new LinearLayout(a);box.addView(row);TextView minus=a.text("−",24,a.GREEN),plus=a.text("+",24,a.GREEN),fit=a.text("⌖  "+Lang.t("Весь маршрут"),13,a.GREEN);
  minus.setContentDescription(Lang.t("Уменьшить карту"));plus.setContentDescription(Lang.t("Увеличить карту"));
  for(TextView b:new TextView[]{minus,plus,fit}){b.setGravity(android.view.Gravity.CENTER);b.setBackground(a.shape(a.BG,12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(b==fit?0:a.dp(48),a.dp(48),b==fit?1:0);if(row.getChildCount()>0)lp.leftMargin=a.dp(8);row.addView(b,lp);}
  a.clickable(minus,()->map.zoom(-1));a.clickable(plus,()->map.zoom(1));a.clickable(fit,()->{map.zoomOffset=0;map.panX=map.panY=0;map.invalidate();});
  TextView credit=a.text("© OpenStreetMap contributors",11,a.MUTED);credit.setMinHeight(a.dp(40));credit.setGravity(android.view.Gravity.CENTER_VERTICAL);box.addView(credit);a.clickable(credit,()->a.startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse("https://www.openstreetmap.org/copyright"))));
 }

 void refresh(){JSONObject data=Walks.data(a),active=data.optJSONObject("active");JSONArray list=data.optJSONArray("history");JSONObject shown=active!=null?active:list.optJSONObject(list.length()-1);map.route(shown);summary.setText(String.format(Lang.locale(),"%.2f",shown==null?0:shown.optDouble("meters")/1000)+Lang.t(" км"));long minutes=shown==null?0:Math.max(0,(shown.optLong("ended",System.currentTimeMillis())-shown.optLong("started"))/60000);duration.setText(minutes+Lang.t(" мин"));boolean running=WalkService.running;status.setTextColor(running?a.GREEN:a.MUTED);
  status.setText(running?(active==null||active.optJSONArray("points").length()==0?Lang.t("Ищем GPS…"):System.currentTimeMillis()-active.optLong("lastFix")>120000?Lang.t("Нет свежего сигнала GPS"):Lang.t("Запись прогулки")):active!=null?Lang.t("Запись прервана. Начни новую прогулку."):shown!=null?Lang.t("Последняя прогулка"):Lang.t("Нажми начать и бери телефон с собой"));button.setText(Lang.t(running?"Завершить прогулку":"Начать прогулку"));
  String signature=list.length()+":"+(list.length()==0?"":list.optJSONObject(list.length()-1).optString("id"));if(!signature.equals(lastHistory)){lastHistory=signature;history.removeAllViews();if(list.length()>0){a.space(history,16);a.label(history,Lang.t("История прогулок"));}for(int i=list.length()-1;i>=0;i--){JSONObject walk=list.optJSONObject(i);String date=new java.text.SimpleDateFormat("d MMM · HH:mm",Lang.locale()).format(new java.util.Date(walk.optLong("started")));a.link(history,date+" · "+Walks.summary(walk),()->detail(walk));}}
 }
 void detail(JSONObject walk){LinearLayout box=a.form();box.addView(a.title(Walks.summary(walk),22));WalkMap view=new WalkMap(a);view.route(walk);box.addView(view,new LinearLayout.LayoutParams(-1,a.dp(280)));mapTools(a,box,view);if(walk.optBoolean("interrupted"))box.addView(a.text(Lang.t("Запись была прервана"),14,a.MUTED));a.panel(Lang.t("Карта прогулки"),box,Lang.t("Закрыть"),()->{},false);}
}
