package com.podhod.app;
import org.json.*;

/** Three-week advanced adaptation. Percentages initialize loads, feedback advances blocks. */
final class ZlatAdvanced {
 static final String SOURCE="https://www.scribd.com/document/654317739/The-complete-guide-to-weighted-calisthenics-1";
 static boolean is(JSONObject p){return p!=null&&"zlat-advanced-trace".equals(p.optString("routine"));}
 static void ensure(JSONObject data){JSONArray ps=data.optJSONArray("programs");for(int i=0;i<ps.length();i++)if(is(ps.optJSONObject(i)))return;ps.put(create());}
 static JSONObject create(){JSONObject p=Engine.obj("{\"id\":\"builtin-zlat-advanced\",\"routine\":\"zlat-advanced-trace\",\"name\":\"Злат · Продвинутый\",\"category\":\"streetlifting\",\"mine\":false,\"nextDay\":0,\"maxima\":{},\"days\":[]}");Engine.put(p,"source",SOURCE);Engine.put(p,"description","Трёхнедельный цикл: объём, восстановление, реализация. 9 занятий. Адаптация Trace без микроблинов; оценка тяжести перед сохранением. Максимальные попытки выбираются вручную.");
  String[] names={"1 · Пн · Сила и объём","1 · Вт · Двойные паузы","1 · Чт · Восстановление","1 · Пт · Сила и объём","1 · Вс · Двойные паузы","2 · Ср · Разгрузка","2 · Сб · Подготовка","3 · Вт · Проверка максимума","3 · Пт · Следующий цикл"};
  for(int d=0;d<9;d++){JSONObject day=Engine.obj("{\"groups\":[]}");Engine.put(day,"name","Неделя "+names[d]);for(String lift:new String[]{"dip","pullup"}){if(d==0||d==3){group(day,lift,"heavy",3,3);group(day,lift,"volume",3,4);}else if(d==1||d==4)group(day,lift,"technique",4,3);else if(d==2)group(day,lift,"recovery",2,6);else if(d==6)group(day,lift,"prep",3,1);else if(d==7){group(day,lift,"max",1,1);group(day,lift,"deload",1,3);}else group(day,lift,"deload",2,2);}p.optJSONArray("days").put(day);}return p;
 }
 static void group(JSONObject day,String lift,String block,int sets,int reps){JSONObject g=Engine.obj("{}");Engine.put(g,"exercise",lift.equals("dip")?"Брусья с весом":"Подтягивания с весом");Engine.put(g,"advancedLift",lift);Engine.put(g,"advancedBlock",block);Engine.put(g,"sets",sets);Engine.put(g,"reps",reps);Engine.put(g,"kg",-1);day.optJSONArray("groups").put(g);}
 static double round(double n){return Math.max(0,Math.min(1990,Math.floor((n+1e-8)/1.25)*1.25));}
 static double load(double max,double body,double factor){return round((max+body/2)*factor-body/2);}
 static void configure(JSONObject p,double pull,double dip,double body){if(!Double.isFinite(pull)||!Double.isFinite(dip)||!Double.isFinite(body)||pull<=0||dip<=0||pull>1900||dip>1900||body<20||body>350)throw new IllegalArgumentException(Lang.t("Проверь максимумы и массу тела"));JSONObject weights=new JSONObject();for(String lift:new String[]{"pullup","dip"}){double max=lift.equals("dip")?dip:pull;JSONObject w=new JSONObject();String[] blocks={"heavy","volume","technique","recovery","deload","prep"};double[] factors={.85,.70,lift.equals("dip")?.60:.55,.50,.80,.90};for(int b=0;b<blocks.length;b++)Engine.put(w,blocks[b],load(max,body,factors[b]));Engine.put(weights,lift,w);}Engine.put(p,"advancedWeights",weights);Engine.put(p,"bodyWeight",body);Engine.put(p,"configured",true);update(p,p.optInt("nextDay"));}
 static void update(JSONObject p,int from){JSONObject weights=p.optJSONObject("advancedWeights");if(weights==null)return;JSONArray days=p.optJSONArray("days");for(int d=from;d<days.length();d++){JSONArray gs=days.optJSONObject(d).optJSONArray("groups");for(int g=0;g<gs.length();g++){JSONObject x=gs.optJSONObject(g),w=weights.optJSONObject(x.optString("advancedLift"));if(w!=null)Engine.put(x,"kg",x.optString("advancedBlock").equals("max")?-1:w.optDouble(x.optString("advancedBlock"),-1));}}}
 static boolean confirmation(JSONObject s){JSONArray sets=s.optJSONArray("sets");for(int i=0;i<sets.length();i++){String b=sets.optJSONObject(i).optString("advancedBlock");if(b.equals("heavy")||b.equals("volume")||b.equals("technique"))return true;}return false;}
 static int minReps(JSONObject s,String lift,String block){int n=1001;JSONArray ss=s.optJSONArray("sets");for(int i=0;i<ss.length();i++){JSONObject x=ss.optJSONObject(i);if(lift.equals(x.optString("advancedLift"))&&block.equals(x.optString("advancedBlock")))n=Math.min(n,x.optInt("reps"));}return n==1001?-1:n;}
 static double minWeight(JSONObject s,String lift,String block){double n=Double.POSITIVE_INFINITY;JSONArray ss=s.optJSONArray("sets");for(int i=0;i<ss.length();i++){JSONObject x=ss.optJSONObject(i);if(lift.equals(x.optString("advancedLift"))&&block.equals(x.optString("advancedBlock")))n=Math.min(n,x.optDouble("kg",-1));}return Double.isFinite(n)?n:-1;}
 static double next(double base,int reps,String block,int effort){if((block.equals("heavy")&&reps<2)||(block.equals("technique")&&reps<3))return round(base*.95);if(block.equals("volume"))return round(base+(reps>=6?2.5:reps==5?1.25:0));if(reps<3)return round(base);return round(base+(effort==2?2.5:effort==1?1.25:0));}
 static void advance(JSONObject p,JSONObject s){if(!is(p)||s.optString("id").equals(p.optString("lastProgressedSession")))return;JSONObject ws=p.optJSONObject("advancedWeights"),ratings=s.optJSONObject("advancedEffort");if(ws==null)return;for(String lift:new String[]{"dip","pullup"}){JSONObject w=ws.optJSONObject(lift);for(String block:new String[]{"heavy","volume","technique"}){int reps=minReps(s,lift,block);double base=minWeight(s,lift,block);if(reps<0||base<0)continue;double result=next(base,reps,block,ratings==null?0:ratings.optInt(lift+"_"+block)),delta=result-w.optDouble(block);Engine.put(w,block,result);if(block.equals("heavy"))for(String derived:new String[]{"deload","prep"})Engine.put(w,derived,round(w.optDouble(derived)+delta));}}update(p,s.optInt("day")+1);Engine.put(p,"lastProgressedSession",s.optString("id"));}
 static String cue(JSONObject x){switch(x.optString("advancedBlock")){case "technique":return Lang.t("Пауза на 3 счёта в верхней и нижней точках каждого повторения.");case "max":return Lang.t("Выбери вес попытки вручную. Запиши успешный результат; не отмечай неудачную попытку выполненной.");case "volume":return Lang.t("Объёмный блок · 4–6 повторений. Прогрессия по худшему подходу.");case "heavy":return Lang.t("Тяжёлый блок · 3 подхода по 3 повторения.");default:return Lang.t("Контрольная техника, без отказа. На брусьях — пауза внизу; на турнике — полный вис перед подъёмом.");}}
}
