package com.podhod.app;
import org.json.*;
/** Separate intermediate adaptation; old routines and session snapshots are untouched. */
final class ZlatIntermediate {
 static boolean is(JSONObject p){return p!=null&&"zlat-intermediate-trace".equals(p.optString("routine"));}
 static boolean ensure(JSONObject data){JSONArray ps=data.optJSONArray("programs");for(int i=0;i<ps.length();i++)if(is(ps.optJSONObject(i)))return false;ps.put(create());return true;}
 static JSONObject create(){JSONObject p=Engine.obj("{\"id\":\"builtin-zlat-intermediate\",\"routine\":\"zlat-intermediate-trace\",\"name\":\"Злат · intermediate\",\"category\":\"streetlifting\",\"mine\":false,\"nextDay\":0,\"maxima\":{},\"days\":[]}");Engine.put(p,"source","https://www.scribd.com/document/654317739/The-complete-guide-to-weighted-calisthenics-1");Engine.put(p,"description",Lang.t("Три разных дня: объём, лёгкая техника, контрольный подход. Адаптация Trace: без прибавок 0,5 кг и без автоматических тестов 1ПМ. 12 занятий — четыре обычные недели."));
  for(int d=0;d<12;d++){int type=d%3;JSONObject day=Engine.obj("{\"groups\":[]}");Engine.put(day,"name","Неделя "+(d/3+1)+" · "+(type==0?"Объём":type==1?"Лёгкая техника":"Контрольный день"));Engine.put(day,"intermediateDay",type);
   for(String lift:new String[]{"pullup","dip"}){if(type==0){group(day,lift,"heavy",3,3);group(day,lift,"volume",3,4);}else if(type==1)group(day,lift,"light",2,5);else{group(day,lift,"test",1,4);group(day,lift,"backoff",2,4);}}p.optJSONArray("days").put(day);
  }return p;
 }
 static void group(JSONObject day,String lift,String block,int sets,int reps){JSONObject g=new JSONObject();Engine.put(g,"exercise",(lift.equals("pullup")?"Подтягивания с весом":"Брусья с весом"));Engine.put(g,"intermediateLift",lift);Engine.put(g,"intermediateBlock",block);Engine.put(g,"sets",sets);Engine.put(g,"reps",reps);Engine.put(g,"kg",-1);day.optJSONArray("groups").put(g);}
 static double round(double n){return Math.floor((n+1e-8)/1.25)*1.25;}
 static void configure(JSONObject p,double pull,double dip){if(!Double.isFinite(pull)||!Double.isFinite(dip)||pull<1.25||dip<1.25||pull>1900||dip>1900)throw new IllegalArgumentException(Lang.t("Укажи максимумы от 1,25 до 1900 кг"));JSONObject weights=new JSONObject();for(String lift:new String[]{"pullup","dip"}){double max=lift.equals("pullup")?pull:dip;JSONObject w=new JSONObject();double heavy=round(max*.8);Engine.put(w,"heavy",heavy);Engine.put(w,"volume",round(max*.65));Engine.put(w,"light",round(heavy*.7));Engine.put(weights,lift,w);}Engine.put(p,"intermediateWeights",weights);Engine.put(p,"configured",true);update(p,p.optInt("nextDay"));}
 static void update(JSONObject p,int from){JSONObject ws=p.optJSONObject("intermediateWeights");if(ws==null)return;JSONArray days=p.optJSONArray("days");for(int d=from;d<days.length();d++){JSONArray groups=days.optJSONObject(d).optJSONArray("groups");for(int i=0;i<groups.length();i++){JSONObject g=groups.optJSONObject(i),w=ws.optJSONObject(g.optString("intermediateLift"));if(w==null)continue;String block=g.optString("intermediateBlock");double value;switch(block){case "volume":value=w.optDouble("volume");break;case "light":value=w.optDouble("light");break;case "backoff":value=Math.max(0,w.optDouble("heavy")-(g.optString("intermediateLift").equals("pullup")?15:20));break;default:value=w.optDouble("heavy");}Engine.put(g,"kg",round(value));}}}
 static int reps(JSONObject s,String lift,String block){int min=Integer.MAX_VALUE;JSONArray sets=s.optJSONArray("sets");for(int i=0;i<sets.length();i++){JSONObject x=sets.optJSONObject(i);if(lift.equals(x.optString("intermediateLift"))&&block.equals(x.optString("intermediateBlock")))min=Math.min(min,x.optInt("reps"));}return min==Integer.MAX_VALUE?0:min;}
 static double weight(JSONObject s,String lift,String block){double result=Double.POSITIVE_INFINITY;JSONArray sets=s.optJSONArray("sets");for(int i=0;i<sets.length();i++){JSONObject x=sets.optJSONObject(i);if(lift.equals(x.optString("intermediateLift"))&&block.equals(x.optString("intermediateBlock")))result=Math.min(result,x.optDouble("kg",-1));}return Double.isFinite(result)?result:-1;}
 static double increment(int reps){return reps>=6?2.5:reps==5?1.25:0;}
 static boolean confirmation(JSONObject s){JSONArray sets=s.optJSONArray("sets");for(int i=0;i<sets.length();i++){String b=sets.optJSONObject(i).optString("intermediateBlock");if(b.equals("volume")||b.equals("test"))return true;}return false;}
 static void advance(JSONObject p,JSONObject s){if(!is(p)||s.optString("id").equals(p.optString("lastProgressedSession")))return;JSONObject ws=p.optJSONObject("intermediateWeights");if(ws==null)return;for(String lift:new String[]{"pullup","dip"}){JSONObject w=ws.optJSONObject(lift);if(w==null)continue;double test=weight(s,lift,"test"),volume=weight(s,lift,"volume");if(test>=0){double next=Math.min(1990,round(test+increment(reps(s,lift,"test")))),delta=next-w.optDouble("heavy");Engine.put(w,"heavy",next);Engine.put(w,"light",Math.min(1990,Math.max(0,w.optDouble("light")+delta)));}if(volume>=0)Engine.put(w,"volume",Math.min(1990,round(volume+increment(reps(s,lift,"volume")))));}update(p,s.optInt("day")+1);Engine.put(p,"lastProgressedSession",s.optString("id"));}
 static void syncBackoffs(JSONObject s){JSONArray sets=s.optJSONArray("sets");for(String lift:new String[]{"pullup","dip"}){JSONObject top=null;for(int i=0;i<sets.length();i++){JSONObject x=sets.optJSONObject(i);if(lift.equals(x.optString("intermediateLift"))&&"test".equals(x.optString("intermediateBlock")))top=x;}if(top==null||!top.optBoolean("done"))continue;for(int i=0;i<sets.length();i++){JSONObject x=sets.optJSONObject(i);if(!x.optBoolean("done")&&lift.equals(x.optString("intermediateLift"))&&"backoff".equals(x.optString("intermediateBlock")))Engine.put(x,"reps",top.optInt("reps"));}}}
 static String cue(JSONObject set){String block=set.optString("intermediateBlock");boolean pull=set.optString("intermediateLift").equals("pullup");if(block.equals("light")||block.equals("backoff"))return Lang.t(pull?"Пауза в полном висе, затем быстрый подъём. Без раскачки.":"Пауза на 3 счёта внизу каждого повторения.");if(block.equals("volume"))return Lang.t("Объёмный блок · 4–6 повторений. Прогрессия по худшему подходу.");if(block.equals("test"))return Lang.t("Контрольный подход · 4–6 повторений. Результат задаёт вес следующей недели.");return Lang.t("Тяжёлый блок · 3 подхода по 3 повторения.");}
}
