package com.podhod.app;
import org.junit.Test;import org.json.*;import static org.junit.Assert.*;
public class CommunityPlansTest {
 JSONObject plan(){JSONObject p=Zlat.create();Engine.put(p,"exerciseNotes",new JSONObject());Engine.put(p,"mine",true);Engine.put(p,"nextDay",3);Engine.put(p,"author",Engine.put(new JSONObject(),"uid","untrusted"));return p;}
 @Test public void publishedSnapshotExcludesPrivateAndAuthFields(){JSONObject p=plan(),s=CommunityPlans.snapshot(p);assertFalse(s.has("author"));assertFalse(s.has("exerciseNotes"));assertFalse(s.has("nextDay"));assertFalse(s.has("mine"));assertFalse(s.has("id"));assertTrue(p.has("author"));}
 @Test public void submittedDaysAreIndependent(){JSONObject p=plan(),s=CommunityPlans.snapshot(p);Engine.put(s.optJSONArray("days").optJSONObject(0),"name","changed");assertNotEquals("changed",p.optJSONArray("days").optJSONObject(0).optString("name"));}
 @Test public void requestsAreScopedToAuthor(){JSONObject p=plan();assertNotEquals(CommunityPlans.requestId("a",p),CommunityPlans.requestId("b",p));}
 @Test public void moderatorDraftDoesNotMutateOriginalOrProgression(){JSONObject original=ZlatIntermediate.create();ZlatIntermediate.configure(original,50,70);String before=original.toString();JSONObject draft=Engine.copy(original);Engine.put(draft,"name","Reviewed intermediate");Engine.put(draft.optJSONArray("days").optJSONObject(0).optJSONArray("groups").optJSONObject(0),"reps",4);JSONObject snapshot=CommunityPlans.snapshot(draft);assertEquals(before,original.toString());assertEquals(original.optJSONObject("intermediateWeights").toString(),snapshot.optJSONObject("intermediateWeights").toString());assertEquals(PlanPopularity.key(original),PlanPopularity.key(snapshot));assertEquals("Reviewed intermediate",snapshot.optString("name"));}
}
