package com.podhod.app;
import org.junit.Test;import org.json.*;import java.util.*;import static org.junit.Assert.*;
public class CommunityCatalogTest {
 JSONObject local(String id){JSONObject p=new JSONObject();Engine.put(p,"id",id);Engine.put(p,"name","Same title");PlanPopularity.identity(p);return p;}
 @Test public void approvedOriginalAppearsOnceAndPreservesLocalState(){JSONObject p=local("original");Engine.put(p,"mine",true);Engine.put(p,"nextDay",4);JSONObject remote=Engine.copy(p);Engine.put(remote,"id","community");Engine.put(remote,"catalogId",PlanPopularity.key(p));Engine.put(remote,"nextDay",0);List<JSONObject> result=CommunityCatalog.merge(Arrays.asList(p),Arrays.asList(remote));assertEquals(1,result.size());assertSame(p,result.get(0));assertEquals(4,p.optInt("nextDay"));assertTrue(p.optBoolean("mine"));}
 @Test public void distinctPlansWithSameTitleStaySeparate(){assertEquals(2,CommunityCatalog.merge(Arrays.asList(local("a")),Arrays.asList(local("b"))).size());}
 @Test public void importedCopyMatchesPublishedIdentity(){JSONObject p=local("source");JSONObject imported=Engine.copy(p);Engine.put(imported,"id","imported");JSONObject remote=Engine.copy(p);Engine.put(remote,"catalogId",PlanPopularity.key(p));assertSame(imported,CommunityCatalog.merge(Arrays.asList(imported),Arrays.asList(remote)).get(0));assertEquals(1,CommunityCatalog.merge(Arrays.asList(imported),Arrays.asList(remote)).size());}
 JSONObject legacy(String id){JSONObject p=local(id);Engine.put(p,"description","Подготовительный цикл · 4 недели · Б. И. Шейко");JSONArray days=new JSONArray();for(int row:new int[]{6,12,18,23,29,35,41,46,52,58,65,71,77,83,89,95}){JSONObject group=Engine.put(new JSONObject(),"sourceRow",row);days.put(Engine.put(new JSONObject(),"groups",new JSONArray().put(group)));}Engine.put(p,"days",days);return p;}
 @Test public void legacySheikoOnAnotherPhoneMatchesPublishedOwnerCopy(){JSONObject brother=legacy("brother-local-id"),owner=legacy("owner-original-id");Engine.put(brother,"nextDay",5);Engine.put(owner,"catalogId",PlanPopularity.key(owner));assertEquals(1,CommunityCatalog.merge(Arrays.asList(brother),Arrays.asList(owner)).size());assertSame(brother,CommunityCatalog.merge(Arrays.asList(brother),Arrays.asList(owner)).get(0));assertEquals(5,brother.optInt("nextDay"));}
 @Test public void freshBuiltinMatchesLegacyPublicSnapshot(){JSONObject fresh=local("fresh-random-id");Engine.put(fresh,"routine","sheiko-cms-ms");JSONObject published=legacy("old-id");Engine.put(published,"catalogId",PlanPopularity.key(published));assertEquals(1,CommunityCatalog.merge(Arrays.asList(fresh),Arrays.asList(published)).size());}
 @Test public void similarCustomPlanIsNotTreatedAsBuiltin(){JSONObject custom=legacy("custom");Engine.put(custom,"createdLocally",true);assertEquals("",PlanIdentity.routine(custom));JSONObject changed=legacy("different");Engine.put(changed.optJSONArray("days").optJSONObject(0).optJSONArray("groups").optJSONObject(0),"sourceRow",999);assertEquals("",PlanIdentity.routine(changed));}
}
