package com.podhod.app;
import org.junit.Test;import org.json.*;import static org.junit.Assert.*;
public class DeletedItemsTest {
 JSONObject fixture(){JSONObject p=Zlat.create();Engine.put(p,"id","personal");Zlat.configure(p,20,40,3);JSONObject data=Engine.obj("{\"programs\":[],\"history\":[]}");data.optJSONArray("programs").put(p);return data;}
 @Test public void undoPlanDoesNotReplaceNewActiveWorkout(){JSONObject data=fixture(),p=data.optJSONArray("programs").optJSONObject(0);Engine.selectProgram(data,p,1);String session=data.optJSONObject("active").toString();DeletedItems.plan(data,p);assertEquals(0,data.optJSONArray("programs").length());Engine.put(data,"active",Engine.obj("{\"programId\":\"another\",\"id\":\"new-session\"}"));data.optJSONArray("history").put(Engine.obj("{\"id\":\"new-history\"}"));assertTrue(DeletedItems.undo(data));assertEquals("new-session",data.optJSONObject("active").optString("id"));assertEquals(1,data.optJSONArray("history").length());assertNotNull(data.optJSONObject("savedSessions").optJSONObject("personal"));assertEquals(1,data.optJSONArray("programs").length());}
 @Test public void exerciseUndoSurvivesSerializationAndKeepsOtherEdits(){JSONObject data=fixture(),p=data.optJSONArray("programs").optJSONObject(0);String first=p.optJSONArray("days").optJSONObject(0).optJSONArray("groups").optJSONObject(0).toString();DeletedItems.exercise(data,p,0,0);Engine.put(p,"name","Changed name");data=Engine.copy(data);assertTrue(DeletedItems.undo(data));p=data.optJSONArray("programs").optJSONObject(0);assertEquals("Changed name",p.optString("name"));assertEquals(first,p.optJSONArray("days").optJSONObject(0).optJSONArray("groups").optJSONObject(0).toString());assertNull(DeletedItems.last(data));}
 @Test public void undoPlanThenEarlierExercise(){JSONObject data=fixture(),p=data.optJSONArray("programs").optJSONObject(0);DeletedItems.exercise(data,p,0,0);DeletedItems.plan(data,p);assertTrue(DeletedItems.undo(data));assertTrue(DeletedItems.undo(data));assertEquals(2,data.optJSONArray("programs").optJSONObject(0).optJSONArray("days").optJSONObject(0).optJSONArray("groups").length());}
 @Test public void lastExerciseCannotBeDeleted(){JSONObject data=fixture(),p=data.optJSONArray("programs").optJSONObject(0);DeletedItems.exercise(data,p,0,0);try{DeletedItems.exercise(data,p,0,0);fail();}catch(IllegalArgumentException expected){}assertEquals(1,p.optJSONArray("days").optJSONObject(0).optJSONArray("groups").length());}
}
