package com.podhod.app;
import org.junit.Test;import org.json.*;import static org.junit.Assert.*;
public class PlanEditingTest {
 @Test public void sessionAndSharedPlanPreserveNotes(){JSONObject p=Engine.obj("{\"id\":\"p\",\"name\":\"Plan\",\"days\":[{\"name\":\"Day\",\"groups\":[{\"exercise\":\"Bench\",\"sets\":3,\"reps\":5,\"kg\":40}]}]}");ExerciseNotes.set(p,"Bench","30 degrees");JSONObject session=Engine.start(p,1000);ExerciseNotes.set(p,"Bench","new note");assertEquals("30 degrees",ExerciseNotes.get(session,"Bench"));assertEquals("new note",ExerciseNotes.get(PlanShare.snapshot(p),"Bench"));}

 @Test public void reorderRetainsEveryExercise(){JSONArray g=Engine.obj("{\"g\":[{\"exercise\":\"A\"},{\"exercise\":\"B\"},{\"exercise\":\"C\"}]}").optJSONArray("g");PlanEditing.move(g,0,2);assertEquals("B",g.optJSONObject(0).optString("exercise"));assertEquals("A",g.optJSONObject(2).optString("exercise"));PlanEditing.move(g,2,0);assertEquals("A",g.optJSONObject(0).optString("exercise"));assertEquals(3,g.length());PlanEditing.move(g,0,-1);assertEquals("A",g.optJSONObject(0).optString("exercise"));}
 @Test public void copiedDayDoesNotShareEdits(){JSONObject p=Engine.obj("{\"nextDay\":1,\"days\":[{\"name\":\"A\",\"groups\":[{\"exercise\":\"Squat\",\"sets\":3,\"factor\":0.7}]}]}");PlanEditing.copyDay(p,0,"B");JSONObject copy=p.optJSONArray("days").optJSONObject(1).optJSONArray("groups").optJSONObject(0);PlanEditing.sets(copy,1);assertEquals(3,p.optJSONArray("days").optJSONObject(0).optJSONArray("groups").optJSONObject(0).optInt("sets"));assertEquals(.7,copy.optDouble("factor"),0);assertEquals(1,p.optInt("nextDay"));}
 @Test public void setCountStaysWithinBounds(){JSONObject g=Engine.obj("{\"sets\":1}");PlanEditing.sets(g,-1);assertEquals(1,g.optInt("sets"));Engine.put(g,"sets",100);PlanEditing.sets(g,1);assertEquals(100,g.optInt("sets"));}
 @Test public void notesPersistInJsonAndCopiesAreIndependent(){JSONObject p=new JSONObject();ExerciseNotes.set(p,"Bench","  narrow grip  ");JSONObject snapshot=Engine.copy(p);ExerciseNotes.set(p,"Bench","new");assertEquals("narrow grip",ExerciseNotes.get(snapshot,"Bench"));assertEquals("new",ExerciseNotes.get(p,"Bench"));ExerciseNotes.set(p,"Bench","");assertEquals("",ExerciseNotes.get(p,"Bench"));}
}
