package com.podhod.app;
import org.junit.Test;import org.json.*;import static org.junit.Assert.*;
public class ZlatIntermediateTest {
 JSONObject plan(){JSONObject p=ZlatIntermediate.create();ZlatIntermediate.configure(p,50,100);return p;}
 @Test public void threeDistinctDaysAndRounding(){JSONObject p=plan();Engine.validateProgram(p);JSONArray ds=p.optJSONArray("days");assertEquals(12,ds.length());assertEquals(4,ds.optJSONObject(0).optJSONArray("groups").length());assertEquals(2,ds.optJSONObject(1).optJSONArray("groups").length());assertEquals(4,ds.optJSONObject(2).optJSONArray("groups").length());assertEquals(40,ZlatIntermediate.weight(Engine.start(p,1),"pullup","heavy"),0);Engine.put(p,"nextDay",1);assertEquals(27.5,ZlatIntermediate.weight(Engine.start(p,1),"pullup","light"),0);Engine.put(p,"nextDay",2);assertEquals(25,ZlatIntermediate.weight(Engine.start(p,1),"pullup","backoff"),0);}
 @Test public void volumeAndTopProgressIndependentlyAndPreserveSnapshots(){JSONObject p=plan(),s=Engine.start(p,1);JSONArray sets=s.optJSONArray("sets");for(int i=0;i<sets.length();i++){JSONObject x=sets.optJSONObject(i);if("volume".equals(x.optString("intermediateBlock")))Engine.put(x,"reps",6);Engine.setDone(s,i,true,i);}String snapshot=s.toString();ZlatIntermediate.advance(p,s);assertEquals(snapshot,s.toString());assertEquals(35,p.optJSONObject("intermediateWeights").optJSONObject("pullup").optDouble("volume"),0);assertEquals(40,p.optJSONObject("intermediateWeights").optJSONObject("pullup").optDouble("heavy"),0);String once=p.toString();ZlatIntermediate.advance(p,s);assertEquals(once,p.toString());Engine.put(p,"nextDay",2);s=Engine.start(p,2);for(int i=0;i<s.optJSONArray("sets").length();i++){JSONObject x=s.optJSONArray("sets").optJSONObject(i);if("test".equals(x.optString("intermediateBlock")))Engine.put(x,"reps",5);Engine.setDone(s,i,true,i);}ZlatIntermediate.advance(p,s);assertEquals(41.25,p.optJSONObject("intermediateWeights").optJSONObject("pullup").optDouble("heavy"),0);assertEquals(28.75,p.optJSONObject("intermediateWeights").optJSONObject("pullup").optDouble("light"),0);assertEquals(35,p.optJSONObject("intermediateWeights").optJSONObject("pullup").optDouble("volume"),0);}
 @Test public void backoffsFollowTopRepsWithoutChangingFinishedSets(){JSONObject p=plan();Engine.put(p,"nextDay",2);JSONObject s=Engine.start(p,1);JSONObject top=s.optJSONArray("sets").optJSONObject(0);Engine.put(top,"reps",6);Engine.setDone(s,0,true,1);Engine.setDone(s,1,true,2);ZlatIntermediate.syncBackoffs(s);assertEquals(4,s.optJSONArray("sets").optJSONObject(1).optInt("reps"));assertEquals(6,s.optJSONArray("sets").optJSONObject(2).optInt("reps"));}
 @Test public void noMicroplatesAndNoProgressOnLightDay(){assertEquals(0,ZlatIntermediate.increment(4),0);assertEquals(1.25,ZlatIntermediate.increment(5),0);assertEquals(2.5,ZlatIntermediate.increment(6),0);JSONObject p=plan();Engine.put(p,"nextDay",1);JSONObject s=Engine.start(p,1);String before=p.optJSONObject("intermediateWeights").toString();assertFalse(ZlatIntermediate.confirmation(s));ZlatIntermediate.advance(p,s);assertEquals(before,p.optJSONObject("intermediateWeights").toString());}
 @Test public void catalogPreservesOldPlanAndDoesNotDuplicate(){JSONObject root=Engine.obj("{\"programs\":[]}");root.optJSONArray("programs").put(Zlat.create());String old=root.optJSONArray("programs").optJSONObject(0).toString();assertTrue(ZlatIntermediate.ensure(root));assertFalse(ZlatIntermediate.ensure(root));assertEquals(old,root.optJSONArray("programs").optJSONObject(0).toString());}
}
