package com.podhod.app;
import org.json.*;
import org.junit.Test;
import static org.junit.Assert.*;
public class ZlatAdvancedTest {
 @Test public void cycleAndBodyWeightCalculation(){JSONObject p=ZlatAdvanced.create();assertEquals(9,p.optJSONArray("days").length());ZlatAdvanced.configure(p,100,140,80);Engine.validateProgram(p);assertEquals(78.75,p.optJSONObject("advancedWeights").optJSONObject("pullup").optDouble("heavy"),.001);int[] counts={12,8,4,12,8,4,6,4,4};for(int d=0;d<9;d++){Engine.put(p,"nextDay",d);JSONObject s=Engine.start(p,1);assertEquals(counts[d],s.optJSONArray("sets").length());if(d==7)assertEquals(-1,s.optJSONArray("sets").optJSONObject(0).optDouble("kg"),.001);}}
 @Test public void feedbackAndVolumeProgressIndependentlyWithoutChangingSnapshot(){JSONObject p=ZlatAdvanced.create();ZlatAdvanced.configure(p,100,140,80);JSONObject s=Engine.start(p,1);for(int i=0;i<s.optJSONArray("sets").length();i++){JSONObject x=s.optJSONArray("sets").optJSONObject(i);Engine.put(x,"done",true);if(x.optString("advancedBlock").equals("volume"))Engine.put(x,"reps",5);}Engine.put(s,"advancedEffort",Engine.obj("{\"pullup_heavy\":2,\"dip_heavy\":0}"));String before=s.toString();JSONObject old=Engine.copy(p.optJSONObject("advancedWeights"));ZlatAdvanced.advance(p,s);JSONObject w=p.optJSONObject("advancedWeights");assertEquals(old.optJSONObject("pullup").optDouble("heavy")+2.5,w.optJSONObject("pullup").optDouble("heavy"),.001);assertEquals(old.optJSONObject("dip").optDouble("heavy"),w.optJSONObject("dip").optDouble("heavy"),.001);assertEquals(old.optJSONObject("dip").optDouble("volume")+1.25,w.optJSONObject("dip").optDouble("volume"),.001);assertEquals(old.optJSONObject("pullup").optDouble("deload")+2.5,w.optJSONObject("pullup").optDouble("deload"),.001);assertEquals(before,s.toString());String after=p.toString();ZlatAdvanced.advance(p,s);assertEquals(after,p.toString());}
 @Test public void effortDoesNotOverrideMissedReps(){assertEquals(100,ZlatAdvanced.next(100,2,"heavy",2),.001);assertEquals(95,ZlatAdvanced.next(100,1,"heavy",2),.001);assertEquals(95,ZlatAdvanced.next(100,2,"technique",2),.001);assertEquals(100,ZlatAdvanced.next(100,4,"volume",2),.001);}
 @Test public void catalogIsIdempotentAndPreservesCustomNames(){JSONObject data=Engine.obj("{\"programs\":[],\"history\":[{\"id\":\"old\"}]}");JSONObject old=Zlat.create();Engine.put(old,"name","Матвей Злат · турник и брусья");data.optJSONArray("programs").put(old);JSONObject custom=ZlatIntermediate.create();Engine.put(custom,"name","My personal cycle");data.optJSONArray("programs").put(custom);ZlatAdvanced.ensure(data);ZlatAdvanced.ensure(data);PlanPresentation.normalize(data);assertEquals(3,data.optJSONArray("programs").length());assertEquals("Zlat · Beginner",old.optString("name"));assertEquals("My personal cycle",custom.optString("name"));assertEquals("old",data.optJSONArray("history").optJSONObject(0).optString("id"));assertTrue(PlanPresentation.street(custom));}
}
